-- EteleOS: libraries/extra/libcurses/base/MKkeyname.lua, time wirte: 2026/08/08
-- This file uses the Apache-2.0 license
-- Original AWK file license: $OpenBSD: MKkeyname.awk,v 1.6 2023/10/17 09:52:08 nicm Exp $
-- Copyright 2020 Thomas E. Dickey; Copyright 1998-2016,2017 Free Software Foundation, Inc.
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software
-- and associated documentation files, to deal in the Software without restriction.
-- Native Lua port of MKkeyname.awk; it does not invoke awk.
local a={...};if #a==0 then a=arg or{}end;local big=tonumber(a[1])or 0;local entries,blob,off={},"",0
local function add(l)if l:match("^[^#]")then local k=l:match("^(%S+)");if k then if big~=0 then entries[#entries+1]=string.format("\t{ %d, %s },",off,k);blob=blob..'\n\t"'..k..'\\0"';off=off+#k+1 else entries[#entries+1]=string.format("\t{ \"%s\", %s },",k,k)end end end end
if #a>1 then for i=2,#a do local f=assert(io.open(a[i]));for l in f:lines()do add(l)end;f:close()end else for l in io.stdin:lines()do add(l)end end
print("/* generated by MKkeyname.lua */\n\n#include <curses.priv.h>\n#include <tic.h>\n")
if big~=0 then print("struct kn { short offset; int code; };\nstatic const struct kn _nc_key_names[] = {");for _,v in ipairs(entries)do print(v)end;print("\t{ -1, 0 }};\n\nstatic const char key_names[] = "..blob..";")else print("struct kn { const char *name; int code; };\nstatic const struct kn _nc_key_names[] = {");for _,v in ipairs(entries)do print(v)end;print("\t{ 0, 0 }};")end
print([[#define SIZEOF_TABLE 256
#define MyTable _nc_globals.keyname_table
#define MyInit _nc_globals.init_keyname
NCURSES_EXPORT(NCURSES_CONST char *) safe_keyname (SCREEN *sp, int c)
{
	char name[20]; NCURSES_CONST char *result = 0;
	if (c == -1) result = "-1";
	else { int i; ]])
if big~=0 then print([[for (i = 0; _nc_key_names[i].offset != -1; i++) if (_nc_key_names[i].code == c) { result = (NCURSES_CONST char *)key_names + _nc_key_names[i].offset; break; }]])else print([[for (i = 0; _nc_key_names[i].name != 0; i++) if (_nc_key_names[i].code == c) { result = (NCURSES_CONST char *)_nc_key_names[i].name; break; }]])end
print([[
		if (result == 0 && (c >= 0 && c < SIZEOF_TABLE)) {
			if (MyTable == 0) MyTable = typeCalloc(char *, SIZEOF_TABLE);
			if (MyTable != 0) { int m_prefix = (sp == 0 || sp->_use_meta);
				if (MyInit != (m_prefix + 1)) { MyInit=m_prefix+1; for (i=0;i<SIZEOF_TABLE;++i) if(MyTable[i]) FreeAndNull(MyTable[i]); }
				if (MyTable[c] == 0) { int cc=c; char *p=name;
#define P_LIMIT (sizeof(name) - (size_t) (p - name))
					if (cc >= 128 && m_prefix) { _nc_STRCPY(p,"M-",P_LIMIT);p+=2;cc-=128; }
					if (cc < 32) _nc_SPRINTF(p,_nc_SLIMIT(P_LIMIT) "^%c",cc+'@'); else if (cc == 127) _nc_STRCPY(p,"^?",P_LIMIT); else _nc_SPRINTF(p,_nc_SLIMIT(P_LIMIT) "%c",cc);
					MyTable[c]=strdup(name); }
				result=MyTable[c]; }
		}
	}
	return result;
}
NCURSES_EXPORT(NCURSES_CONST char *) keyname (int c) { return safe_keyname(CURRENT_SCREEN,c); }
#if NO_LEAKS
void _nc_keyname_leaks(void) { if (MyTable != 0) { int j; for (j=0;j<SIZEOF_TABLE;++j) FreeIfNeeded(MyTable[j]); FreeAndNull(MyTable); } }
#endif /* NO_LEAKS */]])
