#!/usr/bin/perl
# EteleOS: libraries/extra/libcurses/base/MKunctrl.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
# Perl translation of MKunctrl.awk (provenance preserved below).
#
# $OpenBSD: MKunctrl.awk,v 1.5 2023/10/17 09:52:08 nicm Exp $
# $Id: MKunctrl.awk,v 1.5 2023/10/17 09:52:08 nicm Exp $
##############################################################################
# Copyright 2020 Thomas E. Dickey                                            #
# Copyright 1998-2012,2017 Free Software Foundation, Inc.                    #
#                                                                            #
# Permission is hereby granted, free of charge, to any person obtaining a    #
# copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation  #
# the rights to use, copy, modify, merge, publish, distribute, distribute    #
# with modifications, sublicense, and/or sell copies of the Software, and to #
# permit persons to whom the Software is furnished to do so, subject to the  #
# following conditions:                                                      #
#                                                                            #
# The above copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                        #
#                                                                            #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    #
# THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER        #
# DEALINGS IN THE SOFTWARE.                                                  #
#                                                                            #
# Except as contained in this notice, the name(s) of the above copyright     #
# holders shall not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written               #
# authorization.                                                             #
##############################################################################
#
# Author: Thomas E. Dickey (1997-on)
#
use strict;
use warnings;

my %vars;
while (@ARGV && $ARGV[0] =~ /^(\w+)=(.*)$/) {
    $vars{$1} = $2;
    shift @ARGV;
}
my $bigstrings = defined $vars{bigstrings} ? $vars{bigstrings} : 0;

# Drain stdin/any file args, mirroring the awk script (which requires input
# to reach EOF before running its END block, even though it never reads
# any fields from it).
while (<>) { }

print "/* generated by MKunctrl.awk */\n";
print "\n";
print "#include <curses.priv.h>\n";
print "#include <ctype.h>\n";
print "\n";
print "#undef unctrl\n";
print "\n";

print "NCURSES_EXPORT(NCURSES_CONST char *) safe_unctrl(SCREEN *sp, chtype ch)\n";
print "{\n";
my $blob = "";
my $offset = 0;
if ($bigstrings) {
    printf "static const short unctrl_table[] = {";
} else {
    printf "static const char* const unctrl_table[] = {";
}
for (my $ch = 0; $ch < 256; $ch++) {
    my $gap = ",";
    my $part = "";
    if (($ch % 8) == 0) {
        printf "\n    ";
        if ($ch != 0) {
            $blob = $blob . "\"";
        }
        $blob = $blob . "\n    \"";
    }
    if ($bigstrings) {
        printf "%4d%s", $offset, $gap;
    }
    if ($ch < 32) {
        $part = sprintf("^\\%03o", $ch + 64);
        $offset = $offset + 3;
    } elsif ($ch == 127) {
        $part = "^?";
        $offset = $offset + 3;
    } elsif ($ch >= 128 && $ch < 160) {
        $part = sprintf("~\\%03o", $ch - 64);
        $offset = $offset + 3;
    } elsif ($ch == 255) {
        $part = "~?";
        $offset = $offset + 3;
    } elsif ($ch >= 160) {
        $part = sprintf("M-\\%03o", $ch - 128);
        $offset = $offset + 4;
    } else {
        $gap = $gap . " ";
        $part = sprintf("\\%03o", $ch);
        $offset = $offset + 2;
    }
    if ($ch == 255) {
        $gap = "\n";
    } elsif ((($ch + 1) % 8) != 0) {
        $gap = $gap . " ";
    }
    if ($bigstrings) {
        $blob = $blob . $part . "\\0";
    } else {
        printf "\"%s\"%s", $part, $gap;
    }
}
print "};\n";
$blob = $blob . "\"";

print "\n";
printf "#if NCURSES_EXT_FUNCS\n";
if ($bigstrings) {
    $blob = $blob . "\n/* printable values in 128-255 range */";
    printf "static const short unctrl_c1[] = {";
} else {
    printf "static const char* const unctrl_c1[] = {";
}
for (my $ch = 128; $ch < 256; $ch++) {
    my $gap = ",";
    if (($ch % 8) == 0) {
        if ($ch != 128) {
            $blob = $blob . "\"";
        }
        printf "\n    ";
        $blob = $blob . "\n    \"";
    }
    if ($bigstrings) {
        printf "%4d%s", $offset, $gap;
        my $part = sprintf("\\%03o\\0", $ch);
        $blob = $blob . $part;
        $offset = $offset + 2;
        if ((($ch + 1) % 8) != 0) {
            $gap = $gap . " ";
        }
    } else {
        if ($ch >= 128) {
            printf "\"\\%03o\"", $ch;
            $gap = $gap . " ";
        }
        if ($ch == 255) {
            $gap = "\n";
        } elsif ((($ch + 1) % 8) != 0) {
            $gap = $gap . " ";
        }
        printf "%s", $gap;
    }
}
print "};\n";
print "#endif /* NCURSES_EXT_FUNCS */\n";
$blob = $blob . "\"\n";

print "\n";
my $stringname;
if ($bigstrings) {
    print "static const char unctrl_blob[] = " . $blob . ";\n";
    print "\n";
    $stringname = "unctrl_blob + unctrl";
} else {
    $stringname = "unctrl";
}
print "\tint check = (int) ChCharOf(ch);\n";
print "\tconst char *result;\n";
print "\n";
print "(void) sp;\n";
print "\tif (check >= 0 && check < (int)SIZEOF(unctrl_table)) {\n";
print "#if NCURSES_EXT_FUNCS\n";
print "\t\tif ((sp != 0)\n";
print "\t\t && (sp->_legacy_coding > 1)\n";
print "\t\t && (check >= 128)\n";
print "\t\t && (check < 160))\n";
printf "\t\t\tresult = %s_c1[check - 128];\n", $stringname;
print "\t\telse\n";
print "\t\tif ((check >= 160)\n";
print "\t\t && (check < 256)\n";
print "\t\t && ((sp != 0)\n";
print "\t\t  && ((sp->_legacy_coding > 0)\n";
print "\t\t   || (sp->_legacy_coding == 0\n";
print "\t\t       && isprint(check)))))\n";
printf "\t\t\tresult = %s_c1[check - 128];\n", $stringname;
print "\t\telse\n";
print "#endif /* NCURSES_EXT_FUNCS */\n";
printf "\t\t\tresult = %s_table[check];\n", $stringname;
print "\t} else {\n";
print "\t\tresult = 0;\n";
print "\t}\n";
print "\treturn (NCURSES_CONST char *)result;\n";
print "}\n";
print "\n";
print "NCURSES_EXPORT(NCURSES_CONST char *) unctrl (chtype ch)\n";
print "{\n";
print "\treturn safe_unctrl(CURRENT_SCREEN, ch);\n";
print "}\n";
