-- EteleOS: libraries/extra/libcurses/base/MKunctrl.lua, time wirte: 2026/08/08
-- This file uses the Apache-2.0 license
-- Original AWK file license: $OpenBSD: MKunctrl.awk,v 1.5 2023/10/17 09:52:08 nicm Exp $
-- Copyright 2020 Thomas E. Dickey; Copyright 1998-2012,2017 Free Software Foundation, Inc.
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software
-- and associated documentation files, to deal in the Software without restriction.
-- Ported natively from MKunctrl.awk; it does not invoke awk.
local argv={...};if #argv==0 then argv=arg or{}end
local bigstrings=tonumber(argv[1]) or 0
local function oct(n)return string.format("\\%03o",n)end
print("/* generated by MKunctrl.lua */\n\n#include <curses.priv.h>\n#include <ctype.h>\n\n#undef unctrl\n")
print("NCURSES_EXPORT(NCURSES_CONST char *) safe_unctrl(SCREEN *sp, chtype ch)\n{")
local blob,offset="",0
io.write(bigstrings~=0 and "static const short unctrl_table[] = {" or "static const char* const unctrl_table[] = {")
for ch=0,255 do
  local part,gap="",",";if ch%8==0 then io.write("\n    ");if ch~=0 then blob=blob..'"'end;blob=blob..'\n    "'end
  if ch<32 then part="^"..oct(ch+64);offset=offset+3 elseif ch==127 then part="^?";offset=offset+3 elseif ch<160 and ch>=128 then part="~"..oct(ch-64);offset=offset+3 elseif ch==255 then part="~?";offset=offset+3 elseif ch>=160 then part="M-"..oct(ch-128);offset=offset+4 else gap=", ";part=oct(ch);offset=offset+2 end
  if ch==255 then gap="\n" elseif (ch+1)%8~=0 then gap=gap.." " end
  if bigstrings~=0 then io.write(string.format("%4d%s",offset-(#part==4 and 4 or (#part==3 and 3 or 2)),gap));blob=blob..part.."\\0" else io.write('"'..part..'"'..gap)end
end
print("};\n\n#if NCURSES_EXT_FUNCS")
io.write(bigstrings~=0 and "static const short unctrl_c1[] = {" or "static const char* const unctrl_c1[] = {")
for ch=128,255 do local gap=",";if ch%8==0 then io.write("\n    ");if ch~=128 then blob=blob..'"'end;blob=blob..'\n    "'end;if bigstrings~=0 then io.write(string.format("%4d%s",offset,gap));blob=blob..oct(ch).."\\0";offset=offset+2; if(ch+1)%8~=0 then gap=gap.." " end else io.write('"'..oct(ch)..'"');if ch==255 then gap="\n" elseif(ch+1)%8~=0 then gap=gap.." "end end; if bigstrings==0 then io.write(gap)end end
print("};\n#endif /* NCURSES_EXT_FUNCS */\n")
local name=bigstrings~=0 and "unctrl_blob + unctrl" or "unctrl"
if bigstrings~=0 then print("static const char unctrl_blob[] = "..blob..'";\n')end
print("\tint check = (int) ChCharOf(ch);\n\tconst char *result;\n\n\t(void) sp;\n\tif (check >= 0 && check < (int)SIZEOF(unctrl_table)) {\n#if NCURSES_EXT_FUNCS\n\t\tif ((sp != 0)\n\t\t && (sp->_legacy_coding > 1)\n\t\t && (check >= 128)\n\t\t && (check < 160))\n\t\t\tresult = "..name.."_c1[check - 128];\n\t\telse\n\t\tif ((check >= 160)\n\t\t && (check < 256)\n\t\t && ((sp != 0)\n\t\t  && ((sp->_legacy_coding > 0)\n\t\t   || (sp->_legacy_coding == 0\n\t\t       && isprint(check)))))\n\t\t\tresult = "..name.."_c1[check - 128];\n\t\telse\n#endif /* NCURSES_EXT_FUNCS */\n\t\t\tresult = "..name.."_table[check];\n\t} else {\n\t\tresult = 0;\n\t}\n\treturn (NCURSES_CONST char *)result;\n}\n\nNCURSES_EXPORT(NCURSES_CONST char *) unctrl (chtype ch)\n{\n\treturn safe_unctrl(CURRENT_SCREEN, ch);\n}")
