/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nlm_prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
nlm_prog_0(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct nlm_sm_status nlm_sm_notify_0_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case NLM_SM_NOTIFY:
		_xdr_argument = (xdrproc_t) xdr_nlm_sm_status;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_sm_notify_0_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		syslog (LOG_ERR, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void
nlm_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct nlm_testargs nlm_test_1_arg;
		struct nlm_lockargs nlm_lock_1_arg;
		struct nlm_cancargs nlm_cancel_1_arg;
		struct nlm_unlockargs nlm_unlock_1_arg;
		struct nlm_testargs nlm_granted_1_arg;
		struct nlm_testargs nlm_test_msg_1_arg;
		struct nlm_lockargs nlm_lock_msg_1_arg;
		struct nlm_cancargs nlm_cancel_msg_1_arg;
		struct nlm_unlockargs nlm_unlock_msg_1_arg;
		struct nlm_testargs nlm_granted_msg_1_arg;
		nlm_testres nlm_test_res_1_arg;
		nlm_res nlm_lock_res_1_arg;
		nlm_res nlm_cancel_res_1_arg;
		nlm_res nlm_unlock_res_1_arg;
		nlm_res nlm_granted_res_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case NLM_TEST:
		_xdr_argument = (xdrproc_t) xdr_nlm_testargs;
		_xdr_result = (xdrproc_t) xdr_nlm_testres;
		local = (char *(*)(char *, struct svc_req *)) nlm_test_1_svc;
		break;

	case NLM_LOCK:
		_xdr_argument = (xdrproc_t) xdr_nlm_lockargs;
		_xdr_result = (xdrproc_t) xdr_nlm_res;
		local = (char *(*)(char *, struct svc_req *)) nlm_lock_1_svc;
		break;

	case NLM_CANCEL:
		_xdr_argument = (xdrproc_t) xdr_nlm_cancargs;
		_xdr_result = (xdrproc_t) xdr_nlm_res;
		local = (char *(*)(char *, struct svc_req *)) nlm_cancel_1_svc;
		break;

	case NLM_UNLOCK:
		_xdr_argument = (xdrproc_t) xdr_nlm_unlockargs;
		_xdr_result = (xdrproc_t) xdr_nlm_res;
		local = (char *(*)(char *, struct svc_req *)) nlm_unlock_1_svc;
		break;

	case NLM_GRANTED:
		_xdr_argument = (xdrproc_t) xdr_nlm_testargs;
		_xdr_result = (xdrproc_t) xdr_nlm_res;
		local = (char *(*)(char *, struct svc_req *)) nlm_granted_1_svc;
		break;

	case NLM_TEST_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm_testargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_test_msg_1_svc;
		break;

	case NLM_LOCK_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm_lockargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_lock_msg_1_svc;
		break;

	case NLM_CANCEL_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm_cancargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_cancel_msg_1_svc;
		break;

	case NLM_UNLOCK_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm_unlockargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_unlock_msg_1_svc;
		break;

	case NLM_GRANTED_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm_testargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_granted_msg_1_svc;
		break;

	case NLM_TEST_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm_testres;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_test_res_1_svc;
		break;

	case NLM_LOCK_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_lock_res_1_svc;
		break;

	case NLM_CANCEL_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_cancel_res_1_svc;
		break;

	case NLM_UNLOCK_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_unlock_res_1_svc;
		break;

	case NLM_GRANTED_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_granted_res_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		syslog (LOG_ERR, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void
nlm_prog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		nlm_shareargs nlm_share_3_arg;
		nlm_shareargs nlm_unshare_3_arg;
		nlm_lockargs nlm_nm_lock_3_arg;
		nlm_notify nlm_free_all_3_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case NLM_SHARE:
		_xdr_argument = (xdrproc_t) xdr_nlm_shareargs;
		_xdr_result = (xdrproc_t) xdr_nlm_shareres;
		local = (char *(*)(char *, struct svc_req *)) nlm_share_3_svc;
		break;

	case NLM_UNSHARE:
		_xdr_argument = (xdrproc_t) xdr_nlm_shareargs;
		_xdr_result = (xdrproc_t) xdr_nlm_shareres;
		local = (char *(*)(char *, struct svc_req *)) nlm_unshare_3_svc;
		break;

	case NLM_NM_LOCK:
		_xdr_argument = (xdrproc_t) xdr_nlm_lockargs;
		_xdr_result = (xdrproc_t) xdr_nlm_res;
		local = (char *(*)(char *, struct svc_req *)) nlm_nm_lock_3_svc;
		break;

	case NLM_FREE_ALL:
		_xdr_argument = (xdrproc_t) xdr_nlm_notify;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm_free_all_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		syslog (LOG_ERR, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

void
nlm_prog_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		nlm4_testargs nlm4_test_4_arg;
		nlm4_lockargs nlm4_lock_4_arg;
		nlm4_cancargs nlm4_cancel_4_arg;
		nlm4_unlockargs nlm4_unlock_4_arg;
		nlm4_testargs nlm4_granted_4_arg;
		nlm4_testargs nlm4_test_msg_4_arg;
		nlm4_lockargs nlm4_lock_msg_4_arg;
		nlm4_cancargs nlm4_cancel_msg_4_arg;
		nlm4_unlockargs nlm4_unlock_msg_4_arg;
		nlm4_testargs nlm4_granted_msg_4_arg;
		nlm4_testres nlm4_test_res_4_arg;
		nlm4_res nlm4_lock_res_4_arg;
		nlm4_res nlm4_cancel_res_4_arg;
		nlm4_res nlm4_unlock_res_4_arg;
		nlm4_res nlm4_granted_res_4_arg;
		nlm4_shareargs nlm4_share_4_arg;
		nlm4_shareargs nlm4_unshare_4_arg;
		nlm4_lockargs nlm4_nm_lock_4_arg;
		nlm_notify nlm4_free_all_4_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case NLM4_TEST:
		_xdr_argument = (xdrproc_t) xdr_nlm4_testargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_testres;
		local = (char *(*)(char *, struct svc_req *)) nlm4_test_4_svc;
		break;

	case NLM4_LOCK:
		_xdr_argument = (xdrproc_t) xdr_nlm4_lockargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_res;
		local = (char *(*)(char *, struct svc_req *)) nlm4_lock_4_svc;
		break;

	case NLM4_CANCEL:
		_xdr_argument = (xdrproc_t) xdr_nlm4_cancargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_res;
		local = (char *(*)(char *, struct svc_req *)) nlm4_cancel_4_svc;
		break;

	case NLM4_UNLOCK:
		_xdr_argument = (xdrproc_t) xdr_nlm4_unlockargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_res;
		local = (char *(*)(char *, struct svc_req *)) nlm4_unlock_4_svc;
		break;

	case NLM4_GRANTED:
		_xdr_argument = (xdrproc_t) xdr_nlm4_testargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_res;
		local = (char *(*)(char *, struct svc_req *)) nlm4_granted_4_svc;
		break;

	case NLM4_TEST_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm4_testargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_test_msg_4_svc;
		break;

	case NLM4_LOCK_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm4_lockargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_lock_msg_4_svc;
		break;

	case NLM4_CANCEL_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm4_cancargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_cancel_msg_4_svc;
		break;

	case NLM4_UNLOCK_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm4_unlockargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_unlock_msg_4_svc;
		break;

	case NLM4_GRANTED_MSG:
		_xdr_argument = (xdrproc_t) xdr_nlm4_testargs;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_granted_msg_4_svc;
		break;

	case NLM4_TEST_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm4_testres;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_test_res_4_svc;
		break;

	case NLM4_LOCK_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm4_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_lock_res_4_svc;
		break;

	case NLM4_CANCEL_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm4_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_cancel_res_4_svc;
		break;

	case NLM4_UNLOCK_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm4_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_unlock_res_4_svc;
		break;

	case NLM4_GRANTED_RES:
		_xdr_argument = (xdrproc_t) xdr_nlm4_res;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_granted_res_4_svc;
		break;

	case NLM4_SHARE:
		_xdr_argument = (xdrproc_t) xdr_nlm4_shareargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_shareres;
		local = (char *(*)(char *, struct svc_req *)) nlm4_share_4_svc;
		break;

	case NLM4_UNSHARE:
		_xdr_argument = (xdrproc_t) xdr_nlm4_shareargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_shareres;
		local = (char *(*)(char *, struct svc_req *)) nlm4_unshare_4_svc;
		break;

	case NLM4_NM_LOCK:
		_xdr_argument = (xdrproc_t) xdr_nlm4_lockargs;
		_xdr_result = (xdrproc_t) xdr_nlm4_res;
		local = (char *(*)(char *, struct svc_req *)) nlm4_nm_lock_4_svc;
		break;

	case NLM4_FREE_ALL:
		_xdr_argument = (xdrproc_t) xdr_nlm_notify;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nlm4_free_all_4_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		syslog (LOG_ERR, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
