/*
 * Copyright 2022 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _osssys_4_4_2_SH_MASK_HEADER
#define _osssys_4_4_2_SH_MASK_HEADER

// addressBlock: aid_osssys_osssysdec
//IH_VMID_0_LUT
#define IH_VMID_0_LUT__PASID__SHIFT 0x0
#define IH_VMID_0_LUT__PASID_MASK 0x0000FFFFL
//IH_RB_CNTL
#define IH_RB_CNTL__RB_ENABLE__SHIFT 0x0
#define IH_RB_CNTL__RB_SIZE__SHIFT 0x1
#define IH_RB_CNTL__RB_GPU_TS_ENABLE__SHIFT 0x7
#define IH_RB_CNTL__WPTR_WRITEBACK_ENABLE__SHIFT 0x8
#define IH_RB_CNTL__RB_FULL_DRAIN_ENABLE__SHIFT 0x9
#define IH_RB_CNTL__WPTR_OVERFLOW_ENABLE__SHIFT 0x10
#define IH_RB_CNTL__ENABLE_INTR__SHIFT 0x11
#define IH_RB_CNTL__MC_SNOOP__SHIFT 0x14
#define IH_RB_CNTL__RPTR_REARM__SHIFT 0x15
#define IH_RB_CNTL__MC_RO__SHIFT 0x16
#define IH_RB_CNTL__MC_VMID__SHIFT 0x18
#define IH_RB_CNTL__MC_SPACE__SHIFT 0x1c
#define IH_RB_CNTL__WPTR_OVERFLOW_CLEAR__SHIFT 0x1f
#define IH_RB_CNTL__RB_ENABLE_MASK 0x00000001L
#define IH_RB_CNTL__RB_SIZE_MASK 0x0000003EL
#define IH_RB_CNTL__RB_GPU_TS_ENABLE_MASK 0x00000080L
#define IH_RB_CNTL__WPTR_WRITEBACK_ENABLE_MASK 0x00000100L
#define IH_RB_CNTL__RB_FULL_DRAIN_ENABLE_MASK 0x00000200L
#define IH_RB_CNTL__WPTR_OVERFLOW_ENABLE_MASK 0x00010000L
#define IH_RB_CNTL__ENABLE_INTR_MASK 0x00020000L
#define IH_RB_CNTL__MC_SNOOP_MASK 0x00100000L
#define IH_RB_CNTL__RPTR_REARM_MASK 0x00200000L
#define IH_RB_CNTL__MC_RO_MASK 0x00400000L
#define IH_RB_CNTL__MC_VMID_MASK 0x0F000000L
#define IH_RB_CNTL__MC_SPACE_MASK 0x70000000L
#define IH_RB_CNTL__WPTR_OVERFLOW_CLEAR_MASK 0x80000000L
//IH_RB_WPTR
#define IH_RB_WPTR__RB_OVERFLOW__SHIFT 0x0
#define IH_RB_WPTR__RB_OVERFLOW_MASK 0x00000001L
//IH_DOORBELL_RPTR
#define IH_DOORBELL_RPTR__OFFSET__SHIFT 0x0
#define IH_DOORBELL_RPTR__ENABLE__SHIFT 0x1c
#define IH_DOORBELL_RPTR__OFFSET_MASK 0x03FFFFFFL
#define IH_DOORBELL_RPTR__ENABLE_MASK 0x10000000L
//IH_RB_CNTL_RING1
#define IH_RB_CNTL_RING1__RB_USED_INT_THRESHOLD__SHIFT 0xc
#define IH_RB_CNTL_RING1__RB_USED_INT_THRESHOLD_MASK 0x0000F000L
//IH_CNTL
#define IH_CNTL__MC_WR_CLEAN_CNT__SHIFT 0x14
#define IH_CNTL__MC_WR_CLEAN_CNT_MASK 0x01F00000L
//IH_CNTL2
#define IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_TIMEOUT__SHIFT 0x0
#define IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_ENABLE__SHIFT 0x8
#define IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_TIMEOUT_MASK 0x0000001FL
#define IH_CNTL2__SELF_IV_FORCE_WPTR_UPDATE_ENABLE_MASK 0x00000100L
//IH_INT_FLOOD_CNTL
#define IH_INT_FLOOD_CNTL__FLOOD_CNTL_ENABLE__SHIFT 0x3
#define IH_INT_FLOOD_CNTL__FLOOD_CNTL_ENABLE_MASK 0x00000008L
//IH_STORM_CLIENT_LIST_CNTL
#define IH_STORM_CLIENT_LIST_CNTL__CLIENT18_IS_STORM_CLIENT__SHIFT 0x12
#define IH_STORM_CLIENT_LIST_CNTL__CLIENT18_IS_STORM_CLIENT_MASK 0x00040000L
//IH_CLK_CTRL
#define IH_CLK_CTRL__IH_RETRY_INT_CAM_MEM_CLK_SOFT_OVERRIDE__SHIFT 0x19
#define IH_CLK_CTRL__IH_BUFFER_MEM_CLK_SOFT_OVERRIDE__SHIFT 0x1a
#define IH_CLK_CTRL__DBUS_MUX_CLK_SOFT_OVERRIDE__SHIFT 0x1b
#define IH_CLK_CTRL__OSSSYS_SHARE_CLK_SOFT_OVERRIDE__SHIFT 0x1c
#define IH_CLK_CTRL__LIMIT_SMN_CLK_SOFT_OVERRIDE__SHIFT 0x1d
#define IH_CLK_CTRL__DYN_CLK_SOFT_OVERRIDE__SHIFT 0x1e
#define IH_CLK_CTRL__REG_CLK_SOFT_OVERRIDE__SHIFT 0x1f
#define IH_CLK_CTRL__IH_RETRY_INT_CAM_MEM_CLK_SOFT_OVERRIDE_MASK 0x02000000L
#define IH_CLK_CTRL__IH_BUFFER_MEM_CLK_SOFT_OVERRIDE_MASK 0x04000000L
#define IH_CLK_CTRL__DBUS_MUX_CLK_SOFT_OVERRIDE_MASK 0x08000000L
#define IH_CLK_CTRL__OSSSYS_SHARE_CLK_SOFT_OVERRIDE_MASK 0x10000000L
#define IH_CLK_CTRL__LIMIT_SMN_CLK_SOFT_OVERRIDE_MASK 0x20000000L
#define IH_CLK_CTRL__DYN_CLK_SOFT_OVERRIDE_MASK 0x40000000L
#define IH_CLK_CTRL__REG_CLK_SOFT_OVERRIDE_MASK 0x80000000L
//IH_MEM_POWER_CTRL
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_CTRL_EN__SHIFT 0x0
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_LS_EN__SHIFT 0x1
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_DS_EN__SHIFT 0x2
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_SD_EN__SHIFT 0x3
#define IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_LS_EN__SHIFT 0x11
#define IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_DS_EN__SHIFT 0x12
#define IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_SD_EN__SHIFT 0x13
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_CTRL_EN_MASK 0x00000001L
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_LS_EN_MASK 0x00000002L
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_DS_EN_MASK 0x00000004L
#define IH_MEM_POWER_CTRL__IH_BUFFER_MEM_POWER_SD_EN_MASK 0x00000008L
#define IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_LS_EN_MASK 0x00020000L
#define IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_DS_EN_MASK 0x00040000L
#define IH_MEM_POWER_CTRL__IH_RETRY_INT_CAM_MEM_POWER_SD_EN_MASK 0x00080000L
//IH_RETRY_INT_CAM_CNTL
#define IH_RETRY_INT_CAM_CNTL__ENABLE__SHIFT 0x10
#define IH_RETRY_INT_CAM_CNTL__ENABLE_MASK 0x00010000L
//IH_CLIENT_CFG_DATA
#define IH_CLIENT_CFG_DATA__CLIENT_TYPE__SHIFT 0x13
#define IH_CLIENT_CFG_DATA__RING_ID__SHIFT 0x14
#define IH_CLIENT_CFG_DATA__CLIENT_TYPE_MASK 0x00080000L
#define IH_CLIENT_CFG_DATA__RING_ID_MASK 0x00300000L
//IH_CHICKEN
#define IH_CHICKEN__MC_SPACE_GPA_ENABLE__SHIFT 0x4
#define IH_CHICKEN__MC_SPACE_GPA_ENABLE_MASK 0x00000010L
#endif
