/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bootparam_prot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

void
bootparamprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		bp_whoami_arg bootparamproc_whoami_1_arg;
		bp_getfile_arg bootparamproc_getfile_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case BOOTPARAMPROC_WHOAMI:
		_xdr_argument = (xdrproc_t) xdr_bp_whoami_arg;
		_xdr_result = (xdrproc_t) xdr_bp_whoami_res;
		local = (char *(*)(char *, struct svc_req *)) bootparamproc_whoami_1_svc;
		break;

	case BOOTPARAMPROC_GETFILE:
		_xdr_argument = (xdrproc_t) xdr_bp_getfile_arg;
		_xdr_result = (xdrproc_t) xdr_bp_getfile_res;
		local = (char *(*)(char *, struct svc_req *)) bootparamproc_getfile_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
