-- EteleOS: kernel/dev/usb/devlist2h.lua, time write: 2026/08/08
-- This file uses the Apache-2.0 license
--
-- Original AWK file license:
-- $OpenBSD: devlist2h.awk,v 1.11 2007/06/04 10:34:04 mbalmer Exp $
-- $NetBSD: devlist2h.awk,v 1.9 2001/01/18 20:28:22 jdolecek Exp $
--
-- Copyright (c) 1995, 1996 Christopher G. Demetriou
-- All rights reserved.
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
-- 1. Redistributions of source code must retain the above copyright
--    notice, this list of conditions and the following disclaimer.
-- 2. Redistributions in binary form must reproduce the above copyright
--    notice, this list of conditions and the following disclaimer in the
--    documentation and/or other materials provided with the distribution.
-- 3. All advertising materials mentioning features or use of this software
--    must display the following acknowledgement:
--      This product includes software developed by Christopher G. Demetriou.
-- 4. The name of the author may not be used to endorse or promote products
--    derived from this software without specific prior written permission
--
-- THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
-- IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
-- OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
-- IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
-- INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
-- NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
-- DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
-- THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
-- (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
-- THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

if io.stdout and io.stdout.setvbuf then io.stdout:setvbuf("no") end

local argv = {...}; if #argv == 0 then argv = arg or {} end
local infile = argv[1] or "usbdevs"

local function split_fields(line)
    local fields = {}
    for f in line:gmatch("%S+") do
        fields[#fields + 1] = f
    end
    return fields
end

local dfile_path = "usbdevs_data.h"
local hfile_path = "usbdevs.h"

local df = io.open(dfile_path, "w")
local hf = io.open(hfile_path, "w")
if not df or not hf then
    io.stderr:write("devlist2h.lua: cannot open output files\n")
    os.exit(1)
end

local nproducts  = 0
local nvendors   = 0
local blanklines = 0
local vendors    = {}
local products   = {}
local vendorindex = {}

local inp = io.open(infile, "r")
if not inp then
    io.stderr:write("devlist2h.lua: cannot open " .. infile .. "\n")
    os.exit(1)
end

local nr = 0
for line in inp:lines() do
    nr = nr + 1
    local f = split_fields(line)
    local NF = #f

    if nr == 1 then
        local VERSION = line:gsub("%$", "")
        for _, fh in ipairs({df, hf}) do
            fh:write("/*\t$OpenBSD$\t*/\n\n")
            fh:write("/*\n")
            fh:write(" * THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT.\n")
            fh:write(" *\n")
            fh:write(" * generated from:\n")
            fh:write(string.format(" *\t%s\n", VERSION))
            fh:write(" */\n")
        end
        goto continue
    end

    if NF > 0 and f[1] == "vendor" then
        nvendors = nvendors + 1
        local vname = f[2]
        local vid   = f[3]
        vendorindex[vname] = nvendors

        hf:write(string.format("#define\tUSB_VENDOR_%s\t%s\t", vname, vid))

        local oparen  = false
        local ocomment = false
        local fid = 4
        local str_parts = {}
        if fid <= NF then
            hf:write("/* ")
            ocomment = true
        end
        while fid <= NF do
            if f[fid] == "#" then
                hf:write("(")
                oparen = true
                fid = fid + 1
            elseif oparen then
                hf:write(f[fid])
                if fid < NF then hf:write(" ") end
                fid = fid + 1
            else
                str_parts[#str_parts + 1] = f[fid]
                hf:write(f[fid])
                if fid < NF then hf:write(" ") end
                fid = fid + 1
            end
        end
        if oparen   then hf:write(")") end
        if ocomment then hf:write(" */") end
        hf:write("\n")

        vendors[nvendors] = {name=vname, id=vid, parts=str_parts}
        goto continue
    end

    if NF > 0 and f[1] == "product" then
        nproducts = nproducts + 1
        local pvendor  = f[2]
        local pproduct = f[3]
        local pid      = f[4]

        hf:write(string.format("#define\tUSB_PRODUCT_%s_%s\t%s\t",
            pvendor, pproduct, pid))

        local oparen  = false
        local ocomment = false
        local fid = 5
        local desc_parts = {}
        if fid <= NF then
            hf:write("/* ")
            ocomment = true
        end
        while fid <= NF do
            if f[fid] == "#" then
                hf:write("(")
                oparen = true
                fid = fid + 1
            elseif oparen then
                hf:write(f[fid])
                if fid < NF then hf:write(" ") end
                fid = fid + 1
            else
                desc_parts[#desc_parts + 1] = f[fid]
                hf:write(f[fid])
                if fid < NF then hf:write(" ") end
                fid = fid + 1
            end
        end
        if oparen   then hf:write(")") end
        if ocomment then hf:write(" */") end
        hf:write("\n")

        products[nproducts] = {
            vendor  = pvendor,
            product = pproduct,
            id      = pid,
            desc    = desc_parts,
        }
        goto continue
    end

    if line == "" then blanklines = blanklines + 1 end
    hf:write(line .. "\n")
    if blanklines < 2 then
        df:write(line .. "\n")
    end

    ::continue::
end

inp:close()

df:write("\n")
df:write("/*\n")
df:write(' * Descriptions of known vendors and devices ("products").\n')
df:write(" */\n")
df:write("struct usb_known_vendor {\n")
df:write("\tu_int16_t\tvendor;\n")
df:write("\tchar\t\t*vendorname;\n")
df:write("};\n\n")

df:write("struct usb_known_product {\n")
df:write("\tu_int16_t\tvendor;\n")
df:write("\tu_int16_t\tproduct;\n")
df:write("\tchar\t\t*productname;\n")
df:write("};\n\n")

df:write("const struct usb_known_product usb_known_products[] = {\n")
for i = 1, nproducts do
    local p = products[i]
    df:write("\t{\n")
    df:write(string.format("\t    USB_VENDOR_%s, USB_PRODUCT_%s_%s,\n",
        p.vendor, p.vendor, p.product))
    df:write('\t    "')
    local needspace = false
    for _, part in ipairs(p.desc) do
        if needspace then df:write(" ") end
        df:write(part)
        needspace = true
    end
    df:write('",\n')
    df:write("\t},\n")
end
df:write("\t{ 0, 0, NULL }\n")
df:write("};\n\n")

df:write("const struct usb_known_vendor usb_known_vendors[] = {\n")
for i = 1, nvendors do
    local v = vendors[i]
    df:write("\t{\n")
    df:write(string.format("\t    USB_VENDOR_%s,\n", v.name))
    df:write('\t    "')
    local needspace = false
    for _, part in ipairs(v.parts) do
        if needspace then df:write(" ") end
        df:write(part)
        needspace = true
    end
    df:write('",\n')
    df:write("\t},\n")
end
df:write("\t{ 0, NULL }\n")
df:write("};\n")

df:close()
hf:close()
