-- EteleOS: kernel/dev/usb/makemap.lua, time write: 2026/08/08
-- This file uses the Apache-2.0 license
--
-- Original AWK file license:
-- $OpenBSD: makemap.awk,v 1.18 2026/01/06 18:42:18 helg Exp $
--
-- Copyright (c) 2005, Miodrag Vallat
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
-- 1. Redistributions of source code must retain the above copyright
--    notice, this list of conditions and the following disclaimer.
-- 2. Redistributions in binary form must reproduce the above copyright
--    notice, this list of conditions and the following disclaimer in the
--    documentation and/or other materials provided with the distribution.
--
-- THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
-- IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
-- INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
-- HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
-- STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
-- ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-- POSSIBILITY OF SUCH DAMAGE.

if io.stdout and io.stdout.setvbuf then io.stdout:setvbuf("no") end

local argv = {...}; if #argv == 0 then argv = arg or {} end
local infile = argv[1]

local rcsid = "$OpenBSD: makemap.awk,v 1.18 2026/01/06 18:42:18 helg Exp $"

local conv = {}
for i = 0, 255 do conv[i] = -1 end

conv[1]=41; conv[2]=30; conv[3]=31; conv[4]=32; conv[5]=33; conv[6]=34
conv[7]=35; conv[8]=36; conv[9]=37; conv[10]=38; conv[11]=39; conv[12]=45
conv[13]=46; conv[14]=42; conv[15]=43; conv[16]=20; conv[17]=26; conv[18]=8
conv[19]=21; conv[20]=23; conv[21]=28; conv[22]=24; conv[23]=12; conv[24]=18
conv[25]=19; conv[26]=47; conv[27]=48; conv[28]=40; conv[29]=224; conv[30]=4
conv[31]=22; conv[32]=7; conv[33]=9; conv[34]=10; conv[35]=11; conv[36]=13
conv[37]=14; conv[38]=15; conv[39]=51; conv[40]=52; conv[41]=53; conv[42]=225
conv[43]=50; conv[44]=29; conv[45]=27; conv[46]=6; conv[47]=25; conv[48]=5
conv[49]=17; conv[50]=16; conv[51]=54; conv[52]=55; conv[53]=56; conv[54]=229
conv[55]=85; conv[56]=226; conv[57]=44; conv[58]=57; conv[59]=58; conv[60]=59
conv[61]=60; conv[62]=61; conv[63]=62; conv[64]=63; conv[65]=64; conv[66]=65
conv[67]=66; conv[68]=67; conv[69]=83; conv[70]=71; conv[71]=95; conv[72]=96
conv[73]=97; conv[74]=86; conv[75]=92; conv[76]=93; conv[77]=94; conv[78]=87
conv[79]=89; conv[80]=90; conv[81]=91; conv[82]=98; conv[83]=99; conv[86]=100
conv[87]=68; conv[88]=69; conv[91]=104; conv[92]=105; conv[93]=106; conv[99]=107
conv[100]=108; conv[101]=109; conv[102]=110; conv[103]=111; conv[104]=112
conv[105]=113; conv[106]=114; conv[107]=115; conv[112]=136; conv[115]=135
conv[121]=138; conv[123]=139; conv[125]=137; conv[127]=72; conv[156]=88
conv[157]=228; conv[160]=127; conv[170]=70; conv[174]=129; conv[176]=128
conv[181]=84; conv[184]=230
conv[199]=74; conv[200]=82; conv[201]=75; conv[203]=80; conv[205]=79
conv[207]=77; conv[208]=81; conv[209]=78; conv[210]=73; conv[211]=76
conv[219]=227; conv[220]=231; conv[221]=101

local ifdepth = 0
local ignores = {}
local ignore  = 0
local declk   = 0
local haskeys = 0
local kbde    = 0
local kbfr    = 0
local nmaps   = 0

local lines   = {}
local mapname = ""

local function split_fields(line)
    local fields = {}
    for f in line:gmatch("%S+") do
        fields[#fields + 1] = f
    end
    return fields
end

local inp = infile and io.open(infile, "r") or io.stdin
if not inp then
    io.stderr:write("makemap.lua: cannot open " .. tostring(infile) .. "\n")
    os.exit(1)
end

local nr = 0
for line in inp:lines() do
    nr = nr + 1
    local f  = split_fields(line)
    local NF = #f

    if nr == 1 then
        local VERSION = line:gsub("%$", "")
        rcsid = rcsid:gsub("%$", "")
        io.write("/*\t\\$OpenBSD\\$\t*/\n\n")
        io.write("/*\n")
        io.write(" * THIS FILE IS AUTOMAGICALLY GENERATED.  DO NOT EDIT.\n")
        io.write(" *\n")
        io.write(" * generated by:\n")
        io.write(string.format(" *\t%s\n", rcsid))
        io.write(" * generated from:\n")
        io.write(" */\n")
        io.write(VERSION .. "\n")
        goto next_line
    end

    if line:match("^#if") then
        ignores[ifdepth] = ignore
        if NF >= 2 and f[2] == "0" then
            ignore = 1
        end
        ifdepth = ifdepth + 1
        if ignore == 1 then goto next_line end
    end

    if line:match("^#endif") then
        local oldignore = ignore
        ifdepth = ifdepth - 1
        ignore = ignores[ifdepth] or 0
        ignores[ifdepth] = 0
        if oldignore == 1 then goto next_line end
    end

    if NF >= 1 and f[1] == "#include" then
        if ignore == 1 then goto next_line end
        if f[2] == "<dev/pckbc/wskbdmap_mfii.h>" then goto next_line end
        io.write(string.format("#include %s\n", f[2]))
        goto next_line
    end

    if NF >= 1 and (f[1] == "#define" or f[1] == "#undef") then
        if ignore == 1 then goto next_line end
        io.write(line .. "\n")
        goto next_line
    end

    if line:match("declk%[") then
        declk = 1
        goto next_line
    end
    if line:match("declk") then
        goto next_line
    end

    if line:match("pckbd") then
        line = line:gsub("pckbd", "ukbd")
        f = split_fields(line)
        NF = #f
        mapname = f[4] or mapname
    end

    if line:match("KC") then
        if ignore == 1 then goto next_line end
        if declk == 1   then goto next_line end

        haskeys = 1

        local sidx_str = (f[1] or ""):match("KC%((%d+)%)")
        if not sidx_str then goto next_line end
        local orig = tonumber(sidx_str)
        local id   = conv[orig] or -1

        if orig == 183 then goto next_line end

        if id == -1 then
            io.write(string.format("/* initially KC(%d),", orig))
            for fi = 2, NF do
                if f[fi] ~= "/*" and f[fi] ~= "*/" then
                    io.write(string.format("\t%s", f[fi]))
                end
            end
            io.write("\t*/\n")
        else
            lines[id] = string.format("    KC(%d),\t", id)
            local comma = 0
            for fi = 2, NF do
                local fv = f[fi]
                local l  = #fv
                if fv == "/*" then comma = comma + 1 end
                if comma == 0 and fv:sub(l,l) ~= "," then
                    lines[id] = lines[id] .. fv .. ","
                    l = l + 1
                else
                    lines[id] = lines[id] .. fv
                end
                if comma == 0 and fi ~= NF then
                    if l < 16 then lines[id] = lines[id] .. "\t" end
                    if l < 8  then lines[id] = lines[id] .. "\t" end
                end
                if fv == "*/" then comma = comma - 1 end
            end
        end
        goto next_line
    end

    if line:match("};") then
        if ignore == 1 then goto next_line end
        if declk == 1 then
            declk = 0
            goto next_line
        end

        if haskeys == 1 then
            if not lines[76] then
                lines[76] = lines[42]
                if lines[76] then
                    lines[76] = lines[76]:gsub("42", "76", 1)
                end
            end
            if not lines[49] then
                lines[49] = lines[50]
                if lines[49] then
                    lines[49] = lines[49]:gsub("50", "49", 1)
                end
            end

            if nmaps == 0 then
                lines[102] = "    KC(102),\tKS_Cmd_Sleep,"
                lines[116] = "    KC(116),\tKS_Open,"
                lines[117] = "    KC(117),\tKS_Help,"
                lines[118] = "    KC(118),\tKS_Props,"
                lines[119] = "    KC(119),\tKS_Front,"
                lines[120] = "    KC(120),\tKS_Cmd,"
                lines[121] = "    KC(121),\tKS_Again,"
                lines[122] = "    KC(122),\tKS_Undo,"
                lines[123] = "    KC(123),\tKS_Cut,"
                lines[124] = "    KC(124),\tKS_Copy,"
                lines[125] = "    KC(125),\tKS_Paste,"
                lines[126] = "    KC(126),\tKS_Find,"
                lines[232] = "    KC(232),\tKS_Cmd_BrightnessUp,"
                lines[233] = "    KC(233),\tKS_Cmd_BrightnessDown,"
                lines[234] = "    KC(234),\tKS_Cmd_KbdBacklightToggle,"
                lines[235] = "    KC(235),\tKS_Cmd_KbdBacklightUp,"
                lines[236] = "    KC(236),\tKS_Cmd_KbdBacklightDown,"
            end
            nmaps = nmaps + 1

            for i = 0, 255 do
                if lines[i] then
                    io.write(lines[i] .. "\n")
                    lines[i] = nil
                end
            end

            haskeys = 0

            if mapname == "ukbd_keydesc_de[]" then
                io.write(line .. "\n")
                io.write("\nstatic const keysym_t ukbd_keydesc_de_apple[] = {\n")
                io.write("/*  pos\t\tnormal\t\tshifted\t\taltgr\t\tshifted-altgr */\n")
                io.write("    KC(15),\tKS_l,\t\tKS_L,\t\tKS_at,\n")
                io.write("    KC(34),\tKS_5,\t\tKS_percent,\tKS_bracketleft,\n")
                io.write("    KC(35),\tKS_6,\t\tKS_ampersand,\tKS_bracketright,\n")
                io.write("    KC(36),\tKS_7,\t\tKS_slash,\tKS_bar,\t\tKS_backslash,\n")
                io.write("    KC(37),\tKS_8,\t\tKS_parenleft,\tKS_braceleft,\n")
                io.write("    KC(38),\tKS_9,\t\tKS_parenright,\tKS_braceright,\n")
                io.write("    KC(17),\tKS_n,\t\tKS_N,\t\tKS_asciitilde,\n")
                goto next_line
            elseif mapname == "ukbd_keydesc_fr[]" then
                io.write(line .. "\n")
                io.write("\nstatic const keysym_t ukbd_keydesc_fr_apple[] = {\n")
                io.write("    KC(5),\tKS_b,\t\tKS_B,\t\tKS_ssharp,\n")
                io.write("    KC(8),\tKS_e,\t\tKS_E,\t\tKS_ecircumflex,\tKS_Ecircumflex,\n")
                io.write("    KC(11),\tKS_h,\t\tKS_H,\t\tKS_Igrave,\tKS_Icircumflex,\n")
                io.write("    KC(12),\tKS_i,\t\tKS_I,\t\tKS_icircumflex,\tKS_idiaeresis,\n")
                io.write("    KC(13),\tKS_j,\t\tKS_J,\t\tKS_Idiaeresis,\tKS_Iacute,\n")
                io.write("    KC(14),\tKS_k,\t\tKS_K,\t\tKS_Egrave,\tKS_Ediaeresis,\n")
                io.write("    KC(15),\tKS_l,\t\tKS_L,\t\tKS_voidSymbol,\tKS_bar,\n")
                io.write("    KC(16),\tKS_comma,\tKS_question,\tKS_voidSymbol,\tKS_questiondown,\n")
                io.write("    KC(17),\tKS_n,\t\tKS_N,\t\tKS_asciitilde,\n")
                io.write("    KC(20),\tKS_a,\t\tKS_A,\t\tKS_ae,\t\tKS_AE,\n")
                io.write("    KC(21),\tKS_r,\t\tKS_R,\t\tKS_registered,\tKS_comma,\n")
                io.write("    KC(22),\tKS_s,\t\tKS_S,\t\tKS_Ograve,\n")
                io.write("    KC(26),\tKS_z,\t\tKS_Z,\t\tKS_Acircumflex,\tKS_Aring,\n")
                io.write("    KC(28),\tKS_y,\t\tKS_Y,\t\tKS_Uacute,\n")
                io.write("    KC(31),\tKS_eacute,\tKS_2,\t\tKS_ediaeresis,\n")
                io.write('    KC(32),\tKS_quotedbl,\tKS_3,\n')
                io.write("    KC(33),\tKS_apostrophe,\tKS_4,\n")
                io.write("    KC(34),\tKS_parenleft,\tKS_5,\t\tKS_braceleft,\tKS_bracketleft,\n")
                io.write("    KC(35),\tKS_section,\tKS_6,\n")
                io.write("    KC(36),\tKS_egrave,\tKS_7,\t\tKS_guillemotleft,\n")
                io.write("\t\t\t\t\t\tKS_guillemotright,\n")
                io.write("    KC(37),\tKS_exclam,\tKS_8,\n")
                io.write("    KC(38),\tKS_ccedilla,\tKS_9,\t\tKS_Ccedilla,\tKS_Aacute,\n")
                io.write("    KC(37),\tKS_exclam,\tKS_8,\t\tKS_exclamdown,\tKS_Ucircumflex,\n")
                io.write("    KC(39),\tKS_agrave,\tKS_0,\t\tKS_oslash,\tKS_Ooblique,\n")
                io.write("    KC(45),\tKS_parenright,\tKS_degree,\tKS_braceright,\tKS_bracketright,\n")
                io.write("    KC(46),\tKS_minus,\tKS_underscore,\n")
                io.write("    KC(47),\tKS_dead_circumflex, KS_dead_diaeresis,\n")
                io.write("\t\t\t\t\t\tKS_ocircumflex,\tKS_Ocircumflex,\n")
                io.write("    KC(48),\tKS_dollar,\tKS_asterisk,\tKS_cent,\tKS_yen,\n")
                io.write("    KC(50),\tKS_grave,\tKS_sterling,\tKS_at,\t\tKS_numbersign,\n")
                io.write("    KC(51),\tKS_m,\t\tKS_M,\t\tKS_mu,\t\tKS_Oacute,\n")
                io.write("    KC(52),\tKS_ugrave,\tKS_percent,\tKS_Ugrave,\n")
                io.write("    KC(53),\tKS_at,\t\tKS_numbersign,\n")
                io.write("    KC(55),\tKS_colon,\tKS_slash,\tKS_voidSymbol,\tKS_backslash,\n")
                io.write("    KC(56),\tKS_equal,\tKS_plus,\n")
                io.write("    KC(103),\tKS_KP_Equal,\n")
                io.write("    KC(231),\tKS_Mode_switch,\tKS_Multi_key,\n")
                goto next_line
            elseif mapname == "ukbd_keydesc_pt[]" then
                io.write(line .. "\n")
                io.write("\nstatic const keysym_t ukbd_keydesc_pt_apple[] = {\n")
                io.write("/*  pos\t\tnormal\t\tshifted */\n")
                io.write("    KC(46),\tKS_plus,\tKS_asterisk,\n")
                io.write("    KC(47),\tKS_masculine,\tKS_ordfeminine,\n")
                io.write("    KC(50),\tKS_backslash,\tKS_bar,\n")
                io.write("    KC(52),\tKS_dead_tilde,\tKS_dead_circumflex\n")
                goto next_line
            end
        end
    end

    if line:match("KB_DE") then
        io.write(line .. "\n")
        kbde = kbde + 1
        if kbde == 1 then
            io.write("\tKBD_MAP(KB_DE | KB_APPLE,\tKB_DE,\tukbd_keydesc_de_apple),\n")
        elseif kbde == 2 then
            io.write("\tKBD_MAP(KB_DE | KB_APPLE | KB_NODEAD,\tKB_DE | KB_APPLE,\n")
            io.write("\t\tukbd_keydesc_de_nodead),\n")
        end
        goto next_line
    end

    if line:match("KB_FR") then
        io.write(line .. "\n")
        kbfr = kbfr + 1
        if kbfr == 1 then
            io.write("\tKBD_MAP(KB_FR | KB_APPLE,\tKB_FR,\tukbd_keydesc_fr_apple),\n")
        elseif kbfr == 3 then
            io.write("\tKBD_MAP(KB_FR | KB_APPLE | KB_SWAPCTRLCAPS,\tKB_FR | KB_APPLE,\n")
            io.write("\t\tukbd_keydesc_swapctrlcaps),\n")
        end
        goto next_line
    end

    if line:match("KB_PT") then
        io.write(line .. "\n")
        io.write("\tKBD_MAP(KB_PT | KB_APPLE,\tKB_PT,\tukbd_keydesc_pt_apple),\n")
        goto next_line
    end

    if ignore == 1 then goto next_line end
    if declk == 1   then goto next_line end
    io.write(line .. "\n")

    ::next_line::
end

if infile then inp:close() end
