# PeteleOS: kernel/dev/usb/makemap.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
#	$OpenBSD: makemap.awk,v 1.18 2026/01/06 18:42:18 helg Exp $
#
# Copyright (c) 2005, Miodrag Vallat
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
#
# This script attempts to convert, with minimal hacks and losses, the
# regular PS/2 keyboard (pckbd) layout tables into USB keyboard (ukbd)
# layout tables.
#

use strict;
use warnings;
no warnings 'uninitialized';

my $rcsid = '$OpenBSD: makemap.awk,v 1.18 2026/01/06 18:42:18 helg Exp $';
my $ifdepth = 0;
my $ignore = 0;
my $declk = 0;
my $haskeys = 0;
my $kbde = 0;
my $kbfr = 0;
my $nmaps = 0;

# PS/2 id -> UKBD conversion table, or "sanity lossage 101"
my @conv = (-1) x 256;

$conv[1] = 41;
$conv[2] = 30;
$conv[3] = 31;
$conv[4] = 32;
$conv[5] = 33;
$conv[6] = 34;
$conv[7] = 35;
$conv[8] = 36;
$conv[9] = 37;
$conv[10] = 38;
$conv[11] = 39;
$conv[12] = 45;
$conv[13] = 46;
$conv[14] = 42;
$conv[15] = 43;
$conv[16] = 20;
$conv[17] = 26;
$conv[18] = 8;
$conv[19] = 21;
$conv[20] = 23;
$conv[21] = 28;
$conv[22] = 24;
$conv[23] = 12;
$conv[24] = 18;
$conv[25] = 19;
$conv[26] = 47;
$conv[27] = 48;
$conv[28] = 40;
$conv[29] = 224;
$conv[30] = 4;
$conv[31] = 22;
$conv[32] = 7;
$conv[33] = 9;
$conv[34] = 10;
$conv[35] = 11;
$conv[36] = 13;
$conv[37] = 14;
$conv[38] = 15;
$conv[39] = 51;
$conv[40] = 52;
$conv[41] = 53;
$conv[42] = 225;
$conv[43] = 50;
$conv[44] = 29;
$conv[45] = 27;
$conv[46] = 6;
$conv[47] = 25;
$conv[48] = 5;
$conv[49] = 17;
$conv[50] = 16;
$conv[51] = 54;
$conv[52] = 55;
$conv[53] = 56;
$conv[54] = 229;
$conv[55] = 85;
$conv[56] = 226;
$conv[57] = 44;
$conv[58] = 57;
$conv[59] = 58;
$conv[60] = 59;
$conv[61] = 60;
$conv[62] = 61;
$conv[63] = 62;
$conv[64] = 63;
$conv[65] = 64;
$conv[66] = 65;
$conv[67] = 66;
$conv[68] = 67;
$conv[69] = 83;
$conv[70] = 71;
$conv[71] = 95;
$conv[72] = 96;
$conv[73] = 97;
$conv[74] = 86;
$conv[75] = 92;
$conv[76] = 93;
$conv[77] = 94;
$conv[78] = 87;
$conv[79] = 89;
$conv[80] = 90;
$conv[81] = 91;
$conv[82] = 98;
$conv[83] = 99;
$conv[86] = 100;
$conv[87] = 68;
$conv[88] = 69;
$conv[91] = 104;
$conv[92] = 105;
$conv[93] = 106;
$conv[99] = 107;
$conv[100] = 108;
$conv[101] = 109;
$conv[102] = 110;
$conv[103] = 111;
$conv[104] = 112;
$conv[105] = 113;
$conv[106] = 114;
$conv[107] = 115;
$conv[112] = 136;
$conv[115] = 135;
$conv[121] = 138;
$conv[123] = 139;
$conv[125] = 137;
$conv[127] = 72;
$conv[156] = 88;
$conv[157] = 228;
$conv[160] = 127;
$conv[170] = 70;
$conv[174] = 129;
$conv[176] = 128;
$conv[181] = 84;
$conv[184] = 230;
# 198 is #if 0 in the PS/2 map...
$conv[199] = 74;
$conv[200] = 82;
$conv[201] = 75;
$conv[203] = 80;
$conv[205] = 79;
$conv[207] = 77;
$conv[208] = 81;
$conv[209] = 78;
$conv[210] = 73;
$conv[211] = 76;
$conv[219] = 227;
$conv[220] = 231;
$conv[221] = 101;

my @ignores;
my @lines;
my $mapname;
my $nr = 0;

LINE: while (my $line = <>) {
	chomp $line;
	$nr++;

	if ($nr == 1) {
		my $version = $line;
		$version =~ s/\$//g;
		(my $id = $rcsid) =~ s/\$//g;

		print "/*\t\$OpenBSD\$\t*/\n\n";
		print "/*\n";
		print " * THIS FILE IS AUTOMAGICALLY GENERATED.  DO NOT EDIT.\n";
		print " *\n";
		print " * generated by:\n";
		printf(" *\t%s\n", $id);
		print " * generated from:\n";
		print " */\n";
		print "$version\n";

		next LINE;
	}

	#
	# A very limited #if ... #endif parser. We only want to correctly
	# detect ``#if 0'' constructs, so as not to process their contents.
	# This is necessary since our output is out-of-order from our input.
	#
	# Note that this does NOT handle ``#ifdef notyet'' correctly - please
	# only use ``#if 0'' constructs in the input.
	#

	if ($line =~ /^#if/) {
		my @f = split(' ', $line);
		$ignores[$ifdepth] = $ignore;
		if ($f[1] eq "0") {
			$ignore = 1;
		}
		#else
		#	$ignore = 0;
		$ifdepth++;
		if ($ignore) {
			next LINE;
		}
	}
	if ($line =~ /^#endif/) {
		my $oldignore = $ignore;
		$ifdepth--;
		$ignore = $ignores[$ifdepth];
		$ignores[$ifdepth] = 0;
		if ($oldignore) {
			next LINE;
		}
	}

	my @f = split(' ', $line);

	if ($f[0] eq "#include") {
		if ($ignore) {
			next LINE;
		}
		if ($f[1] eq "<dev/pckbc/wskbdmap_mfii.h>") {
			next LINE;
		}
		printf("#include %s\n", $f[1]);
		next LINE;
	}
	if ($f[0] eq "#define" || $f[0] eq "#undef") {
		if ($ignore) {
			next LINE;
		}
		print "$line\n";
		next LINE;
	}

	# Don't bother converting the DEC LK layout.
	if ($line =~ /declk\[/) {
		$declk = 1;
		next LINE;
	}
	if ($line =~ /declk/) {
		next LINE;
	}

	if ($line =~ /pckbd/) {
		$line =~ s/pckbd/ukbd/g;
		@f = split(' ', $line);
		$mapname = $f[3];
	}

	if ($line =~ /KC/) {
		if ($ignore) {
			next LINE;
		}

		if ($declk) {
			next LINE;
		}

		$haskeys = 1;

		my $sidx = substr($f[0], 3, length($f[0]) - 5);
		my $orig = int($sidx);
		my $id = $conv[$orig];

		# 183 is another Print Screen...
		if ($orig == 183) {
			next LINE;
		}

		if ($id == -1) {
			printf("/* initially KC(%d),", $orig);
			for (my $fi = 1; $fi <= $#f; $fi++) {
				if ($f[$fi] ne "/*" && $f[$fi] ne "*/") {
					printf("\t%s", $f[$fi]);
				}
			}
			printf("\t*/\n");
		} else {
			$lines[$id] = sprintf("    KC(%d),\t", $id);
			#
			# This makes sure that the non-comment part of the
			# output ends up with a trailing comma. This is
			# necessary since the last line of an input block
			# might not have a trailing comma, but might not be
			# the last line of an output block due to sorting.
			#
			my $comma = 0;
			for (my $fi = 1; $fi <= $#f; $fi++) {
				my $l = length($f[$fi]);
				if ($f[$fi] eq "/*") {
					$comma++;
				}
				if ($comma == 0 && substr($f[$fi], $l - 1) ne ",") {
					$lines[$id] = sprintf("%s%s,", $lines[$id], $f[$fi]);
					$l++;
				} else {
					$lines[$id] = sprintf("%s%s", $lines[$id], $f[$fi]);
				}
				if ($comma == 0 && $fi != $#f) {
					if ($l < 2 * 8) {
						$lines[$id] = $lines[$id] . "\t";
					}
					if ($l < 8) {
						$lines[$id] = $lines[$id] . "\t";
					}
				}
				if ($f[$fi] eq "*/") {
					$comma--;
				}
			}
		}

		next LINE;
	}
	if ($line =~ /};/) {
		if ($ignore) {
			next LINE;
		}

		if ($declk) {
			$declk = 0;
			next LINE;
		}

		if ($haskeys) {
			# Duplicate 42 (backspace) as 76 and 50 (backslash bar)
			# as 49
			if (!$lines[76]) {
				$lines[76] = $lines[42];
				$lines[76] =~ s/42/76/;
			}
			if (!$lines[49]) {
				$lines[49] = $lines[50];
				$lines[49] =~ s/50/49/;
			}

			#
			# Several USB keyboards have extra keys do not appear
			# in the traditional PS/2 maps. We add them here,
			# except for the Sun keyboard Compose key (101) which
			# conflicts with the ``menu'' key.
			#
			if ($nmaps++ == 0) {
				$lines[102] = "    KC(102),\tKS_Cmd_Sleep,";
				$lines[116] = "    KC(116),\tKS_Open,";
				$lines[117] = "    KC(117),\tKS_Help,";
				$lines[118] = "    KC(118),\tKS_Props,";
				$lines[119] = "    KC(119),\tKS_Front,";
				$lines[120] = "    KC(120),\tKS_Cmd,";
				$lines[121] = "    KC(121),\tKS_Again,";
				$lines[122] = "    KC(122),\tKS_Undo,";
				$lines[123] = "    KC(123),\tKS_Cut,";
				$lines[124] = "    KC(124),\tKS_Copy,";
				$lines[125] = "    KC(125),\tKS_Paste,";
				$lines[126] = "    KC(126),\tKS_Find,";
				$lines[232] = "    KC(232),\tKS_Cmd_BrightnessUp,";
				$lines[233] = "    KC(233),\tKS_Cmd_BrightnessDown,";
				$lines[234] = "    KC(234),\tKS_Cmd_KbdBacklightToggle,";
				$lines[235] = "    KC(235),\tKS_Cmd_KbdBacklightUp,";
				$lines[236] = "    KC(236),\tKS_Cmd_KbdBacklightDown,";
			}

			for (my $i = 0; $i < 256; $i++) {
				if ($lines[$i]) {
					print "$lines[$i]\n";
					$lines[$i] = "";
				}
			}

			$haskeys = 0;

			#
			# Apple black USB keyboards use a slightly different
			# layout. We define them here.
			#
			if ($mapname eq "ukbd_keydesc_de[]") {
				print "$line\n";
				print "\nstatic const keysym_t ukbd_keydesc_de_apple[] = {\n";
				print "/*  pos\t\tnormal\t\tshifted\t\taltgr\t\tshifted-altgr */\n";
				print "    KC(15),\tKS_l,\t\tKS_L,\t\tKS_at,\n";
				print "    KC(34),\tKS_5,\t\tKS_percent,\tKS_bracketleft,\n";
				print "    KC(35),\tKS_6,\t\tKS_ampersand,\tKS_bracketright,\n";
				print "    KC(36),\tKS_7,\t\tKS_slash,\tKS_bar,\t\tKS_backslash,\n";
				print "    KC(37),\tKS_8,\t\tKS_parenleft,\tKS_braceleft,\n";
				print "    KC(38),\tKS_9,\t\tKS_parenright,\tKS_braceright,\n";
				print "    KC(17),\tKS_n,\t\tKS_N,\t\tKS_asciitilde,\n";
			} elsif ($mapname eq "ukbd_keydesc_fr[]") {
				print "$line\n";
				print "\nstatic const keysym_t ukbd_keydesc_fr_apple[] = {\n";
				print "    KC(5),\tKS_b,\t\tKS_B,\t\tKS_ssharp,\n";
				print "    KC(8),\tKS_e,\t\tKS_E,\t\tKS_ecircumflex,\tKS_Ecircumflex,\n";
				print "    KC(11),\tKS_h,\t\tKS_H,\t\tKS_Igrave,\tKS_Icircumflex,\n";
				print "    KC(12),\tKS_i,\t\tKS_I,\t\tKS_icircumflex,\tKS_idiaeresis,\n";
				print "    KC(13),\tKS_j,\t\tKS_J,\t\tKS_Idiaeresis,\tKS_Iacute,\n";
				print "    KC(14),\tKS_k,\t\tKS_K,\t\tKS_Egrave,\tKS_Ediaeresis,\n";
				print "    KC(15),\tKS_l,\t\tKS_L,\t\tKS_voidSymbol,\tKS_bar,\n";
				print "    KC(16),\tKS_comma,\tKS_question,\tKS_voidSymbol,\tKS_questiondown,\n";
				print "    KC(17),\tKS_n,\t\tKS_N,\t\tKS_asciitilde,\n";
				print "    KC(20),\tKS_a,\t\tKS_A,\t\tKS_ae,\t\tKS_AE,\n";
				print "    KC(21),\tKS_r,\t\tKS_R,\t\tKS_registered,\tKS_comma,\n";
				print "    KC(22),\tKS_s,\t\tKS_S,\t\tKS_Ograve,\n";
				print "    KC(26),\tKS_z,\t\tKS_Z,\t\tKS_Acircumflex,\tKS_Aring,\n";
				print "    KC(28),\tKS_y,\t\tKS_Y,\t\tKS_Uacute,\n";
				print "    KC(31),\tKS_eacute,\tKS_2,\t\tKS_ediaeresis,\n";
				print "    KC(32),\tKS_quotedbl,\tKS_3,\n";
				print "    KC(33),\tKS_apostrophe,\tKS_4,\n";
				print "    KC(34),\tKS_parenleft,\tKS_5,\t\tKS_braceleft,\tKS_bracketleft,\n";
				print "    KC(35),\tKS_section,\tKS_6,\n";
				print "    KC(36),\tKS_egrave,\tKS_7,\t\tKS_guillemotleft,\n";
				print "\t\t\t\t\t\tKS_guillemotright,\n";
				print "    KC(37),\tKS_exclam,\tKS_8,\n";
				print "    KC(38),\tKS_ccedilla,\tKS_9,\t\tKS_Ccedilla,\tKS_Aacute,\n";
				print "    KC(37),\tKS_exclam,\tKS_8,\t\tKS_exclamdown,\tKS_Ucircumflex,\n";
				print "    KC(39),\tKS_agrave,\tKS_0,\t\tKS_oslash,\tKS_Ooblique,\n";
				print "    KC(45),\tKS_parenright,\tKS_degree,\tKS_braceright,\tKS_bracketright,\n";
				print "    KC(46),\tKS_minus,\tKS_underscore,\n";
				print "    KC(47),\tKS_dead_circumflex, KS_dead_diaeresis,\n";
				print "\t\t\t\t\t\tKS_ocircumflex,\tKS_Ocircumflex,\n";
				print "    KC(48),\tKS_dollar,\tKS_asterisk,\tKS_cent,\tKS_yen,\n";
				print "    KC(50),\tKS_grave,\tKS_sterling,\tKS_at,\t\tKS_numbersign,\n";
				print "    KC(51),\tKS_m,\t\tKS_M,\t\tKS_mu,\t\tKS_Oacute,\n";
				print "    KC(52),\tKS_ugrave,\tKS_percent,\tKS_Ugrave,\n";
				print "    KC(53),\tKS_at,\t\tKS_numbersign,\n";
				print "    KC(55),\tKS_colon,\tKS_slash,\tKS_voidSymbol,\tKS_backslash,\n";
				print "    KC(56),\tKS_equal,\tKS_plus,\n";
				print "    KC(103),\tKS_KP_Equal,\n";
				print "    KC(231),\tKS_Mode_switch,\tKS_Multi_key,\n";
			} elsif ($mapname eq "ukbd_keydesc_pt[]") {
				print "$line\n";
				print "\nstatic const keysym_t ukbd_keydesc_pt_apple[] = {\n";
				print "/*  pos\t\tnormal\t\tshifted */\n";
				print "    KC(46),\tKS_plus,\tKS_asterisk,\n";
				print "    KC(47),\tKS_masculine,\tKS_ordfeminine,\n";
				print "    KC(50),\tKS_backslash,\tKS_bar,\n";
				print "    KC(52),\tKS_dead_tilde,\tKS_dead_circumflex\n";
			}
		}
		# fall through to final default rule below
	}
	if ($line =~ /KB_DE/) {
		print "$line\n";
		$kbde++;
		# Add .apple variants
		if ($kbde == 1) {
			print "\tKBD_MAP(KB_DE | KB_APPLE,\tKB_DE,\tukbd_keydesc_de_apple),\n";
		} elsif ($kbde == 2) {
			print "\tKBD_MAP(KB_DE | KB_APPLE | KB_NODEAD,\tKB_DE | KB_APPLE,\n";
			print "\t\tukbd_keydesc_de_nodead),\n";
		}
		next LINE;
	}
	if ($line =~ /KB_FR/) {
		print "$line\n";
		$kbfr++;
		# Add .apple variants, but not to the fr.dvorak variants
		if ($kbfr == 1) {
			print "\tKBD_MAP(KB_FR | KB_APPLE,\tKB_FR,\tukbd_keydesc_fr_apple),\n";
		} elsif ($kbfr == 3) {
			print "\tKBD_MAP(KB_FR | KB_APPLE | KB_SWAPCTRLCAPS,\tKB_FR | KB_APPLE,\n";
			print "\t\tukbd_keydesc_swapctrlcaps),\n";
		}
		next LINE;
	}
	if ($line =~ /KB_PT/) {
		print "$line\n";
		print "\tKBD_MAP(KB_PT | KB_APPLE,\tKB_PT,\tukbd_keydesc_pt_apple),\n";
		next LINE;
	}

	if ($ignore) {
		next LINE;
	}
	if ($declk) {
		next LINE;
	}
	print "$line\n";
}
