/*
 * Copyright (C) 2019  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _vcn_2_0_0_OFFSET_HEADER
#define _vcn_2_0_0_OFFSET_HEADER

// addressBlock: uvd0_jpegnpdec
// base address: 0x1e200
#define mmUVD_JPEG_INT_STAT 0x008b
#define mmUVD_JPEG_INT_STAT_BASE_IDX 0
#define mmUVD_JPEG_PITCH 0x009f
#define mmUVD_JPEG_PITCH_BASE_IDX 0
#define mmUVD_JPEG_UV_PITCH 0x00a0
#define mmUVD_JPEG_UV_PITCH_BASE_IDX 0
#define mmJPEG_DEC_GFX8_ADDR_CONFIG 0x00a3
#define mmJPEG_DEC_GFX8_ADDR_CONFIG_BASE_IDX 0
#define mmJPEG_DEC_Y_GFX10_TILING_SURFACE 0x00a4
#define mmJPEG_DEC_Y_GFX10_TILING_SURFACE_BASE_IDX 0
#define mmJPEG_DEC_UV_GFX10_TILING_SURFACE 0x00a5
#define mmJPEG_DEC_UV_GFX10_TILING_SURFACE_BASE_IDX 0
#define mmJPEG_DEC_GFX10_ADDR_CONFIG 0x00a6
#define mmJPEG_DEC_GFX10_ADDR_CONFIG_BASE_IDX 0
#define mmJPEG_DEC_ADDR_MODE 0x00a7
#define mmJPEG_DEC_ADDR_MODE_BASE_IDX 0
#define mmUVD_JPEG_GPCOM_CMD 0x00a9
#define mmUVD_JPEG_GPCOM_CMD_BASE_IDX 0
#define mmUVD_JPEG_GPCOM_DATA0 0x00aa
#define mmUVD_JPEG_GPCOM_DATA0_BASE_IDX 0
#define mmUVD_JPEG_GPCOM_DATA1 0x00ab
#define mmUVD_JPEG_GPCOM_DATA1_BASE_IDX 0
// addressBlock: uvd0_uvd_jpeg_enc_sclk_dec
// base address: 0x1e380
#define mmJPEG_ENC_GFX10_ADDR_CONFIG 0x00ec
#define mmJPEG_ENC_GFX10_ADDR_CONFIG_BASE_IDX 0
// addressBlock: uvd0_uvd_jrbc_dec
// base address: 0x1e400
#define mmUVD_JRBC_RB_WPTR 0x0100
#define mmUVD_JRBC_RB_WPTR_BASE_IDX 0
#define mmUVD_JRBC_RB_CNTL 0x0101
#define mmUVD_JRBC_RB_CNTL_BASE_IDX 0
#define mmUVD_JRBC_IB_SIZE 0x0102
#define mmUVD_JRBC_IB_SIZE_BASE_IDX 0
#define mmUVD_JRBC_RB_REF_DATA 0x0104
#define mmUVD_JRBC_RB_REF_DATA_BASE_IDX 0
#define mmUVD_JRBC_RB_COND_RD_TIMER 0x0105
#define mmUVD_JRBC_RB_COND_RD_TIMER_BASE_IDX 0
#define mmUVD_JRBC_STATUS 0x0109
#define mmUVD_JRBC_STATUS_BASE_IDX 0
#define mmUVD_JRBC_RB_RPTR 0x010a
#define mmUVD_JRBC_RB_RPTR_BASE_IDX 0
#define mmUVD_JRBC_RB_SIZE 0x0113
#define mmUVD_JRBC_RB_SIZE_BASE_IDX 0
// addressBlock: uvd0_uvd_jmi_dec
// base address: 0x1e500
#define mmUVD_LMI_JRBC_IB_VMID 0x014f
#define mmUVD_LMI_JRBC_IB_VMID_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_VMID 0x0150
#define mmUVD_LMI_JRBC_RB_VMID_BASE_IDX 0
#define mmUVD_LMI_JPEG_VMID 0x0151
#define mmUVD_LMI_JPEG_VMID_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_64BIT_BAR_LOW 0x0166
#define mmUVD_LMI_JRBC_RB_64BIT_BAR_LOW_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_64BIT_BAR_HIGH 0x0167
#define mmUVD_LMI_JRBC_RB_64BIT_BAR_HIGH_BASE_IDX 0
#define mmUVD_LMI_JRBC_IB_64BIT_BAR_LOW 0x0168
#define mmUVD_LMI_JRBC_IB_64BIT_BAR_LOW_BASE_IDX 0
#define mmUVD_LMI_JRBC_IB_64BIT_BAR_HIGH 0x0169
#define mmUVD_LMI_JRBC_IB_64BIT_BAR_HIGH_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_MEM_WR_64BIT_BAR_LOW 0x016a
#define mmUVD_LMI_JRBC_RB_MEM_WR_64BIT_BAR_LOW_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_MEM_WR_64BIT_BAR_HIGH 0x016b
#define mmUVD_LMI_JRBC_RB_MEM_WR_64BIT_BAR_HIGH_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_MEM_RD_64BIT_BAR_LOW 0x016c
#define mmUVD_LMI_JRBC_RB_MEM_RD_64BIT_BAR_LOW_BASE_IDX 0
#define mmUVD_LMI_JRBC_RB_MEM_RD_64BIT_BAR_HIGH 0x016d
#define mmUVD_LMI_JRBC_RB_MEM_RD_64BIT_BAR_HIGH_BASE_IDX 0
#define mmUVD_JMI_CNTL 0x0192
#define mmUVD_JMI_CNTL_BASE_IDX 0
// addressBlock: uvd0_uvd_jpeg_common_dec
// base address: 0x1e700
#define mmJPEG_SYS_INT_EN 0x01c1
#define mmJPEG_SYS_INT_EN_BASE_IDX 0
// addressBlock: uvd0_uvd_jpeg_common_sclk_dec
// base address: 0x1e780
#define mmJPEG_CGC_GATE 0x01e0
#define mmJPEG_CGC_GATE_BASE_IDX 0
#define mmJPEG_CGC_CTRL 0x01e1
#define mmJPEG_CGC_CTRL_BASE_IDX 0
// addressBlock: uvd0_uvd_pg_dec
// base address: 0x1f800
#define mmUVD_PGFSM_CONFIG 0x0000
#define mmUVD_PGFSM_CONFIG_BASE_IDX 1
#define mmUVD_PGFSM_STATUS 0x0001
#define mmUVD_PGFSM_STATUS_BASE_IDX 1
#define mmUVD_POWER_STATUS 0x0004
#define mmUVD_POWER_STATUS_BASE_IDX 1
#define mmCC_UVD_HARVESTING 0x0007
#define mmCC_UVD_HARVESTING_BASE_IDX 1
#define mmUVD_JPEG_POWER_STATUS 0x000a
#define mmUVD_JPEG_POWER_STATUS_BASE_IDX 1
#define mmUVD_DPG_LMA_CTL 0x0011
#define mmUVD_DPG_LMA_CTL_BASE_IDX 1
#define mmUVD_DPG_LMA_DATA 0x0012
#define mmUVD_DPG_LMA_DATA_BASE_IDX 1
#define mmUVD_DPG_LMA_MASK 0x0013
#define mmUVD_DPG_LMA_MASK_BASE_IDX 1
#define mmUVD_DPG_PAUSE 0x0014
#define mmUVD_DPG_PAUSE_BASE_IDX 1
#define mmUVD_SCRATCH2 0x0016
#define mmUVD_SCRATCH2_BASE_IDX 1
#define mmUVD_SCRATCH9 0x001d
#define mmUVD_SCRATCH9_BASE_IDX 1
#define mmUVD_GFX8_ADDR_CONFIG 0x0049
#define mmUVD_GFX8_ADDR_CONFIG_BASE_IDX 1
#define mmUVD_GFX10_ADDR_CONFIG 0x004a
#define mmUVD_GFX10_ADDR_CONFIG_BASE_IDX 1
// addressBlock: uvd0_uvddec
// base address: 0x1ff00
#define mmUVD_SEMA_CNTL 0x01c0
#define mmUVD_SEMA_CNTL_BASE_IDX 1
#define mmUVD_RB_RPTR3 0x01db
#define mmUVD_RB_RPTR3_BASE_IDX 1
#define mmUVD_RB_WPTR3 0x01dc
#define mmUVD_RB_WPTR3_BASE_IDX 1
#define mmUVD_RB_BASE_LO3 0x01dd
#define mmUVD_RB_BASE_LO3_BASE_IDX 1
#define mmUVD_RB_BASE_HI3 0x01de
#define mmUVD_RB_BASE_HI3_BASE_IDX 1
#define mmUVD_RB_SIZE3 0x01df
#define mmUVD_RB_SIZE3_BASE_IDX 1
#define mmUVD_RB_ARB_CTRL 0x01e0
#define mmUVD_RB_ARB_CTRL_BASE_IDX 1
#define mmUVD_CTX_INDEX 0x01e8
#define mmUVD_CTX_INDEX_BASE_IDX 1
#define mmUVD_CTX_DATA 0x01e9
#define mmUVD_CTX_DATA_BASE_IDX 1
#define mmUVD_CGC_GATE 0x01ea
#define mmUVD_CGC_GATE_BASE_IDX 1
#define mmUVD_CGC_CTRL 0x01ec
#define mmUVD_CGC_CTRL_BASE_IDX 1
#define mmUVD_GP_SCRATCH4 0x01f8
#define mmUVD_GP_SCRATCH4_BASE_IDX 1
#define mmUVD_LMI_CTRL2 0x01fd
#define mmUVD_LMI_CTRL2_BASE_IDX 1
#define mmUVD_MASTINT_EN 0x0200
#define mmUVD_MASTINT_EN_BASE_IDX 1
#define mmUVD_SYS_INT_EN 0x0201
#define mmUVD_SYS_INT_EN_BASE_IDX 1
#define mmUVD_VCPU_INT_EN 0x0204
#define mmUVD_VCPU_INT_EN_BASE_IDX 1
#define mmUVD_LMI_CTRL 0x0226
#define mmUVD_LMI_CTRL_BASE_IDX 1
#define mmUVD_LMI_STATUS 0x0227
#define mmUVD_LMI_STATUS_BASE_IDX 1
#define mmUVD_LMI_SWAP_CNTL 0x022d
#define mmUVD_LMI_SWAP_CNTL_BASE_IDX 1
#define mmUVD_MP_SWAP_CNTL 0x022f
#define mmUVD_MP_SWAP_CNTL_BASE_IDX 1
#define mmUVD_MPC_CNTL 0x0237
#define mmUVD_MPC_CNTL_BASE_IDX 1
#define mmUVD_MPC_SET_MUXA0 0x0239
#define mmUVD_MPC_SET_MUXA0_BASE_IDX 1
#define mmUVD_MPC_SET_MUXA1 0x023a
#define mmUVD_MPC_SET_MUXA1_BASE_IDX 1
#define mmUVD_MPC_SET_MUXB0 0x023b
#define mmUVD_MPC_SET_MUXB0_BASE_IDX 1
#define mmUVD_MPC_SET_MUXB1 0x023c
#define mmUVD_MPC_SET_MUXB1_BASE_IDX 1
#define mmUVD_MPC_SET_MUX 0x023d
#define mmUVD_MPC_SET_MUX_BASE_IDX 1
#define mmUVD_MPC_SET_ALU 0x023e
#define mmUVD_MPC_SET_ALU_BASE_IDX 1
#define mmUVD_VCPU_CACHE_OFFSET0 0x0242
#define mmUVD_VCPU_CACHE_OFFSET0_BASE_IDX 1
#define mmUVD_VCPU_CACHE_SIZE0 0x0243
#define mmUVD_VCPU_CACHE_SIZE0_BASE_IDX 1
#define mmUVD_VCPU_CACHE_OFFSET1 0x0244
#define mmUVD_VCPU_CACHE_OFFSET1_BASE_IDX 1
#define mmUVD_VCPU_CACHE_SIZE1 0x0245
#define mmUVD_VCPU_CACHE_SIZE1_BASE_IDX 1
#define mmUVD_VCPU_CACHE_OFFSET2 0x0246
#define mmUVD_VCPU_CACHE_OFFSET2_BASE_IDX 1
#define mmUVD_VCPU_CACHE_SIZE2 0x0247
#define mmUVD_VCPU_CACHE_SIZE2_BASE_IDX 1
#define mmUVD_VCPU_NONCACHE_OFFSET0 0x0254
#define mmUVD_VCPU_NONCACHE_OFFSET0_BASE_IDX 1
#define mmUVD_VCPU_NONCACHE_SIZE0 0x0255
#define mmUVD_VCPU_NONCACHE_SIZE0_BASE_IDX 1
#define mmUVD_VCPU_CNTL 0x0258
#define mmUVD_VCPU_CNTL_BASE_IDX 1
#define mmUVD_SOFT_RESET 0x0260
#define mmUVD_SOFT_RESET_BASE_IDX 1
#define mmUVD_LMI_RBC_IB_VMID 0x0261
#define mmUVD_LMI_RBC_IB_VMID_BASE_IDX 1
#define mmUVD_RBC_IB_SIZE 0x0262
#define mmUVD_RBC_IB_SIZE_BASE_IDX 1
#define mmUVD_LMI_RBC_RB_VMID 0x0263
#define mmUVD_LMI_RBC_RB_VMID_BASE_IDX 1
#define mmUVD_RBC_RB_RPTR 0x0264
#define mmUVD_RBC_RB_RPTR_BASE_IDX 1
#define mmUVD_RBC_RB_WPTR 0x0265
#define mmUVD_RBC_RB_WPTR_BASE_IDX 1
#define mmUVD_RBC_RB_WPTR_CNTL 0x0266
#define mmUVD_RBC_RB_WPTR_CNTL_BASE_IDX 1
#define mmUVD_RBC_RB_CNTL 0x0269
#define mmUVD_RBC_RB_CNTL_BASE_IDX 1
#define mmUVD_RBC_RB_RPTR_ADDR 0x026a
#define mmUVD_RBC_RB_RPTR_ADDR_BASE_IDX 1
#define mmUVD_STATUS 0x026f
#define mmUVD_STATUS_BASE_IDX 1
#define mmUVD_SEMA_TIMEOUT_STATUS 0x0270
#define mmUVD_SEMA_TIMEOUT_STATUS_BASE_IDX 1
#define mmUVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL 0x0271
#define mmUVD_SEMA_WAIT_INCOMPLETE_TIMEOUT_CNTL_BASE_IDX 1
#define mmUVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL 0x0272
#define mmUVD_SEMA_WAIT_FAULT_TIMEOUT_CNTL_BASE_IDX 1
#define mmUVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL 0x0273
#define mmUVD_SEMA_SIGNAL_INCOMPLETE_TIMEOUT_CNTL_BASE_IDX 1
#define mmUVD_CONTEXT_ID 0x027d
#define mmUVD_CONTEXT_ID_BASE_IDX 1
#define mmUVD_CONTEXT_ID2 0x027f
#define mmUVD_CONTEXT_ID2_BASE_IDX 1
#define mmUVD_RB_BASE_LO4 0x029f
#define mmUVD_RB_BASE_LO4_BASE_IDX 1
#define mmUVD_RB_BASE_HI4 0x02a0
#define mmUVD_RB_BASE_HI4_BASE_IDX 1
#define mmUVD_RB_SIZE4 0x02a1
#define mmUVD_RB_SIZE4_BASE_IDX 1
#define mmUVD_RB_RPTR4 0x02a2
#define mmUVD_RB_RPTR4_BASE_IDX 1
// addressBlock: uvd0_uvdnpdec
// base address: 0x20700
#define mmUVD_GPCOM_VCPU_CMD 0x0583
#define mmUVD_GPCOM_VCPU_CMD_BASE_IDX 1
#define mmUVD_GPCOM_VCPU_DATA0 0x0584
#define mmUVD_GPCOM_VCPU_DATA0_BASE_IDX 1
#define mmUVD_GPCOM_VCPU_DATA1 0x0585
#define mmUVD_GPCOM_VCPU_DATA1_BASE_IDX 1
#define mmUVD_ENGINE_CNTL 0x0586
#define mmUVD_ENGINE_CNTL_BASE_IDX 1
#define mmUVD_SUVD_CGC_GATE 0x05a4
#define mmUVD_SUVD_CGC_GATE_BASE_IDX 1
#define mmUVD_SUVD_CGC_CTRL 0x05a6
#define mmUVD_SUVD_CGC_CTRL_BASE_IDX 1
#define mmUVD_LMI_VCPU_CACHE1_64BIT_BAR_LOW 0x05ac
#define mmUVD_LMI_VCPU_CACHE1_64BIT_BAR_LOW_BASE_IDX 1
#define mmUVD_LMI_VCPU_CACHE1_64BIT_BAR_HIGH 0x05ad
#define mmUVD_LMI_VCPU_CACHE1_64BIT_BAR_HIGH_BASE_IDX 1
#define mmUVD_LMI_VCPU_CACHE2_64BIT_BAR_LOW 0x05b0
#define mmUVD_LMI_VCPU_CACHE2_64BIT_BAR_LOW_BASE_IDX 1
#define mmUVD_LMI_VCPU_CACHE2_64BIT_BAR_HIGH 0x05b1
#define mmUVD_LMI_VCPU_CACHE2_64BIT_BAR_HIGH_BASE_IDX 1
#define mmUVD_NO_OP 0x05bf
#define mmUVD_NO_OP_BASE_IDX 1
#define mmUVD_GP_SCRATCH8 0x05ca
#define mmUVD_GP_SCRATCH8_BASE_IDX 1
#define mmUVD_GP_SCRATCH9 0x05cb
#define mmUVD_GP_SCRATCH9_BASE_IDX 1
#define mmUVD_RB_BASE_LO2 0x05e1
#define mmUVD_RB_BASE_LO2_BASE_IDX 1
#define mmUVD_RB_BASE_HI2 0x05e2
#define mmUVD_RB_BASE_HI2_BASE_IDX 1
#define mmUVD_RB_SIZE2 0x05e3
#define mmUVD_RB_SIZE2_BASE_IDX 1
#define mmUVD_RB_RPTR2 0x05e4
#define mmUVD_RB_RPTR2_BASE_IDX 1
#define mmUVD_RB_WPTR2 0x05e5
#define mmUVD_RB_WPTR2_BASE_IDX 1
#define mmUVD_RB_BASE_LO 0x05e6
#define mmUVD_RB_BASE_LO_BASE_IDX 1
#define mmUVD_RB_BASE_HI 0x05e7
#define mmUVD_RB_BASE_HI_BASE_IDX 1
#define mmUVD_RB_SIZE 0x05e8
#define mmUVD_RB_SIZE_BASE_IDX 1
#define mmUVD_RB_RPTR 0x05e9
#define mmUVD_RB_RPTR_BASE_IDX 1
#define mmUVD_RB_WPTR 0x05ea
#define mmUVD_RB_WPTR_BASE_IDX 1
#define mmUVD_RB_WPTR4 0x0616
#define mmUVD_RB_WPTR4_BASE_IDX 1
#define mmUVD_LMI_VCPU_CACHE_64BIT_BAR_HIGH 0x061e
#define mmUVD_LMI_VCPU_CACHE_64BIT_BAR_HIGH_BASE_IDX 1
#define mmUVD_LMI_VCPU_CACHE_64BIT_BAR_LOW 0x061f
#define mmUVD_LMI_VCPU_CACHE_64BIT_BAR_LOW_BASE_IDX 1
#define mmUVD_LMI_VCPU_NC0_64BIT_BAR_HIGH 0x0622
#define mmUVD_LMI_VCPU_NC0_64BIT_BAR_HIGH_BASE_IDX 1
#define mmUVD_LMI_VCPU_NC0_64BIT_BAR_LOW 0x0623
#define mmUVD_LMI_VCPU_NC0_64BIT_BAR_LOW_BASE_IDX 1
#define mmUVD_LMI_RBC_IB_64BIT_BAR_HIGH 0x0626
#define mmUVD_LMI_RBC_IB_64BIT_BAR_HIGH_BASE_IDX 1
#define mmUVD_LMI_RBC_IB_64BIT_BAR_LOW 0x0627
#define mmUVD_LMI_RBC_IB_64BIT_BAR_LOW_BASE_IDX 1
#define mmUVD_LMI_RBC_RB_64BIT_BAR_HIGH 0x0628
#define mmUVD_LMI_RBC_RB_64BIT_BAR_HIGH_BASE_IDX 1
#define mmUVD_LMI_RBC_RB_64BIT_BAR_LOW 0x0629
#define mmUVD_LMI_RBC_RB_64BIT_BAR_LOW_BASE_IDX 1
#endif
