#!/usr/bin/perl
# EteleOS: libraries/extra/libcurses/tinfo/MKcaptab.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
# Perl translation of MKcaptab.awk (provenance preserved below).
#
# $OpenBSD: MKcaptab.awk,v 1.5 2023/10/17 09:52:09 nicm Exp $
##############################################################################
# Copyright 2020 Thomas E. Dickey                                            #
# Copyright 1998-2006,2007 Free Software Foundation, Inc.                    #
#                                                                            #
# Permission is hereby granted, free of charge, to any person obtaining a    #
# copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation  #
# the rights to use, copy, modify, merge, publish, distribute, distribute    #
# with modifications, sublicense, and/or sell copies of the Software, and to #
# permit persons to whom the Software is furnished to do so, subject to the  #
# following conditions:                                                      #
#                                                                            #
# The above copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                        #
#                                                                            #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    #
# THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER        #
# DEALINGS IN THE SOFTWARE.                                                  #
#                                                                            #
# Except as contained in this notice, the name(s) of the above copyright     #
# holders shall not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written               #
# authorization.                                                             #
##############################################################################
# $Id: MKcaptab.awk,v 1.5 2023/10/17 09:52:09 nicm Exp $
use strict;
use warnings;

# Parse "var=value" style arguments (awk-style), leaving any remaining
# arguments as filenames in @ARGV for the diamond operator.
my %vars;
while (@ARGV && $ARGV[0] =~ /^(\w+)=(.*)$/) {
    $vars{$1} = $2;
    shift @ARGV;
}
my $tablename  = defined $vars{tablename}  ? $vars{tablename}  : '';
my $bigstrings = defined $vars{bigstrings} ? $vars{bigstrings} : 0;

my $first = 1;
my $num_aliases = 0;
my $num_strings = 0;
my $offset = 0;
my @offsets;
my @aliases;

sub add_string {
    my ($text) = @_;
    my $result;
    if ($text ne "IGNORE") {
        $offsets[$num_strings] = $offset;
        $offset = $offset + length($text) + 1;
        printf "%s\\0", $text;
    } else {
        $offsets[$num_strings] = -1;
    }
    $num_strings = $num_strings + 1;
    if (($num_strings % 3) == 0) {
        printf "\\\n";
    }
    return $offsets[$num_strings - 1];
}

while (my $line = <>) {
    chomp $line;
    next unless $line =~ /^[^#]/;

    if ($first) {
        printf "/* generated by MKcaptab.awk %s(%d) */\n", $tablename, $bigstrings;
        print "\n";
        if ($bigstrings) {
            printf "static struct alias *_nc_%s_table = 0;\n", $tablename;
            print "\n";
            printf "static const char %s_text[] = \"\\\n", $tablename;
        } else {
            printf "static const struct alias _nc_%s_table[] =\n", $tablename;
            printf "{\n";
        }
        $first = 0;
    }

    my @f = split(' ', $line);
    my $f1 = defined $f[0] ? $f[0] : '';
    my $f2 = defined $f[1] ? $f[1] : '';
    my $f3 = defined $f[2] ? $f[2] : '';
    my $f4 = defined $f[3] ? $f[3] : '';
    my $f5 = defined $f[4] ? $f[4] : '';

    if ($f1 eq $tablename) {
        my $to;
        if ($f3 eq "IGNORE") {
            $to = "(char *)NULL";
        } else {
            $to = "\"" . $f3 . "\"";
        }
        if ($bigstrings) {
            my $c1 = add_string($f2);
            my $c2 = add_string($f3);
            my $c3 = add_string($f4);
            $aliases[$num_aliases] = sprintf("\t{%5d, %5d, %5d},\t /* %s */", $c1, $c2, $c3, $f5);
            $num_aliases = $num_aliases + 1;
        } else {
            printf "\t{\"%s\", %s, \"%s\"},\t /* %s */\n", $f2, $to, $f4, $f5;
        }
    }
}

if ($bigstrings) {
    printf "\";\n\n";
    printf "static const alias_table_data %s_data[] = {\n", $tablename;
    for (my $n = 0; $n < $num_aliases; ++$n) {
        printf "%s\n", $aliases[$n];
    }
    printf "};\n\n";
} else {
    printf "\t{(char *)NULL, (char *)NULL, (char *)NULL}\n";
    printf "};\n\n";
}
# vile:sw=4:
