-- EteleOS: libraries/extra/libcurses/tinfo/MKcaptab.lua, time wirte: 2026/08/08
-- This file uses the Apache-2.0 license
-- Original AWK file license: $OpenBSD: MKcaptab.awk,v 1.5 2023/10/17 09:52:09 nicm Exp $
-- Copyright 2020 Thomas E. Dickey; Copyright 1998-2006,2007 Free Software Foundation, Inc.
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software
-- and associated documentation files, to deal in the Software without restriction.
-- Native Lua port of MKcaptab.awk; it does not invoke awk.
local argv={...};if #argv==0 then argv=arg or{}end
local tablename=argv[1] or "";local bigstrings=tonumber(argv[2]) or 0
local offsets,strings,aliases,offset={}, {}, {}, 0
local function add(text)
  local pos;if text=="IGNORE" then pos=-1 else pos=offset;strings[#strings+1]=text.."\\0";offset=offset+#text+1 end
  offsets[#offsets+1]=pos;return pos
end
local function emit(line)
  if line:match("^[^#]") then
    local f={};for v in line:gmatch("%S+")do f[#f+1]=v end
    if f[1]==tablename then
      if bigstrings~=0 then aliases[#aliases+1]=string.format("\t{%5d, %5d, %5d},\t /* %s */",add(f[2]),add(f[3]),add(f[4]),f[5] or "")
      else print(string.format("\t{\"%s\", %s, \"%s\"},\t /* %s */",f[2],f[3]=="IGNORE" and "(char *)NULL" or '"'..f[3]..'"',f[4],f[5] or "")) end
    end
  end
end
print(string.format("/* generated by MKcaptab.lua %s(%d) */\n",tablename,bigstrings))
if bigstrings~=0 then print(string.format("static struct alias *_nc_%s_table = 0;\n\nstatic const char %s_text[] = \\",tablename,tablename)) else print(string.format("static const struct alias _nc_%s_table[] =\n{",tablename)) end
if #argv>2 then for i=3,#argv do local f=assert(io.open(argv[i]));for l in f:lines()do emit(l)end;f:close()end else for l in io.stdin:lines()do emit(l)end end
if bigstrings~=0 then print(table.concat(strings,""));print('";\n\nstatic const alias_table_data '..tablename..'_data[] = {');for _,v in ipairs(aliases)do print(v)end;print("};\n") else print("\t{(char *)NULL, (char *)NULL, (char *)NULL}\n};\n")end
