-- EteleOS: libraries/extra/libcurses/tinfo/MKcodes.lua, time wirte: 2026/08/08
-- This file uses the Apache-2.0 license
-- Original AWK file license: $OpenBSD: MKcodes.awk,v 1.2 2023/10/17 09:52:09 nicm Exp $
-- Copyright 2019,2020 Thomas E. Dickey; Copyright 2007-2009,2010 Free Software Foundation, Inc.
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software
-- and associated documentation files, to deal in the Software without restriction.
-- Native Lua port of MKcodes.awk; it does not invoke awk.
local argv={...};if #argv==0 then argv=arg or{}end
local big=tonumber(argv[1]) or 0;local files={};for i=2,#argv do files[#files+1]=argv[i]end
local offset,offcol,bigcol,bigstr=0,0,0,"";local small={bool="",num="",str=""};local large={bool="",num="",str=""}
local function large_item(v)local r=tostring(offset)..",";offset=offset+#v+1;offcol=offcol+#r+2;if offcol>70 then r=r.."\n";offcol=0 else r=r.." "end;bigstr=bigstr..'"'..v..'\\0" ';bigcol=bigcol+#v+5;if bigcol>70 then bigstr=bigstr.."\\\n";bigcol=0 end;return r end
local function add(line)local f={};for v in line:gmatch("%S+")do f[#f+1]=v end;if f[1] and not f[1]:match("^#") and not f[1]:match("^(cap|info)alias") and f[1]~="userdef" and f[1]~="SKIPWARN" and (f[3]=="bool"or f[3]=="num"or f[3]=="str")then small[f[3]]=small[f[3]]..'\t\t"'..f[4]..'",\n';large[f[3]]=large[f[3]]..large_item(f[4])end end
if #files==0 then for l in io.stdin:lines()do add(l)end else for _,n in ipairs(files)do local f=assert(io.open(n));for l in f:lines()do add(l)end;f:close()end end
local function strings(n,v)print("DCL("..n..") = {\n"..v.."\t\t(NCURSES_CONST char *)0,\n};\n")end
local function offsets(n,v)print("static const short _nc_offset_"..n.."[] = {\n"..v.."};\n\nstatic NCURSES_CONST char ** ptr_"..n.." = 0;\n")end
print("/* This file was generated by MKcodes.lua */\n\n#include <curses.priv.h>\n\n#define IT NCURSES_CONST char * const\n\n#if BROKEN_LINKER || USE_REENTRANT\n")
if big~=0 then print("static const char _nc_code_blob[] = \n"..bigstr..";\n");offsets("boolcodes",large.bool);offsets("numcodes",large.num);offsets("strcodes",large.str);print([[static IT *
alloc_array(NCURSES_CONST char ***value, const short *offsets, unsigned size)
{
	if (*value == 0) {
		if ((*value = typeCalloc(NCURSES_CONST char *, size + 1)) != 0) {
			unsigned n;
			for (n = 0; n < size; ++n) (*value)[n] = (NCURSES_CONST char *) _nc_code_blob + offsets[n];
		}
	}
	return *value;
}

#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return alloc_array(&ptr_##it, _nc_offset_##it, SIZEOF(_nc_offset_##it)); }]]) else print("#define DCL(it) static IT data##it[]\n");strings("boolcodes",small.bool);strings("numcodes",small.num);strings("strcodes",small.str);print("#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return data##it; }")end
print([[/* remove public definition which conflicts with FIX() */
#undef boolcodes
#undef numcodes
#undef strcodes
FIX(boolcodes)
FIX(numcodes)
FIX(strcodes)
#define FREE_FIX(it) if (ptr_##it) { FreeAndNull(ptr_##it); }
#define boolcodes NCURSES_PUBLIC_VAR(boolcodes())
#define numcodes NCURSES_PUBLIC_VAR(numcodes())
#define strcodes NCURSES_PUBLIC_VAR(strcodes())
#if NO_LEAKS
NCURSES_EXPORT(void) _nc_codes_leaks(void) {]])
if big~=0 then print("FREE_FIX(boolcodes)\nFREE_FIX(numcodes)\nFREE_FIX(strcodes)")end
print([[}
#endif
#else
#define DCL(it) NCURSES_EXPORT_VAR(IT) it[]]])
strings("boolcodes",small.bool);strings("numcodes",small.num);strings("strcodes",small.str);print("#endif /* BROKEN_LINKER */")
