#!/usr/bin/perl
# PeteleOS: libraries/extra/libcurses/tinfo/MKcodes.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
# Perl translation of MKcodes.awk (provenance preserved below).
#
# $OpenBSD: MKcodes.awk,v 1.2 2023/10/17 09:52:09 nicm Exp $
##############################################################################
# Copyright 2019,2020 Thomas E. Dickey                                       #
# Copyright 2007-2009,2010 Free Software Foundation, Inc.                    #
#                                                                            #
# Permission is hereby granted, free of charge, to any person obtaining a    #
# copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation  #
# the rights to use, copy, modify, merge, publish, distribute, distribute    #
# with modifications, sublicense, and/or sell copies of the Software, and to #
# permit persons to whom the Software is furnished to do so, subject to the  #
# following conditions:                                                      #
#                                                                            #
# The above copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                        #
#                                                                            #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    #
# THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER        #
# DEALINGS IN THE SOFTWARE.                                                  #
#                                                                            #
# Except as contained in this notice, the name(s) of the above copyright     #
# holders shall not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written               #
# authorization.                                                             #
##############################################################################
# $Id: MKcodes.awk,v 1.2 2023/10/17 09:52:09 nicm Exp $
use strict;
use warnings;

my %vars;
while (@ARGV && $ARGV[0] =~ /^(\w+)=(.*)$/) {
    $vars{$1} = $2;
    shift @ARGV;
}
my $bigstrings = defined $vars{bigstrings} ? $vars{bigstrings} : 0;

my $offset = 0;
my $offcol = 0;
my $bigcol = 0;
my $bigstr = '';

my $small_boolcodes = '';
my $large_boolcodes = '';
my $small_numcodes = '';
my $large_numcodes = '';
my $small_strcodes = '';
my $large_strcodes = '';

sub large_item {
    my ($value) = @_;
    my $result = sprintf("%d,", $offset);
    $offset = $offset + length($value) + 1;
    $offcol = $offcol + length($result) + 2;
    if ($offcol > 70) {
        $result = $result . "\n";
        $offcol = 0;
    } else {
        $result = $result . " ";
    }
    $bigstr = $bigstr . sprintf("\"%s\\0\" ", $value);
    $bigcol = $bigcol + length($value) + 5;
    if ($bigcol > 70) {
        $bigstr = $bigstr . "\\\n";
        $bigcol = 0;
    }
    return $result;
}

sub small_item {
    my ($value) = @_;
    return sprintf("\t\t\"%s\",\n", $value);
}

sub print_strings {
    my ($name, $value) = @_;
    printf "DCL(%s) = {\n", $name;
    print "$value\n";
    print "\t\t(NCURSES_CONST char *)0,\n";
    print "};\n";
    print "\n";
}

sub print_offsets {
    my ($name, $value) = @_;
    printf "static const short _nc_offset_%s[] = {\n", $name;
    printf "%s", $value;
    print "};\n";
    print "\n";
    printf "static NCURSES_CONST char ** ptr_%s = 0;\n", $name;
    print "\n";
}

print "/* This file was generated by MKcodes.awk */\n";
print "\n";
print "#include <curses.priv.h>\n";
print "\n";
print "#define IT NCURSES_CONST char * const\n";
print "\n";

while (my $line = <>) {
    chomp $line;
    my @f = split(' ', $line);
    my $f1 = defined $f[0] ? $f[0] : '';
    my $f3 = defined $f[2] ? $f[2] : '';
    my $f4 = defined $f[3] ? $f[3] : '';

    next if $f1 =~ /^#/;
    next if $f1 =~ /^(cap|info)alias/;
    next if $f1 eq "userdef";
    next if $f1 eq "SKIPWARN";

    if ($f3 eq "bool") {
        $small_boolcodes = $small_boolcodes . small_item($f4);
        $large_boolcodes = $large_boolcodes . large_item($f4);
    }
    if ($f3 eq "num") {
        $small_numcodes = $small_numcodes . small_item($f4);
        $large_numcodes = $large_numcodes . large_item($f4);
    }
    if ($f3 eq "str") {
        $small_strcodes = $small_strcodes . small_item($f4);
        $large_strcodes = $large_strcodes . large_item($f4);
    }
}

print "\n";
print "#if BROKEN_LINKER || USE_REENTRANT\n";
print "\n";
if ($bigstrings) {
    printf "static const char _nc_code_blob[] = \n";
    printf "%s;\n", $bigstr;
    print_offsets("boolcodes", $large_boolcodes);
    print_offsets("numcodes", $large_numcodes);
    print_offsets("strcodes", $large_strcodes);
    print "\n";
    print "static IT *\n";
    print "alloc_array(NCURSES_CONST char ***value, const short *offsets, unsigned size)\n";
    print "{\n";
    print "\tif (*value == 0) {\n";
    print "\t\tif ((*value = typeCalloc(NCURSES_CONST char *, size + 1)) != 0) {\n";
    print "\t\t\tunsigned n;\n";
    print "\t\t\tfor (n = 0; n < size; ++n) {\n";
    print "\t\t\t\t(*value)[n] = (NCURSES_CONST char *) _nc_code_blob + offsets[n];\n";
    print "\t\t\t}\n";
    print "\t\t}\n";
    print "\t}\n";
    print "\treturn *value;\n";
    print "}\n";
    print "\n";
    print "#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return alloc_array(&ptr_##it, _nc_offset_##it, SIZEOF(_nc_offset_##it)); }\n";
} else {
    print "#define DCL(it) static IT data##it[]\n";
    print "\n";
    print_strings("boolcodes", $small_boolcodes);
    print_strings("numcodes", $small_numcodes);
    print_strings("strcodes", $small_strcodes);
    print "#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return data##it; }\n";
}
print "\n";
print "/* remove public definition which conflicts with FIX() */\n";
print "#undef boolcodes\n";
print "#undef numcodes\n";
print "#undef strcodes\n";
print "\n";
print "/* add local definition */\n";
print "FIX(boolcodes)\n";
print "FIX(numcodes)\n";
print "FIX(strcodes)\n";
print "\n";
print "/* restore the public definition */\n";
print "\n";
print "#define FREE_FIX(it) if (ptr_##it) { FreeAndNull(ptr_##it); }\n";
print "#define boolcodes  NCURSES_PUBLIC_VAR(boolcodes())\n";
print "#define numcodes   NCURSES_PUBLIC_VAR(numcodes())\n";
print "#define strcodes   NCURSES_PUBLIC_VAR(strcodes())\n";
print "\n";
print "#if NO_LEAKS\n";
print "NCURSES_EXPORT(void)\n";
print "_nc_codes_leaks(void)\n";
print "{\n";
if ($bigstrings) {
    print "FREE_FIX(boolcodes)\n";
    print "FREE_FIX(numcodes)\n";
    print "FREE_FIX(strcodes)\n";
}
print "}\n";
print "#endif\n";
print "\n";
print "#else\n";
print "\n";
print "#define DCL(it) NCURSES_EXPORT_VAR(IT) it[]\n";
print "\n";
print_strings("boolcodes", $small_boolcodes);
print_strings("numcodes", $small_numcodes);
print_strings("strcodes", $small_strcodes);
print "\n";
print "#endif /* BROKEN_LINKER */\n";
