-- EteleOS: libraries/extra/libcurses/tinfo/MKnames.lua, time wirte: 2026/08/08
-- This file uses the Apache-2.0 license
-- Original AWK file license: $OpenBSD: MKnames.awk,v 1.4 2023/10/17 09:52:09 nicm Exp $
-- Copyright 2019,2020 Thomas E. Dickey; Copyright 1998-2008,2009 Free Software Foundation, Inc.
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software
-- and associated documentation files, to deal in the Software without restriction.
-- Native Lua port of MKnames.awk; it does not invoke awk.
local a={...};if #a==0 then a=arg or{}end;local big=tonumber(a[1])or 0;local offset,blob=0,"";local small,large={},{}
for _,n in ipairs({"boolnames","boolfnames","numnames","numfnames","strnames","strfnames"})do small[n]="";large[n]=""end
local function item(n,v)local r=tostring(offset)..", ";offset=offset+#v+1;blob=blob..'"'..v..'\\0" ';return r end
local function add(l)local f={};for x in l:gmatch("%S+")do f[#f+1]=x end;if f[1]and not f[1]:match("^#")and not f[1]:match("^(cap|info)alias")and f[1]~="userdef"and f[1]~="SKIPWARN"and(f[3]=="bool"or f[3]=="num"or f[3]=="str")then local k=f[3];small[k.."names"]=small[k.."names"]..'\t\t"'..f[2]..'",\n';large[k.."names"]=large[k.."names"]..item(k,f[2]);small[k.."fnames"]=small[k.."fnames"]..'\t\t"'..f[1]..'",\n';large[k.."fnames"]=large[k.."fnames"]..item(k,f[1])end end
if #a>1 then for i=2,#a do local f=assert(io.open(a[i]));for l in f:lines()do add(l)end;f:close()end else for l in io.stdin:lines()do add(l)end end
local names={"boolnames","boolfnames","numnames","numfnames","strnames","strfnames"};local function strings(n)print("DCL("..n..") = {\n"..small[n].."\t\t(NCURSES_CONST char *)0,\n};\n")end
print("/* This file was generated by MKnames.lua */\n\n#include <curses.priv.h>\n\n#define IT NCURSES_CONST char * const\n\n#if BROKEN_LINKER || USE_REENTRANT\n")
if big~=0 then print("static const char _nc_name_blob[] = \n"..blob..";\n");for _,n in ipairs(names)do print("static const short _nc_offset_"..n.."[] = {\n"..large[n].."};\nstatic NCURSES_CONST char ** ptr_"..n.." = 0;\n")end;print([[static IT * alloc_array(NCURSES_CONST char ***value, const short *offsets, unsigned size) { unsigned n; if (!*value && (*value = typeCalloc(NCURSES_CONST char *, size + 1))) for (n=0;n<size;n++) (*value)[n]=(NCURSES_CONST char *)_nc_name_blob+offsets[n]; return *value; }
#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return alloc_array(&ptr_##it, _nc_offset_##it, SIZEOF(_nc_offset_##it)); }]])else print("#define DCL(it) static IT data##it[]\n");for _,n in ipairs(names)do strings(n)end;print("#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return data##it; }")end
for _,n in ipairs(names)do print("#undef "..n)end;for _,n in ipairs(names)do print("FIX("..n..")")end;for _,n in ipairs(names)do print("#define "..n.." NCURSES_PUBLIC_VAR("..n.."())")end
print("#define FREE_FIX(it) if (ptr_##it) { FreeAndNull(ptr_##it); }\n#if NO_LEAKS\nNCURSES_EXPORT(void) _nc_names_leaks(void) {");if big~=0 then for _,n in ipairs(names)do print("FREE_FIX("..n..")")end end;print("}\n#endif\n#else\n#define DCL(it) NCURSES_EXPORT_VAR(IT) it[]")
for _,n in ipairs(names)do strings(n)end;print("#endif /* BROKEN_LINKER */")
