#!/usr/bin/perl
# PeteleOS: libraries/extra/libcurses/tinfo/MKnames.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
# Perl translation of MKnames.awk (provenance preserved below).
#
# $OpenBSD: MKnames.awk,v 1.4 2023/10/17 09:52:09 nicm Exp $
##############################################################################
# Copyright 2019,2020 Thomas E. Dickey                                       #
# Copyright 1998-2008,2009 Free Software Foundation, Inc.                    #
#                                                                            #
# Permission is hereby granted, free of charge, to any person obtaining a    #
# copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation  #
# the rights to use, copy, modify, merge, publish, distribute, distribute    #
# with modifications, sublicense, and/or sell copies of the Software, and to #
# permit persons to whom the Software is furnished to do so, subject to the  #
# following conditions:                                                      #
#                                                                            #
# The above copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                        #
#                                                                            #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    #
# THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER        #
# DEALINGS IN THE SOFTWARE.                                                  #
#                                                                            #
# Except as contained in this notice, the name(s) of the above copyright     #
# holders shall not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written               #
# authorization.                                                             #
##############################################################################
# $Id: MKnames.awk,v 1.4 2023/10/17 09:52:09 nicm Exp $
use strict;
use warnings;

my %vars;
while (@ARGV && $ARGV[0] =~ /^(\w+)=(.*)$/) {
    $vars{$1} = $2;
    shift @ARGV;
}
my $bigstrings = defined $vars{bigstrings} ? $vars{bigstrings} : 0;

my $offset = 0;
my $offcol = 0;
my $bigcol = 0;
my $bigstr = '';

my $small_boolnames = '';  my $large_boolnames = '';
my $small_boolfnames = ''; my $large_boolfnames = '';
my $small_numnames = '';   my $large_numnames = '';
my $small_numfnames = '';  my $large_numfnames = '';
my $small_strnames = '';   my $large_strnames = '';
my $small_strfnames = '';  my $large_strfnames = '';

sub large_item {
    my ($value) = @_;
    my $result = sprintf("%d,", $offset);
    $offset = $offset + length($value) + 1;
    $offcol = $offcol + length($result) + 2;
    if ($offcol > 70) {
        $result = $result . "\n";
        $offcol = 0;
    } else {
        $result = $result . " ";
    }
    $bigstr = $bigstr . sprintf("\"%s\\0\" ", $value);
    $bigcol = $bigcol + length($value) + 5;
    if ($bigcol > 70) {
        $bigstr = $bigstr . "\\\n";
        $bigcol = 0;
    }
    return $result;
}

sub small_item {
    my ($value) = @_;
    return sprintf("\t\t\"%s\",\n", $value);
}

sub print_strings {
    my ($name, $value) = @_;
    printf "DCL(%s) = {\n", $name;
    print "$value\n";
    print "\t\t(NCURSES_CONST char *)0,\n";
    print "};\n";
    print "\n";
}

sub print_offsets {
    my ($name, $value) = @_;
    printf "static const short _nc_offset_%s[] = {\n", $name;
    printf "%s", $value;
    print "};\n";
    print "\n";
    printf "static NCURSES_CONST char ** ptr_%s = 0;\n", $name;
    print "\n";
}

print "/* This file was generated by MKnames.awk */\n";
print "\n";
print "#include <curses.priv.h>\n";
print "\n";
print "#define IT NCURSES_CONST char * const\n";
print "\n";

while (my $line = <>) {
    chomp $line;
    my @f = split(' ', $line);
    my $f1 = defined $f[0] ? $f[0] : '';
    my $f2 = defined $f[1] ? $f[1] : '';
    my $f3 = defined $f[2] ? $f[2] : '';

    next if $f1 =~ /^#/;
    next if $f1 =~ /^(cap|info)alias/;
    next if $f1 eq "userdef";
    next if $f1 eq "SKIPWARN";

    if ($f3 eq "bool") {
        $small_boolnames  = $small_boolnames  . small_item($f2);
        $large_boolnames  = $large_boolnames  . large_item($f2);
        $small_boolfnames = $small_boolfnames . small_item($f1);
        $large_boolfnames = $large_boolfnames . large_item($f1);
    }
    if ($f3 eq "num") {
        $small_numnames  = $small_numnames  . small_item($f2);
        $large_numnames  = $large_numnames  . large_item($f2);
        $small_numfnames = $small_numfnames . small_item($f1);
        $large_numfnames = $large_numfnames . large_item($f1);
    }
    if ($f3 eq "str") {
        $small_strnames  = $small_strnames  . small_item($f2);
        $large_strnames  = $large_strnames  . large_item($f2);
        $small_strfnames = $small_strfnames . small_item($f1);
        $large_strfnames = $large_strfnames . large_item($f1);
    }
}

print "\n";
print "#if BROKEN_LINKER || USE_REENTRANT\n";
print "\n";
if ($bigstrings) {
    printf "static const char _nc_name_blob[] = \n";
    printf "%s;\n", $bigstr;
    print_offsets("boolfnames", $large_boolfnames);
    print_offsets("boolnames", $large_boolnames);
    print_offsets("numfnames", $large_numfnames);
    print_offsets("numnames", $large_numnames);
    print_offsets("strfnames", $large_strfnames);
    print_offsets("strnames", $large_strnames);
    print "\n";
    print "static IT *\n";
    print "alloc_array(NCURSES_CONST char ***value, const short *offsets, unsigned size)\n";
    print "{\n";
    print "\tif (*value == 0) {\n";
    print "\t\tif ((*value = typeCalloc(NCURSES_CONST char *, size + 1)) != 0) {\n";
    print "\t\t\tunsigned n;\n";
    print "\t\t\tfor (n = 0; n < size; ++n) {\n";
    print "\t\t\t\t(*value)[n] = (NCURSES_CONST char *) _nc_name_blob + offsets[n];\n";
    print "\t\t\t}\n";
    print "\t\t}\n";
    print "\t}\n";
    print "\treturn *value;\n";
    print "}\n";
    print "\n";
    print "#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return alloc_array(&ptr_##it, _nc_offset_##it, SIZEOF(_nc_offset_##it)); }\n";
} else {
    print "#define DCL(it) static IT data##it[]\n";
    print "\n";
    print_strings("boolnames", $small_boolnames);
    print_strings("boolfnames", $small_boolfnames);
    print_strings("numnames", $small_numnames);
    print_strings("numfnames", $small_numfnames);
    print_strings("strnames", $small_strnames);
    print_strings("strfnames", $small_strfnames);
    print "#define FIX(it) NCURSES_IMPEXP IT * NCURSES_API NCURSES_PUBLIC_VAR(it)(void) { return data##it; }\n";
}
print "\n";
print "/* remove public definition which conflicts with FIX() */\n";
print "#undef boolnames\n";
print "#undef boolfnames\n";
print "#undef numnames\n";
print "#undef numfnames\n";
print "#undef strnames\n";
print "#undef strfnames\n";
print "\n";
print "/* add local definition */\n";
print "FIX(boolnames)\n";
print "FIX(boolfnames)\n";
print "FIX(numnames)\n";
print "FIX(numfnames)\n";
print "FIX(strnames)\n";
print "FIX(strfnames)\n";
print "\n";
print "/* restore the public definition */\n";
print "#define boolnames  NCURSES_PUBLIC_VAR(boolnames())\n";
print "#define boolfnames NCURSES_PUBLIC_VAR(boolfnames())\n";
print "#define numnames   NCURSES_PUBLIC_VAR(numnames())\n";
print "#define numfnames  NCURSES_PUBLIC_VAR(numfnames())\n";
print "#define strnames   NCURSES_PUBLIC_VAR(strnames())\n";
print "#define strfnames  NCURSES_PUBLIC_VAR(strfnames())\n";
print "\n";
print "#define FREE_FIX(it) if (ptr_##it) { FreeAndNull(ptr_##it); }\n";
print "\n";
print "#if NO_LEAKS\n";
print "NCURSES_EXPORT(void)\n";
print "_nc_names_leaks(void)\n";
print "{\n";
if ($bigstrings) {
    print "FREE_FIX(boolnames)\n";
    print "FREE_FIX(boolfnames)\n";
    print "FREE_FIX(numnames)\n";
    print "FREE_FIX(numfnames)\n";
    print "FREE_FIX(strnames)\n";
    print "FREE_FIX(strfnames)\n";
}
print "}\n";
print "#endif\n";
print "\n";
print "#else\n";
print "\n";
print "#define DCL(it) NCURSES_EXPORT_VAR(IT) it[]\n";
print "\n";
print_strings("boolnames", $small_boolnames);
print_strings("boolfnames", $small_boolfnames);
print_strings("numnames", $small_numnames);
print_strings("numfnames", $small_numfnames);
print_strings("strnames", $small_strnames);
print_strings("strfnames", $small_strfnames);
print "\n";
print "#endif /* BROKEN_LINKER */\n";
