/*
 * Copyright 2024 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 *
 */
#ifndef _thm_14_0_2_SH_MASK_HEADER
#define _thm_14_0_2_SH_MASK_HEADER

// addressBlock: thm_thm_SmuThmDec
//THM_TCON_CUR_TMP
#define THM_TCON_CUR_TMP__CUR_TEMP_RANGE_SEL__SHIFT 0x13
#define THM_TCON_CUR_TMP__CUR_TEMP__SHIFT 0x15
#define THM_TCON_CUR_TMP__CUR_TEMP_RANGE_SEL_MASK 0x00080000L
#define THM_TCON_CUR_TMP__CUR_TEMP_MASK 0xFFE00000L
//THM_THERMAL_INT_ENA
#define THM_THERMAL_INT_ENA__THERM_INTH_CLR__SHIFT 0x3
#define THM_THERMAL_INT_ENA__THERM_INTL_CLR__SHIFT 0x4
#define THM_THERMAL_INT_ENA__THERM_TRIGGER_CLR__SHIFT 0x5
#define THM_THERMAL_INT_ENA__THERM_INTH_CLR_MASK 0x00000008L
#define THM_THERMAL_INT_ENA__THERM_INTL_CLR_MASK 0x00000010L
#define THM_THERMAL_INT_ENA__THERM_TRIGGER_CLR_MASK 0x00000020L
//THM_THERMAL_INT_CTRL
#define THM_THERMAL_INT_CTRL__DIG_THERM_INTH__SHIFT 0x0
#define THM_THERMAL_INT_CTRL__DIG_THERM_INTL__SHIFT 0x8
#define THM_THERMAL_INT_CTRL__THERM_INTH_MASK__SHIFT 0x18
#define THM_THERMAL_INT_CTRL__THERM_INTL_MASK__SHIFT 0x19
#define THM_THERMAL_INT_CTRL__THERM_TRIGGER_MASK__SHIFT 0x1a
#define THM_THERMAL_INT_CTRL__THERM_IH_HW_ENA__SHIFT 0x1c
#define THM_THERMAL_INT_CTRL__MAX_IH_CREDIT__SHIFT 0x1d
#define THM_THERMAL_INT_CTRL__DIG_THERM_INTH_MASK 0x000000FFL
#define THM_THERMAL_INT_CTRL__DIG_THERM_INTL_MASK 0x0000FF00L
#define THM_THERMAL_INT_CTRL__THERM_INTH_MASK_MASK 0x01000000L
#define THM_THERMAL_INT_CTRL__THERM_INTL_MASK_MASK 0x02000000L
#define THM_THERMAL_INT_CTRL__THERM_TRIGGER_MASK_MASK 0x04000000L
#define THM_THERMAL_INT_CTRL__THERM_IH_HW_ENA_MASK 0x10000000L
#define THM_THERMAL_INT_CTRL__MAX_IH_CREDIT_MASK 0xE0000000L
//CG_MULT_THERMAL_CTRL
#define CG_MULT_THERMAL_CTRL__TEMP_SEL__SHIFT 0x14
#define CG_MULT_THERMAL_CTRL__TEMP_SEL_MASK 0x0FF00000L
//CG_MULT_THERMAL_STATUS
#define CG_MULT_THERMAL_STATUS__CTF_TEMP__SHIFT 0x9
#define CG_MULT_THERMAL_STATUS__CTF_TEMP_MASK 0x0003FE00L
//CG_FDO_CTRL0
#define CG_FDO_CTRL0__FDO_STATIC_DUTY__SHIFT 0x0
#define CG_FDO_CTRL0__FDO_STATIC_DUTY_MASK 0x000000FFL
//CG_FDO_CTRL1
#define CG_FDO_CTRL1__FMAX_DUTY100__SHIFT 0x0
#define CG_FDO_CTRL1__FMAX_DUTY100_MASK 0x000000FFL
//CG_FDO_CTRL2
#define CG_FDO_CTRL2__TMIN__SHIFT 0x0
#define CG_FDO_CTRL2__FDO_PWM_MODE__SHIFT 0xb
#define CG_FDO_CTRL2__TACH_PWM_RESP_RATE__SHIFT 0x19
#define CG_FDO_CTRL2__TMIN_MASK 0x000000FFL
#define CG_FDO_CTRL2__FDO_PWM_MODE_MASK 0x00003800L
#define CG_FDO_CTRL2__TACH_PWM_RESP_RATE_MASK 0xFE000000L
//CG_TACH_CTRL
#define CG_TACH_CTRL__EDGE_PER_REV__SHIFT 0x0
#define CG_TACH_CTRL__TARGET_PERIOD__SHIFT 0x3
#define CG_TACH_CTRL__EDGE_PER_REV_MASK 0x00000007L
#define CG_TACH_CTRL__TARGET_PERIOD_MASK 0xFFFFFFF8L
//CG_TACH_STATUS
#define CG_TACH_STATUS__TACH_PERIOD__SHIFT 0x0
#define CG_TACH_STATUS__TACH_PERIOD_MASK 0xFFFFFFFFL
//CG_THERMAL_STATUS
#define CG_THERMAL_STATUS__FDO_PWM_DUTY__SHIFT 0x9
#define CG_THERMAL_STATUS__FDO_PWM_DUTY_MASK 0x0001FE00L
//THM_BACO_CNTL
#define THM_BACO_CNTL__BACO_ISO_EN__SHIFT 0x1
#define THM_BACO_CNTL__BACO_PWROKRAW_CNTL__SHIFT 0x2
#define THM_BACO_CNTL__BACO_RESET_EN__SHIFT 0x3
#define THM_BACO_CNTL__BACO_SOC_VDCI_RESET__SHIFT 0x4
#define THM_BACO_CNTL__BACO_SMNCLK_MUX__SHIFT 0x5
#define THM_BACO_CNTL__BACO_SOC_REFCLK_OFF__SHIFT 0x6
#define THM_BACO_CNTL__BACO_AEB_ISO_EN__SHIFT 0x7
#define THM_BACO_CNTL__BACO_EXIT__SHIFT 0x8
#define THM_BACO_CNTL__BACO_ANA_ISO_EN__SHIFT 0x9
#define THM_BACO_CNTL__BACO_SB_AXI_FENCE__SHIFT 0x1e
#define THM_BACO_CNTL__SOC_DOMAIN_IDLE__SHIFT 0x1f
#define THM_BACO_CNTL__BACO_ISO_EN_MASK 0x00000002L
#define THM_BACO_CNTL__BACO_PWROKRAW_CNTL_MASK 0x00000004L
#define THM_BACO_CNTL__BACO_RESET_EN_MASK 0x00000008L
#define THM_BACO_CNTL__BACO_SOC_VDCI_RESET_MASK 0x00000010L
#define THM_BACO_CNTL__BACO_SMNCLK_MUX_MASK 0x00000020L
#define THM_BACO_CNTL__BACO_SOC_REFCLK_OFF_MASK 0x00000040L
#define THM_BACO_CNTL__BACO_AEB_ISO_EN_MASK 0x00000080L
#define THM_BACO_CNTL__BACO_EXIT_MASK 0x00000100L
#define THM_BACO_CNTL__BACO_ANA_ISO_EN_MASK 0x00000200L
#define THM_BACO_CNTL__BACO_SB_AXI_FENCE_MASK 0x40000000L
#define THM_BACO_CNTL__SOC_DOMAIN_IDLE_MASK 0x80000000L
#endif
