/*
 * Copyright (C) 2017  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _dce_12_0_OFFSET_HEADER
#define _dce_12_0_OFFSET_HEADER

// addressBlock: dce_dc_dispdec
// base address: 0x0
#define mmVGA_RENDER_CONTROL 0x0000
#define mmVGA_RENDER_CONTROL_BASE_IDX 1
#define mmVGA_HDP_CONTROL 0x000a
#define mmVGA_HDP_CONTROL_BASE_IDX 1
#define mmD1VGA_CONTROL 0x000c
#define mmD1VGA_CONTROL_BASE_IDX 1
#define mmD2VGA_CONTROL 0x000e
#define mmD2VGA_CONTROL_BASE_IDX 1
#define mmVGA_TEST_CONTROL 0x0015
#define mmVGA_TEST_CONTROL_BASE_IDX 1
#define mmD3VGA_CONTROL 0x0038
#define mmD3VGA_CONTROL_BASE_IDX 1
#define mmD4VGA_CONTROL 0x0039
#define mmD4VGA_CONTROL_BASE_IDX 1
#define mmD5VGA_CONTROL 0x003a
#define mmD5VGA_CONTROL_BASE_IDX 1
#define mmD6VGA_CONTROL 0x003b
#define mmD6VGA_CONTROL_BASE_IDX 1
#define mmREFCLK_CNTL 0x0049
#define mmREFCLK_CNTL_BASE_IDX 1
#define mmDPREFCLK_CNTL 0x0058
#define mmDPREFCLK_CNTL_BASE_IDX 1
#define mmDENTIST_DISPCLK_CNTL 0x0064
#define mmDENTIST_DISPCLK_CNTL_BASE_IDX 1
#define mmSMU_INTERRUPT_CONTROL 0x006e
#define mmSMU_INTERRUPT_CONTROL_BASE_IDX 1
#define mmMILLISECOND_TIME_BASE_DIV 0x0070
#define mmMILLISECOND_TIME_BASE_DIV_BASE_IDX 1
#define mmDISPCLK_FREQ_CHANGE_CNTL 0x0071
#define mmDISPCLK_FREQ_CHANGE_CNTL_BASE_IDX 1
#define mmDC_MEM_GLOBAL_PWR_REQ_CNTL 0x0072
#define mmDC_MEM_GLOBAL_PWR_REQ_CNTL_BASE_IDX 1
#define mmDCCG_GATE_DISABLE_CNTL 0x0074
#define mmDCCG_GATE_DISABLE_CNTL_BASE_IDX 1
#define mmMICROSECOND_TIME_BASE_DIV 0x007b
#define mmMICROSECOND_TIME_BASE_DIV_BASE_IDX 1
#define mmDCCG_GATE_DISABLE_CNTL2 0x007c
#define mmDCCG_GATE_DISABLE_CNTL2_BASE_IDX 1
#define mmSYMCLKA_CLOCK_ENABLE 0x00a0
#define mmSYMCLKA_CLOCK_ENABLE_BASE_IDX 1
#define mmSYMCLKB_CLOCK_ENABLE 0x00a1
#define mmSYMCLKB_CLOCK_ENABLE_BASE_IDX 1
#define mmSYMCLKC_CLOCK_ENABLE 0x00a2
#define mmSYMCLKC_CLOCK_ENABLE_BASE_IDX 1
#define mmSYMCLKD_CLOCK_ENABLE 0x00a3
#define mmSYMCLKD_CLOCK_ENABLE_BASE_IDX 1
#define mmSYMCLKE_CLOCK_ENABLE 0x00a4
#define mmSYMCLKE_CLOCK_ENABLE_BASE_IDX 1
#define mmDCCG_AUDIO_DTO_SOURCE 0x00ab
#define mmDCCG_AUDIO_DTO_SOURCE_BASE_IDX 1
#define mmDCCG_AUDIO_DTO0_PHASE 0x00ac
#define mmDCCG_AUDIO_DTO0_PHASE_BASE_IDX 1
#define mmDCCG_AUDIO_DTO0_MODULE 0x00ad
#define mmDCCG_AUDIO_DTO0_MODULE_BASE_IDX 1
#define mmDCCG_AUDIO_DTO1_PHASE 0x00ae
#define mmDCCG_AUDIO_DTO1_PHASE_BASE_IDX 1
#define mmDCCG_AUDIO_DTO1_MODULE 0x00af
#define mmDCCG_AUDIO_DTO1_MODULE_BASE_IDX 1
#define mmFBC_CNTL 0x0062
#define mmFBC_CNTL_BASE_IDX 2
#define mmFBC_IDLE_FORCE_CLEAR_MASK 0x0064
#define mmFBC_IDLE_FORCE_CLEAR_MASK_BASE_IDX 2
#define mmFBC_COMP_CNTL 0x0066
#define mmFBC_COMP_CNTL_BASE_IDX 2
#define mmFBC_COMP_MODE 0x0067
#define mmFBC_COMP_MODE_BASE_IDX 2
#define mmFBC_IND_LUT0 0x006b
#define mmFBC_IND_LUT0_BASE_IDX 2
#define mmFBC_IND_LUT1 0x006c
#define mmFBC_IND_LUT1_BASE_IDX 2
#define mmFBC_CLIENT_REGION_MASK 0x007d
#define mmFBC_CLIENT_REGION_MASK_BASE_IDX 2
#define mmFBC_DEBUG_COMP 0x007e
#define mmFBC_DEBUG_COMP_BASE_IDX 2
#define mmFBC_MISC 0x0084
#define mmFBC_MISC_BASE_IDX 2
#define mmFBC_STATUS 0x0085
#define mmFBC_STATUS_BASE_IDX 2
#define mmDC_IP_REQUEST_CNTL 0x00ac
#define mmDC_IP_REQUEST_CNTL_BASE_IDX 2
#define mmDMIF_ADDR_CALC 0x00d1
#define mmDMIF_ADDR_CALC_BASE_IDX 2
#define mmLOW_POWER_TILING_CONTROL 0x00d9
#define mmLOW_POWER_TILING_CONTROL_BASE_IDX 2
#define mmCC_DC_PIPE_DIS 0x00e0
#define mmCC_DC_PIPE_DIS_BASE_IDX 2
#define mmSMU_WM_CONTROL 0x00e1
#define mmSMU_WM_CONTROL_BASE_IDX 2
#define mmRBBMIF_TIMEOUT_DIS 0x00e4
#define mmRBBMIF_TIMEOUT_DIS_BASE_IDX 2
#define mmDCI_MEM_PWR_STATUS 0x00e5
#define mmDCI_MEM_PWR_STATUS_BASE_IDX 2
#define mmDCI_CLK_CNTL 0x00e7
#define mmDCI_CLK_CNTL_BASE_IDX 2
#define mmPIPE0_DMIF_BUFFER_CONTROL 0x00ef
#define mmPIPE0_DMIF_BUFFER_CONTROL_BASE_IDX 2
#define mmDVMM_PTE_REQ 0x00fe
#define mmDVMM_PTE_REQ_BASE_IDX 2
#define mmDCHUB_FB_LOCATION 0x0126
#define mmDCHUB_FB_LOCATION_BASE_IDX 2
#define mmDCHUB_AGP_BASE 0x0128
#define mmDCHUB_AGP_BASE_BASE_IDX 2
#define mmDCHUB_AGP_BOT 0x0129
#define mmDCHUB_AGP_BOT_BASE_IDX 2
#define mmDCHUB_AGP_TOP 0x012a
#define mmDCHUB_AGP_TOP_BASE_IDX 2
#define mmWB_ENABLE 0x0212
#define mmWB_ENABLE_BASE_IDX 2
#define mmWB_EC_CONFIG 0x0213
#define mmWB_EC_CONFIG_BASE_IDX 2
#define mmCNV_MODE 0x0214
#define mmCNV_MODE_BASE_IDX 2
#define mmWB_SOFT_RESET 0x0230
#define mmWB_SOFT_RESET_BASE_IDX 2
#define mmDMCU_CTRL 0x03b6
#define mmDMCU_CTRL_BASE_IDX 2
#define mmDMCU_STATUS 0x03b7
#define mmDMCU_STATUS_BASE_IDX 2
#define mmDMCU_RAM_ACCESS_CTRL 0x03be
#define mmDMCU_RAM_ACCESS_CTRL_BASE_IDX 2
#define mmDMCU_IRAM_WR_CTRL 0x03c3
#define mmDMCU_IRAM_WR_CTRL_BASE_IDX 2
#define mmDMCU_IRAM_WR_DATA 0x03c4
#define mmDMCU_IRAM_WR_DATA_BASE_IDX 2
#define mmDMCU_IRAM_RD_CTRL 0x03c5
#define mmDMCU_IRAM_RD_CTRL_BASE_IDX 2
#define mmDMCU_IRAM_RD_DATA 0x03c6
#define mmDMCU_IRAM_RD_DATA_BASE_IDX 2
#define mmDMCU_INTERRUPT_TO_UC_EN_MASK 0x03cc
#define mmDMCU_INTERRUPT_TO_UC_EN_MASK_BASE_IDX 2
#define mmDC_DMCU_SCRATCH 0x03ce
#define mmDC_DMCU_SCRATCH_BASE_IDX 2
#define mmMASTER_COMM_DATA_REG1 0x03d2
#define mmMASTER_COMM_DATA_REG1_BASE_IDX 2
#define mmMASTER_COMM_DATA_REG2 0x03d3
#define mmMASTER_COMM_DATA_REG2_BASE_IDX 2
#define mmMASTER_COMM_DATA_REG3 0x03d4
#define mmMASTER_COMM_DATA_REG3_BASE_IDX 2
#define mmMASTER_COMM_CMD_REG 0x03d5
#define mmMASTER_COMM_CMD_REG_BASE_IDX 2
#define mmMASTER_COMM_CNTL_REG 0x03d6
#define mmMASTER_COMM_CNTL_REG_BASE_IDX 2
#define mmSLAVE_COMM_DATA_REG1 0x03d7
#define mmSLAVE_COMM_DATA_REG1_BASE_IDX 2
#define mmSLAVE_COMM_DATA_REG2 0x03d8
#define mmSLAVE_COMM_DATA_REG2_BASE_IDX 2
#define mmSLAVE_COMM_DATA_REG3 0x03d9
#define mmSLAVE_COMM_DATA_REG3_BASE_IDX 2
#define mmSLAVE_COMM_CMD_REG 0x03da
#define mmSLAVE_COMM_CMD_REG_BASE_IDX 2
#define mmBL1_PWM_USER_LEVEL 0x03df
#define mmBL1_PWM_USER_LEVEL_BASE_IDX 2
#define mmBL1_PWM_TARGET_ABM_LEVEL 0x03e0
#define mmBL1_PWM_TARGET_ABM_LEVEL_BASE_IDX 2
#define mmBL1_PWM_CURRENT_ABM_LEVEL 0x03e1
#define mmBL1_PWM_CURRENT_ABM_LEVEL_BASE_IDX 2
#define mmBL1_PWM_BL_UPDATE_SAMPLE_RATE 0x03e5
#define mmBL1_PWM_BL_UPDATE_SAMPLE_RATE_BASE_IDX 2
#define mmDC_ABM1_IPCSC_COEFF_SEL 0x03ef
#define mmDC_ABM1_IPCSC_COEFF_SEL_BASE_IDX 2
#define mmDC_ABM1_ACE_OFFSET_SLOPE_0 0x03f0
#define mmDC_ABM1_ACE_OFFSET_SLOPE_0_BASE_IDX 2
#define mmDC_ABM1_ACE_THRES_12 0x03f5
#define mmDC_ABM1_ACE_THRES_12_BASE_IDX 2
#define mmDC_ABM1_HGLS_REG_READ_PROGRESS 0x0400
#define mmDC_ABM1_HGLS_REG_READ_PROGRESS_BASE_IDX 2
#define mmDC_ABM1_HG_MISC_CTRL 0x0401
#define mmDC_ABM1_HG_MISC_CTRL_BASE_IDX 2
#define mmDC_ABM1_LS_MIN_MAX_PIXEL_VALUE_THRES 0x0407
#define mmDC_ABM1_LS_MIN_MAX_PIXEL_VALUE_THRES_BASE_IDX 2
#define mmDC_ABM1_HG_SAMPLE_RATE 0x040a
#define mmDC_ABM1_HG_SAMPLE_RATE_BASE_IDX 2
#define mmDC_ABM1_LS_SAMPLE_RATE 0x040b
#define mmDC_ABM1_LS_SAMPLE_RATE_BASE_IDX 2
#define mmAZALIA_CONTROLLER_CLOCK_GATING 0x04bc
#define mmAZALIA_CONTROLLER_CLOCK_GATING_BASE_IDX 2
#define mmAZALIA_AUDIO_DTO 0x04bd
#define mmAZALIA_AUDIO_DTO_BASE_IDX 2
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_SUPPORTED_SIZE_RATES 0x0505
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_SUPPORTED_SIZE_RATES_BASE_IDX 2
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_STREAM_FORMATS 0x0506
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_STREAM_FORMATS_BASE_IDX 2
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_POWER_STATES 0x0507
#define mmAZALIA_F0_CODEC_FUNCTION_PARAMETER_POWER_STATES_BASE_IDX 2
#define mmDC_I2C_CONTROL 0x1584
#define mmDC_I2C_CONTROL_BASE_IDX 2
#define mmDC_I2C_ARBITRATION 0x1585
#define mmDC_I2C_ARBITRATION_BASE_IDX 2
#define mmDC_I2C_SW_STATUS 0x1587
#define mmDC_I2C_SW_STATUS_BASE_IDX 2
#define mmDC_I2C_TRANSACTION0 0x159a
#define mmDC_I2C_TRANSACTION0_BASE_IDX 2
#define mmDC_I2C_TRANSACTION1 0x159b
#define mmDC_I2C_TRANSACTION1_BASE_IDX 2
#define mmDC_I2C_TRANSACTION2 0x159c
#define mmDC_I2C_TRANSACTION2_BASE_IDX 2
#define mmDC_I2C_TRANSACTION3 0x159d
#define mmDC_I2C_TRANSACTION3_BASE_IDX 2
#define mmDC_I2C_DATA 0x159e
#define mmDC_I2C_DATA_BASE_IDX 2
#define mmDC_I2C_DDCVGA_SETUP 0x15a1
#define mmDC_I2C_DDCVGA_SETUP_BASE_IDX 2
#define mmDISP_INTERRUPT_STATUS 0x15bf
#define mmDISP_INTERRUPT_STATUS_BASE_IDX 2
#define mmDISP_INTERRUPT_STATUS_CONTINUE 0x15c0
#define mmDISP_INTERRUPT_STATUS_CONTINUE_BASE_IDX 2
#define mmDISP_INTERRUPT_STATUS_CONTINUE2 0x15c1
#define mmDISP_INTERRUPT_STATUS_CONTINUE2_BASE_IDX 2
#define mmDISP_INTERRUPT_STATUS_CONTINUE3 0x15c2
#define mmDISP_INTERRUPT_STATUS_CONTINUE3_BASE_IDX 2
#define mmDISP_INTERRUPT_STATUS_CONTINUE4 0x15c3
#define mmDISP_INTERRUPT_STATUS_CONTINUE4_BASE_IDX 2
#define mmDISP_INTERRUPT_STATUS_CONTINUE5 0x15c4
#define mmDISP_INTERRUPT_STATUS_CONTINUE5_BASE_IDX 2
#define mmDC_GPIO_DEBUG 0x2082
#define mmDC_GPIO_DEBUG_BASE_IDX 2
#define mmDC_PINSTRAPS 0x2096
#define mmDC_PINSTRAPS_BASE_IDX 2
#define mmCC_DC_MISC_STRAPS 0x2097
#define mmCC_DC_MISC_STRAPS_BASE_IDX 2
#define mmBL_PWM_CNTL 0x209e
#define mmBL_PWM_CNTL_BASE_IDX 2
#define mmBL_PWM_CNTL2 0x209f
#define mmBL_PWM_CNTL2_BASE_IDX 2
#define mmBL_PWM_PERIOD_CNTL 0x20a0
#define mmBL_PWM_PERIOD_CNTL_BASE_IDX 2
#define mmBL_PWM_GRP1_REG_LOCK 0x20a1
#define mmBL_PWM_GRP1_REG_LOCK_BASE_IDX 2
#define mmDCIO_GSL0_CNTL 0x20a4
#define mmDCIO_GSL0_CNTL_BASE_IDX 2
#define mmDCIO_SOFT_RESET 0x20b4
#define mmDCIO_SOFT_RESET_BASE_IDX 2
#define mmAUXP_IMPCAL 0x20b9
#define mmAUXP_IMPCAL_BASE_IDX 2
#define mmAUXN_IMPCAL 0x20ba
#define mmAUXN_IMPCAL_BASE_IDX 2
#define mmDC_GPIO_GENERIC_MASK 0x20de
#define mmDC_GPIO_GENERIC_MASK_BASE_IDX 2
#define mmDC_GPIO_GENERIC_A 0x20df
#define mmDC_GPIO_GENERIC_A_BASE_IDX 2
#define mmDC_GPIO_GENERIC_EN 0x20e0
#define mmDC_GPIO_GENERIC_EN_BASE_IDX 2
#define mmDC_GPIO_DVODATA_MASK 0x20e2
#define mmDC_GPIO_DVODATA_MASK_BASE_IDX 2
#define mmDC_GPIO_DVODATA_EN 0x20e4
#define mmDC_GPIO_DVODATA_EN_BASE_IDX 2
#define mmDC_GPIO_DDC1_A 0x20e7
#define mmDC_GPIO_DDC1_A_BASE_IDX 2
#define mmDC_GPIO_DDC2_A 0x20eb
#define mmDC_GPIO_DDC2_A_BASE_IDX 2
#define mmDC_GPIO_DDC3_A 0x20ef
#define mmDC_GPIO_DDC3_A_BASE_IDX 2
#define mmDC_GPIO_DDC4_A 0x20f3
#define mmDC_GPIO_DDC4_A_BASE_IDX 2
#define mmDC_GPIO_DDC5_A 0x20f7
#define mmDC_GPIO_DDC5_A_BASE_IDX 2
#define mmDC_GPIO_DDC6_A 0x20fb
#define mmDC_GPIO_DDC6_A_BASE_IDX 2
#define mmDC_GPIO_DDCVGA_A 0x20ff
#define mmDC_GPIO_DDCVGA_A_BASE_IDX 2
#define mmDC_GPIO_SYNCA_MASK 0x2102
#define mmDC_GPIO_SYNCA_MASK_BASE_IDX 2
#define mmDC_GPIO_SYNCA_A 0x2103
#define mmDC_GPIO_SYNCA_A_BASE_IDX 2
#define mmDC_GPIO_SYNCA_EN 0x2104
#define mmDC_GPIO_SYNCA_EN_BASE_IDX 2
#define mmDC_GPIO_GENLK_A 0x2107
#define mmDC_GPIO_GENLK_A_BASE_IDX 2
#define mmDC_GPIO_HPD_A 0x210b
#define mmDC_GPIO_HPD_A_BASE_IDX 2
#define mmDC_GPIO_PWRSEQ_A 0x210f
#define mmDC_GPIO_PWRSEQ_A_BASE_IDX 2
#define mmDC_GPIO_PAD_STRENGTH_1 0x2112
#define mmDC_GPIO_PAD_STRENGTH_1_BASE_IDX 2
#define mmDC_GPIO_PAD_STRENGTH_2 0x2113
#define mmDC_GPIO_PAD_STRENGTH_2_BASE_IDX 2
#define mmDC_GPIO_I2CPAD_A 0x2117
#define mmDC_GPIO_I2CPAD_A_BASE_IDX 2
// addressBlock: dce_dc_dcp0_dispdec
// base address: 0x0
#define mmDCP0_GRPH_CONTROL 0x055b
#define mmDCP0_GRPH_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dmif_pg0_dispdec
// base address: 0x0
#define mmDMIF_PG0_DPG_PIPE_ARBITRATION_CONTROL1 0x067a
#define mmDMIF_PG0_DPG_PIPE_ARBITRATION_CONTROL1_BASE_IDX 2
#define mmDMIF_PG0_DPG_WATERMARK_MASK_CONTROL 0x067c
#define mmDMIF_PG0_DPG_WATERMARK_MASK_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_scl0_dispdec
// base address: 0x0
#define mmSCL0_VIEWPORT_SIZE 0x06b0
#define mmSCL0_VIEWPORT_SIZE_BASE_IDX 2
// addressBlock: dce_dc_crtc0_dispdec
// base address: 0x0
#define mmCRTC0_CRTC_V_TOTAL 0x06da
#define mmCRTC0_CRTC_V_TOTAL_BASE_IDX 2
#define mmCRTC0_CRTC_V_BLANK_START_END 0x06e0
#define mmCRTC0_CRTC_V_BLANK_START_END_BASE_IDX 2
#define mmCRTC0_CRTC_V_SYNC_A_CNTL 0x06e2
#define mmCRTC0_CRTC_V_SYNC_A_CNTL_BASE_IDX 2
#define mmCRTC0_CRTC_FORCE_COUNT_NOW_CNTL 0x06eb
#define mmCRTC0_CRTC_FORCE_COUNT_NOW_CNTL_BASE_IDX 2
#define mmCRTC0_CRTC_CONTROL 0x06ef
#define mmCRTC0_CRTC_CONTROL_BASE_IDX 2
#define mmCRTC0_CRTC_BLANK_CONTROL 0x06f0
#define mmCRTC0_CRTC_BLANK_CONTROL_BASE_IDX 2
#define mmCRTC0_CRTC_STATUS 0x06f6
#define mmCRTC0_CRTC_STATUS_BASE_IDX 2
#define mmCRTC0_CRTC_STATUS_POSITION 0x06f7
#define mmCRTC0_CRTC_STATUS_POSITION_BASE_IDX 2
#define mmCRTC0_CRTC_NOM_VERT_POSITION 0x06f8
#define mmCRTC0_CRTC_NOM_VERT_POSITION_BASE_IDX 2
#define mmCRTC0_CRTC_STATUS_FRAME_COUNT 0x06f9
#define mmCRTC0_CRTC_STATUS_FRAME_COUNT_BASE_IDX 2
#define mmCRTC0_CRTC_START_LINE_CONTROL 0x0706
#define mmCRTC0_CRTC_START_LINE_CONTROL_BASE_IDX 2
#define mmCRTC0_CRTC_TEST_PATTERN_CONTROL 0x070b
#define mmCRTC0_CRTC_TEST_PATTERN_CONTROL_BASE_IDX 2
#define mmCRTC0_CRTC_TEST_PATTERN_PARAMETERS 0x070c
#define mmCRTC0_CRTC_TEST_PATTERN_PARAMETERS_BASE_IDX 2
#define mmCRTC0_CRTC_TEST_PATTERN_COLOR 0x070d
#define mmCRTC0_CRTC_TEST_PATTERN_COLOR_BASE_IDX 2
#define mmCRTC0_CRTC_MASTER_UPDATE_MODE 0x070f
#define mmCRTC0_CRTC_MASTER_UPDATE_MODE_BASE_IDX 2
#define mmCRTC0_CRTC_OVERSCAN_COLOR 0x0717
#define mmCRTC0_CRTC_OVERSCAN_COLOR_BASE_IDX 2
#define mmCRTC0_CRTC_BLANK_DATA_COLOR 0x0719
#define mmCRTC0_CRTC_BLANK_DATA_COLOR_BASE_IDX 2
#define mmCRTC0_CRTC_BLACK_COLOR 0x071b
#define mmCRTC0_CRTC_BLACK_COLOR_BASE_IDX 2
#define mmCRTC0_CRTC_CRC_CNTL 0x0723
#define mmCRTC0_CRTC_CRC_CNTL_BASE_IDX 2
#define mmCRTC0_CRTC_CRC0_DATA_RG 0x0728
#define mmCRTC0_CRTC_CRC0_DATA_RG_BASE_IDX 2
#define mmCRTC0_CRTC_CRC0_DATA_B 0x0729
#define mmCRTC0_CRTC_CRC0_DATA_B_BASE_IDX 2
#define mmCRTC0_CRTC_CRC1_DATA_RG 0x072e
#define mmCRTC0_CRTC_CRC1_DATA_RG_BASE_IDX 2
#define mmCRTC0_CRTC_CRC1_DATA_B 0x072f
#define mmCRTC0_CRTC_CRC1_DATA_B_BASE_IDX 2
#define mmCRTC0_CRTC_GSL_WINDOW 0x0739
#define mmCRTC0_CRTC_GSL_WINDOW_BASE_IDX 2
#define mmCRTC0_CRTC_GSL_CONTROL 0x073a
#define mmCRTC0_CRTC_GSL_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dcp1_dispdec
// base address: 0x800
#define mmDCP1_GRPH_CONTROL 0x075b
#define mmDCP1_GRPH_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dmif_pg1_dispdec
// base address: 0x800
#define mmDMIF_PG1_DPG_WATERMARK_MASK_CONTROL 0x087c
#define mmDMIF_PG1_DPG_WATERMARK_MASK_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_crtc1_dispdec
// base address: 0x800
#define mmCRTC1_CRTC_CONTROL 0x08ef
#define mmCRTC1_CRTC_CONTROL_BASE_IDX 2
#define mmCRTC1_CRTC_GSL_CONTROL 0x093a
#define mmCRTC1_CRTC_GSL_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dcp2_dispdec
// base address: 0x1000
#define mmDCP2_GRPH_CONTROL 0x095b
#define mmDCP2_GRPH_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dmif_pg2_dispdec
// base address: 0x1000
#define mmDMIF_PG2_DPG_WATERMARK_MASK_CONTROL 0x0a7c
#define mmDMIF_PG2_DPG_WATERMARK_MASK_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_crtc2_dispdec
// base address: 0x1000
#define mmCRTC2_CRTC_CONTROL 0x0aef
#define mmCRTC2_CRTC_CONTROL_BASE_IDX 2
#define mmCRTC2_CRTC_GSL_CONTROL 0x0b3a
#define mmCRTC2_CRTC_GSL_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dcp3_dispdec
// base address: 0x1800
#define mmDCP3_GRPH_CONTROL 0x0b5b
#define mmDCP3_GRPH_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dmif_pg3_dispdec
// base address: 0x1800
#define mmDMIF_PG3_DPG_WATERMARK_MASK_CONTROL 0x0c7c
#define mmDMIF_PG3_DPG_WATERMARK_MASK_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_crtc3_dispdec
// base address: 0x1800
#define mmCRTC3_CRTC_CONTROL 0x0cef
#define mmCRTC3_CRTC_CONTROL_BASE_IDX 2
#define mmCRTC3_CRTC_GSL_CONTROL 0x0d3a
#define mmCRTC3_CRTC_GSL_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dcp4_dispdec
// base address: 0x2000
#define mmDCP4_GRPH_CONTROL 0x0d5b
#define mmDCP4_GRPH_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dmif_pg4_dispdec
// base address: 0x2000
#define mmDMIF_PG4_DPG_WATERMARK_MASK_CONTROL 0x0e7c
#define mmDMIF_PG4_DPG_WATERMARK_MASK_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_crtc4_dispdec
// base address: 0x2000
#define mmCRTC4_CRTC_CONTROL 0x0eef
#define mmCRTC4_CRTC_CONTROL_BASE_IDX 2
#define mmCRTC4_CRTC_GSL_CONTROL 0x0f3a
#define mmCRTC4_CRTC_GSL_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dcp5_dispdec
// base address: 0x2800
#define mmDCP5_GRPH_CONTROL 0x0f5b
#define mmDCP5_GRPH_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dmif_pg5_dispdec
// base address: 0x2800
#define mmDMIF_PG5_DPG_WATERMARK_MASK_CONTROL 0x107c
#define mmDMIF_PG5_DPG_WATERMARK_MASK_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_crtc5_dispdec
// base address: 0x2800
#define mmCRTC5_CRTC_CONTROL 0x10ef
#define mmCRTC5_CRTC_CONTROL_BASE_IDX 2
#define mmCRTC5_CRTC_GSL_CONTROL 0x113a
#define mmCRTC5_CRTC_GSL_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_hpd0_dispdec
// base address: 0x0
#define mmHPD0_DC_HPD_CONTROL 0x1602
#define mmHPD0_DC_HPD_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_hpd1_dispdec
// base address: 0x20
#define mmHPD1_DC_HPD_CONTROL 0x160a
#define mmHPD1_DC_HPD_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_hpd2_dispdec
// base address: 0x40
#define mmHPD2_DC_HPD_CONTROL 0x1612
#define mmHPD2_DC_HPD_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_hpd3_dispdec
// base address: 0x60
#define mmHPD3_DC_HPD_CONTROL 0x161a
#define mmHPD3_DC_HPD_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_hpd4_dispdec
// base address: 0x80
#define mmHPD4_DC_HPD_CONTROL 0x1622
#define mmHPD4_DC_HPD_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_hpd5_dispdec
// base address: 0xa0
#define mmHPD5_DC_HPD_CONTROL 0x162a
#define mmHPD5_DC_HPD_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dig0_dispdec
// base address: 0x0
#define mmDIG0_HDMI_CONTROL 0x1887
#define mmDIG0_HDMI_CONTROL_BASE_IDX 2
// addressBlock: dce_dc_dp0_dispdec
// base address: 0x0
#define mmDP0_DP_DPHY_FAST_TRAINING 0x193a
#define mmDP0_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP0_DP_DPHY_BS_SR_SWAP_CNTL 0x195a
#define mmDP0_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
// addressBlock: dce_dc_dp1_dispdec
// base address: 0x400
#define mmDP1_DP_DPHY_FAST_TRAINING 0x1a3a
#define mmDP1_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP1_DP_DPHY_BS_SR_SWAP_CNTL 0x1a5a
#define mmDP1_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
// addressBlock: dce_dc_dp2_dispdec
// base address: 0x800
#define mmDP2_DP_DPHY_FAST_TRAINING 0x1b3a
#define mmDP2_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP2_DP_DPHY_BS_SR_SWAP_CNTL 0x1b5a
#define mmDP2_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
// addressBlock: dce_dc_dp3_dispdec
// base address: 0xc00
#define mmDP3_DP_DPHY_FAST_TRAINING 0x1c3a
#define mmDP3_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP3_DP_DPHY_BS_SR_SWAP_CNTL 0x1c5a
#define mmDP3_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
// addressBlock: dce_dc_dp4_dispdec
// base address: 0x1000
#define mmDP4_DP_DPHY_FAST_TRAINING 0x1d3a
#define mmDP4_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP4_DP_DPHY_BS_SR_SWAP_CNTL 0x1d5a
#define mmDP4_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
// addressBlock: dce_dc_dp5_dispdec
// base address: 0x1400
#define mmDP5_DP_DPHY_FAST_TRAINING 0x1e3a
#define mmDP5_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP5_DP_DPHY_BS_SR_SWAP_CNTL 0x1e5a
#define mmDP5_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
// addressBlock: dce_dc_dp6_dispdec
// base address: 0x1800
#define mmDP6_DP_DPHY_FAST_TRAINING 0x1f3a
#define mmDP6_DP_DPHY_FAST_TRAINING_BASE_IDX 2
#define mmDP6_DP_DPHY_BS_SR_SWAP_CNTL 0x1f5a
#define mmDP6_DP_DPHY_BS_SR_SWAP_CNTL_BASE_IDX 2
#endif
