-- EteleOS: installer/miniroot/makeconf.lua, time write: 2026/08/08
-- This file uses the Apache-2.0 license
--
-- Original AWK file license:
-- $OpenBSD: makeconf.awk,v 1.28 2019/06/07 14:38:42 deraadt Exp $
--
-- generate crunchgen(1) configuration file from `list' spec.
-- Ported from makeconf.awk (OpenBSD)

if io.stdout and io.stdout.setvbuf then io.stdout:setvbuf("no") end

local libs = "libs -lstubs -lutil -lm -ltls -lssl -lcrypto -levent -lc -lz"
local progs = {}   -- progs[p] = count of links
local links = {}   -- links[p][i] = link name
local specials = {} -- specials[key] = true

local function split_fields(line)
    local fields = {}
    for f in line:gmatch("%S+") do
        fields[#fields + 1] = f
    end
    return fields
end

io.write("#\n# This file is automatically generated by `makeconf'\n#\n\n")

for line in io.lines() do
    local f = split_fields(line)
    local NF = #f

    if NF == 0 then goto continue end

    local f1 = f[1]

    if f1 == "LIBS" then
        f[1] = f[1]:lower()
        libs = table.concat(f, " ")

    elseif f1 == "SRCDIRS" then
        f[1] = f[1]:lower()
        io.write(table.concat(f, " ") .. "\n")

    elseif (f1 == "LINK" or f1 == "SYMLINK") and f[2] == "instbin" then
        local parts3 = {}
        for part in (f[3] or ""):gmatch("[^/]+") do parts3[#parts3+1] = part end
        local p = parts3[#parts3]
        if p then
            progs[p] = NF - 3
            if not links[p] then links[p] = {} end
            for i = 4, NF do
                local parts_i = {}
                for part in (f[i] or ""):gmatch("[^/]+") do parts_i[#parts_i+1] = part end
                local l = parts_i[#parts_i]
                links[p][i - 3] = l
            end
        end

    elseif f1 == "ARGVLINK" then
        local p2 = f[2]
        if p2 then
            local n = (progs[p2] or 0) + 1
            progs[p2] = n
            if not links[p2] then links[p2] = {} end
            links[p2][n] = f[3]
        end

    elseif f1 == "CRUNCHSPECIAL" then
        f[1] = ""
        local key = table.concat(f, " ")
        key = key:match("^ *(.*)")
        specials[key] = true
    end

    ::continue::
end

local column = 0
for p in pairs(progs) do
    if (column % 8) == 0 then
        io.write("\nprogs")
    end
    io.write(" " .. p)
    column = column + 1
end
io.write("\n\n")

for p, n in pairs(progs) do
    for i = 1, n do
        local ln = links[p] and links[p][i]
        if ln then
            io.write(string.format("ln %s %s\n", p, ln))
        end
    end
end
io.write(string.format("\n%s\n\n", libs))
io.write("libdirs distrib/special/libstubs\n")

for s in pairs(specials) do
    io.write(string.format("special %s\n", s))
end
