#!/usr/bin/perl
# EteleOS: installer/miniroot/makeconf.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
# Converted from the original AWK implementation.
# Original header preserved below for provenance:
#
#	$OpenBSD: makeconf.awk,v 1.28 2019/06/07 14:38:42 deraadt Exp $
#
# generate crunchgen(1) configuration file from `list' spec.

use strict;
use warnings;

print "#\n# This file is automatically generated by `makeconf'\n#\n\n";
my $libs = "libs -lstubs -lutil -lm -ltls -lssl -lcrypto -levent -lc -lz";

my %progs;         # progs{p} = number of links
my %links;         # links{"i,p"} = link name
my %specials;       # specials{s} = 1
my @specials_order; # preserve insertion order (awk uses arbitrary array order)
my @progs_order;    # preserve first-seen order of progs

while (my $line = <>) {
	chomp $line;
	my @F = split(' ', $line);
	my $NF = scalar(@F);
	my $F1 = defined($F[0]) ? $F[0] : '';

	if ($F1 eq 'LIBS') {
		$F[0] = lc($F1);
		$libs = join(' ', @F);
		next;
	}

	if ($F1 eq 'SRCDIRS') {
		$F[0] = lc($F1);
		print join(' ', @F), "\n";
		next;
	}

	if (($F1 eq 'LINK' || $F1 eq 'SYMLINK') && defined($F[1]) && $F[1] eq 'instbin') {
		# find basenames for inclusion in crunchgen's `prog' and `ln' directives
		my @x = split('/', $F[2]);
		my $p = $x[-1];
		if (!exists $progs{$p}) {
			push @progs_order, $p;
		}
		$progs{$p} = $NF - 3;
		for (my $i = 4; $i <= $NF; $i++) {
			my @xi = split('/', $F[$i - 1]);
			my $l = $xi[-1];
			$links{($i - 3) . "," . $p} = $l;
		}
		next;
	}

	if ($F1 eq 'ARGVLINK') {
		# add extra `ln' entries (these don't appear in the filesystem)
		if (!exists $progs{$F[1]}) {
			push @progs_order, $F[1];
		}
		my $n = ($progs{$F[1]} || 0) + 1;
		$progs{$F[1]} = $n;
		$links{"$n,$F[1]"} = $F[2];
		next;
	}

	if ($F1 eq 'CRUNCHSPECIAL') {
		# collect crunchgen `special' directives
		$F[0] = '';
		my $rest = join(' ', @F);
		if (!exists $specials{$rest}) {
			push @specials_order, $rest;
		}
		$specials{$rest} = 1;
		next;
	}
}

# write crunchgen configuration

# `prog' directives; print 8 to a line
my $column = 0;
for my $p (@progs_order) {
	if (($column++ % 8) == 0) {
		print "\nprogs";
	}
	print " $p";
}
print "\n\n";

# `ln' directives
for my $p (@progs_order) {
	my $n = $progs{$p};
	for (my $i = 1; $i <= $n; $i++) {
		printf("ln %s %s\n", $p, $links{"$i,$p"});
	}
}
printf("\n%s\n\n", $libs);
print "libdirs distrib/special/libstubs\n";

# `special' directives
for my $s (@specials_order) {
	printf("special %s\n", $s);
}
