/*
 * Copyright (C) 2018  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _sdma1_4_2_2_OFFSET_HEADER
#define _sdma1_4_2_2_OFFSET_HEADER

// addressBlock: sdma1_sdma1dec
// base address: 0x6180
#define mmSDMA1_POWER_CNTL 0x001a
#define mmSDMA1_POWER_CNTL_BASE_IDX 0
#define mmSDMA1_CLK_CTRL 0x001b
#define mmSDMA1_CLK_CTRL_BASE_IDX 0
#define mmSDMA1_CHICKEN_BITS 0x001d
#define mmSDMA1_CHICKEN_BITS_BASE_IDX 0
#define mmSDMA1_GB_ADDR_CONFIG 0x001e
#define mmSDMA1_GB_ADDR_CONFIG_BASE_IDX 0
#define mmSDMA1_GB_ADDR_CONFIG_READ 0x001f
#define mmSDMA1_GB_ADDR_CONFIG_READ_BASE_IDX 0
#define mmSDMA1_STATUS_REG 0x0025
#define mmSDMA1_STATUS_REG_BASE_IDX 0
#define mmSDMA1_RD_BURST_CNTL 0x0027
#define mmSDMA1_RD_BURST_CNTL_BASE_IDX 0
#define mmSDMA1_UTCL1_WATERMK 0x003d
#define mmSDMA1_UTCL1_WATERMK_BASE_IDX 0
#define mmSDMA1_UTCL1_TIMEOUT 0x0047
#define mmSDMA1_UTCL1_TIMEOUT_BASE_IDX 0
#define mmSDMA1_UTCL1_PAGE 0x0048
#define mmSDMA1_UTCL1_PAGE_BASE_IDX 0
#define mmSDMA1_GFX_RB_WPTR_POLL_CNTL 0x0087
#define mmSDMA1_GFX_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_GFX_RB_RPTR_ADDR_LO 0x0089
#define mmSDMA1_GFX_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_GFX_IB_CNTL 0x008a
#define mmSDMA1_GFX_IB_CNTL_BASE_IDX 0
#define mmSDMA1_GFX_PREEMPT 0x00b0
#define mmSDMA1_GFX_PREEMPT_BASE_IDX 0
#define mmSDMA1_PAGE_RB_WPTR_POLL_CNTL 0x00df
#define mmSDMA1_PAGE_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_PAGE_RB_RPTR_ADDR_LO 0x00e1
#define mmSDMA1_PAGE_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_PAGE_IB_CNTL 0x00e2
#define mmSDMA1_PAGE_IB_CNTL_BASE_IDX 0
#define mmSDMA1_RLC0_RB_CNTL 0x0130
#define mmSDMA1_RLC0_RB_CNTL_BASE_IDX 0
#define mmSDMA1_RLC0_RB_WPTR_POLL_CNTL 0x0137
#define mmSDMA1_RLC0_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC0_RB_RPTR_ADDR_LO 0x0139
#define mmSDMA1_RLC0_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC0_IB_CNTL 0x013a
#define mmSDMA1_RLC0_IB_CNTL_BASE_IDX 0
#define mmSDMA1_RLC1_RB_WPTR_POLL_CNTL 0x018f
#define mmSDMA1_RLC1_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC1_RB_RPTR_ADDR_LO 0x0191
#define mmSDMA1_RLC1_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC1_IB_CNTL 0x0192
#define mmSDMA1_RLC1_IB_CNTL_BASE_IDX 0
#define mmSDMA1_RLC2_RB_WPTR_POLL_CNTL 0x01e7
#define mmSDMA1_RLC2_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC2_RB_RPTR_ADDR_LO 0x01e9
#define mmSDMA1_RLC2_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC3_RB_WPTR_POLL_CNTL 0x023f
#define mmSDMA1_RLC3_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC3_RB_RPTR_ADDR_LO 0x0241
#define mmSDMA1_RLC3_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC4_RB_WPTR_POLL_CNTL 0x0297
#define mmSDMA1_RLC4_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC4_RB_RPTR_ADDR_LO 0x0299
#define mmSDMA1_RLC4_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC5_RB_WPTR_POLL_CNTL 0x02ef
#define mmSDMA1_RLC5_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC5_RB_RPTR_ADDR_LO 0x02f1
#define mmSDMA1_RLC5_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC6_RB_WPTR_POLL_CNTL 0x0347
#define mmSDMA1_RLC6_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC6_RB_RPTR_ADDR_LO 0x0349
#define mmSDMA1_RLC6_RB_RPTR_ADDR_LO_BASE_IDX 0
#define mmSDMA1_RLC7_RB_WPTR_POLL_CNTL 0x039f
#define mmSDMA1_RLC7_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define mmSDMA1_RLC7_RB_RPTR_ADDR_LO 0x03a1
#define mmSDMA1_RLC7_RB_RPTR_ADDR_LO_BASE_IDX 0
#endif
