/*
 * Copyright 2021 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _lsdma_6_0_0_SH_MASK_HEADER
#define _lsdma_6_0_0_SH_MASK_HEADER

//LSDMA_PIO_STATUS
#define LSDMA_PIO_STATUS__PIO_FIFO_EMPTY__SHIFT 0x1c
#define LSDMA_PIO_STATUS__PIO_IDLE__SHIFT 0x1f
#define LSDMA_PIO_STATUS__PIO_FIFO_EMPTY_MASK 0x10000000L
#define LSDMA_PIO_STATUS__PIO_IDLE_MASK 0x80000000L
//LSDMA_PIO_COMMAND
#define LSDMA_PIO_COMMAND__BYTE_COUNT__SHIFT 0x0
#define LSDMA_PIO_COMMAND__SRC_LOCATION__SHIFT 0x1a
#define LSDMA_PIO_COMMAND__DST_LOCATION__SHIFT 0x1b
#define LSDMA_PIO_COMMAND__SRC_ADDR_INC__SHIFT 0x1c
#define LSDMA_PIO_COMMAND__DST_ADDR_INC__SHIFT 0x1d
#define LSDMA_PIO_COMMAND__OVERLAP_DISABLE__SHIFT 0x1e
#define LSDMA_PIO_COMMAND__CONSTANT_FILL__SHIFT 0x1f
#define LSDMA_PIO_COMMAND__BYTE_COUNT_MASK 0x03FFFFFFL
#define LSDMA_PIO_COMMAND__SRC_LOCATION_MASK 0x04000000L
#define LSDMA_PIO_COMMAND__DST_LOCATION_MASK 0x08000000L
#define LSDMA_PIO_COMMAND__SRC_ADDR_INC_MASK 0x10000000L
#define LSDMA_PIO_COMMAND__DST_ADDR_INC_MASK 0x20000000L
#define LSDMA_PIO_COMMAND__OVERLAP_DISABLE_MASK 0x40000000L
#define LSDMA_PIO_COMMAND__CONSTANT_FILL_MASK 0x80000000L
//LSDMA_MEM_POWER_CTRL
#define LSDMA_MEM_POWER_CTRL__MEM_POWER_CTRL_EN__SHIFT 0x0
#define LSDMA_MEM_POWER_CTRL__MEM_POWER_CTRL_EN_MASK 0x00000001L
#endif
