/*
 * Copyright 2021 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _sdma_4_4_2_OFFSET_HEADER
#define _sdma_4_4_2_OFFSET_HEADER

// addressBlock: aid_sdma_insts_sdma0_sdmadec
// base address: 0x4980
#define regSDMA_UCODE_ADDR 0x0000
#define regSDMA_UCODE_ADDR_BASE_IDX 0
#define regSDMA_UCODE_DATA 0x0001
#define regSDMA_UCODE_DATA_BASE_IDX 0
#define regSDMA_F32_CNTL 0x0002
#define regSDMA_F32_CNTL_BASE_IDX 0
#define regSDMA_VM_CNTL 0x0010
#define regSDMA_VM_CNTL_BASE_IDX 0
#define regSDMA_RB_RPTR_FETCH_HI 0x0020
#define regSDMA_RB_RPTR_FETCH_HI_BASE_IDX 0
#define regSDMA_SEM_WAIT_FAIL_TIMER_CNTL 0x0021
#define regSDMA_SEM_WAIT_FAIL_TIMER_CNTL_BASE_IDX 0
#define regSDMA_RB_RPTR_FETCH 0x0022
#define regSDMA_RB_RPTR_FETCH_BASE_IDX 0
#define regSDMA_STATUS_REG 0x0025
#define regSDMA_STATUS_REG_BASE_IDX 0
#define regSDMA_STATUS1_REG 0x0026
#define regSDMA_STATUS1_REG_BASE_IDX 0
#define regSDMA_UCODE_CHECKSUM 0x0029
#define regSDMA_UCODE_CHECKSUM_BASE_IDX 0
#define regSDMA_PHASE0_QUANTUM 0x002c
#define regSDMA_PHASE0_QUANTUM_BASE_IDX 0
#define regSDMA_PHASE1_QUANTUM 0x002d
#define regSDMA_PHASE1_QUANTUM_BASE_IDX 0
#define regSDMA_STATUS2_REG 0x0038
#define regSDMA_STATUS2_REG_BASE_IDX 0
#define regSDMA_UTCL1_RD_STATUS 0x003e
#define regSDMA_UTCL1_RD_STATUS_BASE_IDX 0
#define regSDMA_UTCL1_WR_STATUS 0x003f
#define regSDMA_UTCL1_WR_STATUS_BASE_IDX 0
#define regSDMA_UTCL1_RD_XNACK0 0x0043
#define regSDMA_UTCL1_RD_XNACK0_BASE_IDX 0
#define regSDMA_UTCL1_RD_XNACK1 0x0044
#define regSDMA_UTCL1_RD_XNACK1_BASE_IDX 0
#define regSDMA_UTCL1_WR_XNACK0 0x0045
#define regSDMA_UTCL1_WR_XNACK0_BASE_IDX 0
#define regSDMA_UTCL1_WR_XNACK1 0x0046
#define regSDMA_UTCL1_WR_XNACK1_BASE_IDX 0
#define regSDMA_UTCL1_TIMEOUT 0x0047
#define regSDMA_UTCL1_TIMEOUT_BASE_IDX 0
#define regSDMA_STATUS3_REG 0x004c
#define regSDMA_STATUS3_REG_BASE_IDX 0
#define regSDMA_PHASE2_QUANTUM 0x004f
#define regSDMA_PHASE2_QUANTUM_BASE_IDX 0
#define regSDMA_UE_ERR_STATUS_LO 0x0069
#define regSDMA_UE_ERR_STATUS_LO_BASE_IDX 0
#define regSDMA_UE_ERR_STATUS_HI 0x006a
#define regSDMA_UE_ERR_STATUS_HI_BASE_IDX 0
#define regSDMA_POWER_CNTL 0x006b
#define regSDMA_POWER_CNTL_BASE_IDX 0
#define regSDMA_CLK_CTRL 0x006c
#define regSDMA_CLK_CTRL_BASE_IDX 0
#define regSDMA_CNTL 0x006d
#define regSDMA_CNTL_BASE_IDX 0
#define regSDMA_GB_ADDR_CONFIG 0x006f
#define regSDMA_GB_ADDR_CONFIG_BASE_IDX 0
#define regSDMA_GB_ADDR_CONFIG_READ 0x0070
#define regSDMA_GB_ADDR_CONFIG_READ_BASE_IDX 0
#define regSDMA_GFX_RB_CNTL 0x0080
#define regSDMA_GFX_RB_CNTL_BASE_IDX 0
#define regSDMA_GFX_RB_BASE 0x0081
#define regSDMA_GFX_RB_BASE_BASE_IDX 0
#define regSDMA_GFX_RB_BASE_HI 0x0082
#define regSDMA_GFX_RB_BASE_HI_BASE_IDX 0
#define regSDMA_GFX_RB_RPTR 0x0083
#define regSDMA_GFX_RB_RPTR_BASE_IDX 0
#define regSDMA_GFX_RB_RPTR_HI 0x0084
#define regSDMA_GFX_RB_RPTR_HI_BASE_IDX 0
#define regSDMA_GFX_RB_WPTR 0x0085
#define regSDMA_GFX_RB_WPTR_BASE_IDX 0
#define regSDMA_GFX_RB_WPTR_HI 0x0086
#define regSDMA_GFX_RB_WPTR_HI_BASE_IDX 0
#define regSDMA_GFX_RB_WPTR_POLL_CNTL 0x0087
#define regSDMA_GFX_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define regSDMA_GFX_RB_RPTR_ADDR_HI 0x0088
#define regSDMA_GFX_RB_RPTR_ADDR_HI_BASE_IDX 0
#define regSDMA_GFX_RB_RPTR_ADDR_LO 0x0089
#define regSDMA_GFX_RB_RPTR_ADDR_LO_BASE_IDX 0
#define regSDMA_GFX_IB_CNTL 0x008a
#define regSDMA_GFX_IB_CNTL_BASE_IDX 0
#define regSDMA_GFX_IB_RPTR 0x008b
#define regSDMA_GFX_IB_RPTR_BASE_IDX 0
#define regSDMA_GFX_IB_OFFSET 0x008c
#define regSDMA_GFX_IB_OFFSET_BASE_IDX 0
#define regSDMA_GFX_IB_BASE_LO 0x008d
#define regSDMA_GFX_IB_BASE_LO_BASE_IDX 0
#define regSDMA_GFX_IB_BASE_HI 0x008e
#define regSDMA_GFX_IB_BASE_HI_BASE_IDX 0
#define regSDMA_GFX_CONTEXT_STATUS 0x0091
#define regSDMA_GFX_CONTEXT_STATUS_BASE_IDX 0
#define regSDMA_GFX_DOORBELL 0x0092
#define regSDMA_GFX_DOORBELL_BASE_IDX 0
#define regSDMA_GFX_DOORBELL_OFFSET 0x00ab
#define regSDMA_GFX_DOORBELL_OFFSET_BASE_IDX 0
#define regSDMA_GFX_IB_SUB_REMAIN 0x00af
#define regSDMA_GFX_IB_SUB_REMAIN_BASE_IDX 0
#define regSDMA_GFX_DUMMY_REG 0x00b1
#define regSDMA_GFX_DUMMY_REG_BASE_IDX 0
#define regSDMA_GFX_RB_WPTR_POLL_ADDR_HI 0x00b2
#define regSDMA_GFX_RB_WPTR_POLL_ADDR_HI_BASE_IDX 0
#define regSDMA_GFX_RB_WPTR_POLL_ADDR_LO 0x00b3
#define regSDMA_GFX_RB_WPTR_POLL_ADDR_LO_BASE_IDX 0
#define regSDMA_GFX_MINOR_PTR_UPDATE 0x00b5
#define regSDMA_GFX_MINOR_PTR_UPDATE_BASE_IDX 0
#define regSDMA_PAGE_RB_CNTL 0x00d8
#define regSDMA_PAGE_RB_CNTL_BASE_IDX 0
#define regSDMA_PAGE_RB_BASE 0x00d9
#define regSDMA_PAGE_RB_BASE_BASE_IDX 0
#define regSDMA_PAGE_RB_BASE_HI 0x00da
#define regSDMA_PAGE_RB_BASE_HI_BASE_IDX 0
#define regSDMA_PAGE_RB_RPTR 0x00db
#define regSDMA_PAGE_RB_RPTR_BASE_IDX 0
#define regSDMA_PAGE_RB_RPTR_HI 0x00dc
#define regSDMA_PAGE_RB_RPTR_HI_BASE_IDX 0
#define regSDMA_PAGE_RB_WPTR 0x00dd
#define regSDMA_PAGE_RB_WPTR_BASE_IDX 0
#define regSDMA_PAGE_RB_WPTR_HI 0x00de
#define regSDMA_PAGE_RB_WPTR_HI_BASE_IDX 0
#define regSDMA_PAGE_RB_WPTR_POLL_CNTL 0x00df
#define regSDMA_PAGE_RB_WPTR_POLL_CNTL_BASE_IDX 0
#define regSDMA_PAGE_RB_RPTR_ADDR_HI 0x00e0
#define regSDMA_PAGE_RB_RPTR_ADDR_HI_BASE_IDX 0
#define regSDMA_PAGE_RB_RPTR_ADDR_LO 0x00e1
#define regSDMA_PAGE_RB_RPTR_ADDR_LO_BASE_IDX 0
#define regSDMA_PAGE_IB_CNTL 0x00e2
#define regSDMA_PAGE_IB_CNTL_BASE_IDX 0
#define regSDMA_PAGE_IB_OFFSET 0x00e4
#define regSDMA_PAGE_IB_OFFSET_BASE_IDX 0
#define regSDMA_PAGE_IB_BASE_LO 0x00e5
#define regSDMA_PAGE_IB_BASE_LO_BASE_IDX 0
#define regSDMA_PAGE_IB_BASE_HI 0x00e6
#define regSDMA_PAGE_IB_BASE_HI_BASE_IDX 0
#define regSDMA_PAGE_CONTEXT_STATUS 0x00e9
#define regSDMA_PAGE_CONTEXT_STATUS_BASE_IDX 0
#define regSDMA_PAGE_DOORBELL 0x00ea
#define regSDMA_PAGE_DOORBELL_BASE_IDX 0
#define regSDMA_PAGE_DOORBELL_OFFSET 0x0103
#define regSDMA_PAGE_DOORBELL_OFFSET_BASE_IDX 0
#define regSDMA_PAGE_DUMMY_REG 0x0109
#define regSDMA_PAGE_DUMMY_REG_BASE_IDX 0
#define regSDMA_PAGE_RB_WPTR_POLL_ADDR_HI 0x010a
#define regSDMA_PAGE_RB_WPTR_POLL_ADDR_HI_BASE_IDX 0
#define regSDMA_PAGE_RB_WPTR_POLL_ADDR_LO 0x010b
#define regSDMA_PAGE_RB_WPTR_POLL_ADDR_LO_BASE_IDX 0
#define regSDMA_PAGE_MINOR_PTR_UPDATE 0x010d
#define regSDMA_PAGE_MINOR_PTR_UPDATE_BASE_IDX 0
#define regSDMA_RLC0_RB_CNTL 0x0130
#define regSDMA_RLC0_RB_CNTL_BASE_IDX 0
#define regSDMA_RLC0_RB_BASE 0x0131
#define regSDMA_RLC0_RB_BASE_BASE_IDX 0
#define regSDMA_RLC0_RB_BASE_HI 0x0132
#define regSDMA_RLC0_RB_BASE_HI_BASE_IDX 0
#define regSDMA_RLC0_RB_RPTR 0x0133
#define regSDMA_RLC0_RB_RPTR_BASE_IDX 0
#define regSDMA_RLC0_RB_RPTR_HI 0x0134
#define regSDMA_RLC0_RB_RPTR_HI_BASE_IDX 0
#define regSDMA_RLC0_RB_WPTR 0x0135
#define regSDMA_RLC0_RB_WPTR_BASE_IDX 0
#define regSDMA_RLC0_RB_WPTR_HI 0x0136
#define regSDMA_RLC0_RB_WPTR_HI_BASE_IDX 0
#define regSDMA_RLC0_RB_RPTR_ADDR_HI 0x0138
#define regSDMA_RLC0_RB_RPTR_ADDR_HI_BASE_IDX 0
#define regSDMA_RLC0_RB_RPTR_ADDR_LO 0x0139
#define regSDMA_RLC0_RB_RPTR_ADDR_LO_BASE_IDX 0
#define regSDMA_RLC0_IB_OFFSET 0x013c
#define regSDMA_RLC0_IB_OFFSET_BASE_IDX 0
#define regSDMA_RLC0_IB_BASE_LO 0x013d
#define regSDMA_RLC0_IB_BASE_LO_BASE_IDX 0
#define regSDMA_RLC0_IB_BASE_HI 0x013e
#define regSDMA_RLC0_IB_BASE_HI_BASE_IDX 0
#define regSDMA_RLC0_CONTEXT_STATUS 0x0141
#define regSDMA_RLC0_CONTEXT_STATUS_BASE_IDX 0
#define regSDMA_RLC0_DOORBELL 0x0142
#define regSDMA_RLC0_DOORBELL_BASE_IDX 0
#define regSDMA_RLC0_STATUS 0x0158
#define regSDMA_RLC0_STATUS_BASE_IDX 0
#define regSDMA_RLC0_DOORBELL_OFFSET 0x015b
#define regSDMA_RLC0_DOORBELL_OFFSET_BASE_IDX 0
#define regSDMA_RLC0_CSA_ADDR_HI 0x015d
#define regSDMA_RLC0_CSA_ADDR_HI_BASE_IDX 0
#define regSDMA_RLC0_IB_SUB_REMAIN 0x015f
#define regSDMA_RLC0_IB_SUB_REMAIN_BASE_IDX 0
#define regSDMA_RLC0_DUMMY_REG 0x0161
#define regSDMA_RLC0_DUMMY_REG_BASE_IDX 0
#define regSDMA_RLC0_MINOR_PTR_UPDATE 0x0165
#define regSDMA_RLC0_MINOR_PTR_UPDATE_BASE_IDX 0
#define regSDMA_RLC0_MIDCMD_DATA0 0x0170
#define regSDMA_RLC0_MIDCMD_DATA0_BASE_IDX 0
#define regSDMA_RLC0_MIDCMD_CNTL 0x017b
#define regSDMA_RLC0_MIDCMD_CNTL_BASE_IDX 0
#define regSDMA_RLC1_RB_CNTL 0x0188
#define regSDMA_RLC1_RB_CNTL_BASE_IDX 0
#endif
