/*
 * Copyright 2021 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _sdma_4_4_2_SH_MASK_HEADER
#define _sdma_4_4_2_SH_MASK_HEADER

//SDMA_F32_CNTL
#define SDMA_F32_CNTL__HALT__SHIFT 0x0
#define SDMA_F32_CNTL__HALT_MASK 0x00000001L
//SDMA_STATUS_REG
#define SDMA_STATUS_REG__IDLE__SHIFT 0x0
#define SDMA_STATUS_REG__IDLE_MASK 0x00000001L
//SDMA_PHASE0_QUANTUM
#define SDMA_PHASE0_QUANTUM__UNIT__SHIFT 0x0
#define SDMA_PHASE0_QUANTUM__VALUE__SHIFT 0x8
#define SDMA_PHASE0_QUANTUM__UNIT_MASK 0x0000000FL
#define SDMA_PHASE0_QUANTUM__VALUE_MASK 0x00FFFF00L
//SDMA_POWER_CNTL
#define SDMA_POWER_CNTL__MEM_POWER_OVERRIDE__SHIFT 0x8
#define SDMA_POWER_CNTL__MEM_POWER_OVERRIDE_MASK 0x00000100L
//SDMA_CLK_CTRL
#define SDMA_CLK_CTRL__SOFT_OVERRIDE5__SHIFT 0x1a
#define SDMA_CLK_CTRL__SOFT_OVERRIDE4__SHIFT 0x1b
#define SDMA_CLK_CTRL__SOFT_OVERRIDE3__SHIFT 0x1c
#define SDMA_CLK_CTRL__SOFT_OVERRIDE2__SHIFT 0x1d
#define SDMA_CLK_CTRL__SOFT_OVERRIDE1__SHIFT 0x1e
#define SDMA_CLK_CTRL__SOFT_OVERRIDE0__SHIFT 0x1f
#define SDMA_CLK_CTRL__SOFT_OVERRIDE5_MASK 0x04000000L
#define SDMA_CLK_CTRL__SOFT_OVERRIDE4_MASK 0x08000000L
#define SDMA_CLK_CTRL__SOFT_OVERRIDE3_MASK 0x10000000L
#define SDMA_CLK_CTRL__SOFT_OVERRIDE2_MASK 0x20000000L
#define SDMA_CLK_CTRL__SOFT_OVERRIDE1_MASK 0x40000000L
#define SDMA_CLK_CTRL__SOFT_OVERRIDE0_MASK 0x80000000L
//SDMA_CNTL
#define SDMA_CNTL__TRAP_ENABLE__SHIFT 0x0
#define SDMA_CNTL__UTC_L1_ENABLE__SHIFT 0x1
#define SDMA_CNTL__DRAM_ECC_INT_ENABLE__SHIFT 0xa
#define SDMA_CNTL__AUTO_CTXSW_ENABLE__SHIFT 0x12
#define SDMA_CNTL__CTXEMPTY_INT_ENABLE__SHIFT 0x1c
#define SDMA_CNTL__TRAP_ENABLE_MASK 0x00000001L
#define SDMA_CNTL__UTC_L1_ENABLE_MASK 0x00000002L
#define SDMA_CNTL__DRAM_ECC_INT_ENABLE_MASK 0x00000400L
#define SDMA_CNTL__AUTO_CTXSW_ENABLE_MASK 0x00040000L
#define SDMA_CNTL__CTXEMPTY_INT_ENABLE_MASK 0x10000000L
//SDMA_GB_ADDR_CONFIG
#define SDMA_GB_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE__SHIFT 0x3
#define SDMA_GB_ADDR_CONFIG__NUM_BANKS__SHIFT 0xc
#define SDMA_GB_ADDR_CONFIG__PIPE_INTERLEAVE_SIZE_MASK 0x00000038L
#define SDMA_GB_ADDR_CONFIG__NUM_BANKS_MASK 0x00007000L
//SDMA_GB_ADDR_CONFIG_READ
#define SDMA_GB_ADDR_CONFIG_READ__PIPE_INTERLEAVE_SIZE__SHIFT 0x3
#define SDMA_GB_ADDR_CONFIG_READ__NUM_BANKS__SHIFT 0xc
#define SDMA_GB_ADDR_CONFIG_READ__PIPE_INTERLEAVE_SIZE_MASK 0x00000038L
#define SDMA_GB_ADDR_CONFIG_READ__NUM_BANKS_MASK 0x00007000L
//SDMA_GFX_RB_CNTL
#define SDMA_GFX_RB_CNTL__RB_ENABLE__SHIFT 0x0
#define SDMA_GFX_RB_CNTL__RB_SIZE__SHIFT 0x1
#define SDMA_GFX_RB_CNTL__RB_SWAP_ENABLE__SHIFT 0x9
#define SDMA_GFX_RB_CNTL__RPTR_WRITEBACK_ENABLE__SHIFT 0xc
#define SDMA_GFX_RB_CNTL__RPTR_WRITEBACK_SWAP_ENABLE__SHIFT 0xd
#define SDMA_GFX_RB_CNTL__RB_ENABLE_MASK 0x00000001L
#define SDMA_GFX_RB_CNTL__RB_SIZE_MASK 0x0000003EL
#define SDMA_GFX_RB_CNTL__RB_SWAP_ENABLE_MASK 0x00000200L
#define SDMA_GFX_RB_CNTL__RPTR_WRITEBACK_ENABLE_MASK 0x00001000L
#define SDMA_GFX_RB_CNTL__RPTR_WRITEBACK_SWAP_ENABLE_MASK 0x00002000L
//SDMA_GFX_RB_WPTR_POLL_CNTL
#define SDMA_GFX_RB_WPTR_POLL_CNTL__F32_POLL_ENABLE__SHIFT 0x2
#define SDMA_GFX_RB_WPTR_POLL_CNTL__F32_POLL_ENABLE_MASK 0x00000004L
//SDMA_GFX_IB_CNTL
#define SDMA_GFX_IB_CNTL__IB_ENABLE__SHIFT 0x0
#define SDMA_GFX_IB_CNTL__IB_SWAP_ENABLE__SHIFT 0x4
#define SDMA_GFX_IB_CNTL__IB_ENABLE_MASK 0x00000001L
#define SDMA_GFX_IB_CNTL__IB_SWAP_ENABLE_MASK 0x00000010L
//SDMA_GFX_CONTEXT_STATUS
#define SDMA_GFX_CONTEXT_STATUS__SELECTED__SHIFT 0x0
#define SDMA_GFX_CONTEXT_STATUS__SELECTED_MASK 0x00000001L
//SDMA_GFX_DOORBELL
#define SDMA_GFX_DOORBELL__ENABLE__SHIFT 0x1c
#define SDMA_GFX_DOORBELL__ENABLE_MASK 0x10000000L
//SDMA_GFX_DOORBELL_OFFSET
#define SDMA_GFX_DOORBELL_OFFSET__OFFSET__SHIFT 0x2
#define SDMA_GFX_DOORBELL_OFFSET__OFFSET_MASK 0x0FFFFFFCL
//SDMA_PAGE_RB_CNTL
#define SDMA_PAGE_RB_CNTL__RB_ENABLE__SHIFT 0x0
#define SDMA_PAGE_RB_CNTL__RPTR_WRITEBACK_ENABLE__SHIFT 0xc
#define SDMA_PAGE_RB_CNTL__RB_ENABLE_MASK 0x00000001L
#define SDMA_PAGE_RB_CNTL__RPTR_WRITEBACK_ENABLE_MASK 0x00001000L
//SDMA_PAGE_RB_WPTR_POLL_CNTL
#define SDMA_PAGE_RB_WPTR_POLL_CNTL__F32_POLL_ENABLE__SHIFT 0x2
#define SDMA_PAGE_RB_WPTR_POLL_CNTL__F32_POLL_ENABLE_MASK 0x00000004L
//SDMA_PAGE_IB_CNTL
#define SDMA_PAGE_IB_CNTL__IB_ENABLE__SHIFT 0x0
#define SDMA_PAGE_IB_CNTL__IB_SWAP_ENABLE__SHIFT 0x4
#define SDMA_PAGE_IB_CNTL__IB_ENABLE_MASK 0x00000001L
#define SDMA_PAGE_IB_CNTL__IB_SWAP_ENABLE_MASK 0x00000010L
//SDMA_PAGE_DOORBELL
#define SDMA_PAGE_DOORBELL__ENABLE__SHIFT 0x1c
#define SDMA_PAGE_DOORBELL__ENABLE_MASK 0x10000000L
//SDMA_PAGE_DOORBELL_OFFSET
#define SDMA_PAGE_DOORBELL_OFFSET__OFFSET__SHIFT 0x2
#define SDMA_PAGE_DOORBELL_OFFSET__OFFSET_MASK 0x0FFFFFFCL
//SDMA_RLC0_RB_CNTL
#define SDMA_RLC0_RB_CNTL__RB_ENABLE__SHIFT 0x0
#define SDMA_RLC0_RB_CNTL__RB_ENABLE_MASK 0x00000001L
//SDMA_RLC0_CONTEXT_STATUS
#define SDMA_RLC0_CONTEXT_STATUS__SELECTED__SHIFT 0x0
#define SDMA_RLC0_CONTEXT_STATUS__IDLE__SHIFT 0x2
#define SDMA_RLC0_CONTEXT_STATUS__SELECTED_MASK 0x00000001L
#define SDMA_RLC0_CONTEXT_STATUS__IDLE_MASK 0x00000004L
//SDMA_RLC0_DOORBELL
#define SDMA_RLC0_DOORBELL__ENABLE__SHIFT 0x1c
#define SDMA_RLC0_DOORBELL__ENABLE_MASK 0x10000000L
#endif
