/*
 *
 * Copyright (C) 2016 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef GMC_6_0_D_H
#define GMC_6_0_D_H

#define ixMC_IO_DEBUG_UP_13 0x000D
#define ixMC_IO_DEBUG_UP_159 0x009F
#define mmATC_MISC_CG 0x0CD4
#define mmATC_VMID0_PASID_MAPPING 0x0CE7
#define mmATC_VMID_PASID_MAPPING_UPDATE_STATUS 0x0CE6
#define mmDLL_CNTL 0x0AE9
#define mmGMCON_DEBUG 0x0D5F
#define mmGMCON_MISC 0x0D43
#define mmGMCON_MISC2 0x0D44
#define mmGMCON_MISC3 0x0D51
#define mmGMCON_PGFSM_CONFIG 0x0D4E
#define mmGMCON_PGFSM_WRITE 0x0D4F
#define mmGMCON_RENG_EXECUTE 0x0D42
#define mmGMCON_RENG_RAM_DATA 0x0D41
#define mmGMCON_RENG_RAM_INDEX 0x0D40
#define mmMC_ARB_BURST_TIME 0x0A02
#define mmMC_ARB_DRAM_TIMING 0x09DD
#define mmMC_ARB_DRAM_TIMING_1 0x09FC
#define mmMC_ARB_DRAM_TIMING2 0x09DE
#define mmMC_ARB_DRAM_TIMING2_1 0x09FF
#define mmMC_ARB_RAMCFG 0x09D8
#define mmMC_ARB_RFSH_RATE 0x09EC
#define mmMC_ARB_WTM_CNTL_RD 0x09DF
#define mmMC_ARB_WTM_GRPWT_RD 0x09E1
#define mmMC_CG_CONFIG 0x096F
#define mmMC_CITF_MISC_RD_CG 0x0992
#define mmMC_CITF_MISC_VM_CG 0x0994
#define mmMC_CITF_MISC_WR_CG 0x0993
#define mmMC_HUB_MISC_HUB_CG 0x082E
#define mmMC_HUB_MISC_SIP_CG 0x0830
#define mmMC_HUB_MISC_VM_CG 0x082F
#define mmMC_HUB_RDREQ_DMIF_LIMIT 0x0848
#define mmMC_HUB_RDREQ_UVD 0x0861
#define mmMC_HUB_WDP_UMC 0x0877
#define mmMC_IO_RXCNTL_DPHY0_D0 0x0A4C
#define mmMC_IO_RXCNTL_DPHY0_D1 0x0A52
#define mmMC_IO_RXCNTL_DPHY1_D0 0x0A4D
#define mmMC_IO_RXCNTL_DPHY1_D1 0x0A53
#define mmMCLK_PWRMGT_CNTL 0x0AE8
#define mmMC_MEM_POWER_LS 0x082A
#define mmMC_PMG_AUTO_CFG 0x0A35
#define mmMC_PMG_AUTO_CMD 0x0A34
#define mmMC_PMG_CMD_EMRS 0x0A83
#define mmMC_PMG_CMD_MRS 0x0AAB
#define mmMC_PMG_CMD_MRS1 0x0AD1
#define mmMC_PMG_CMD_MRS2 0x0AD7
#define mmMC_RD_GRP_OTH 0x0807
#define mmMC_SEQ_CAS_TIMING 0x0A29
#define mmMC_SEQ_CAS_TIMING_LP 0x0A9C
#define mmMC_SEQ_CNTL_2 0x0AD4
#define mmMC_SEQ_DRAM 0x0A26
#define mmMC_SEQ_IO_DEBUG_DATA 0x0A92
#define mmMC_SEQ_IO_DEBUG_INDEX 0x0A91
#define mmMC_SEQ_MISC0 0x0A80
#define mmMC_SEQ_MISC1 0x0A81
#define mmMC_SEQ_MISC5 0x0A95
#define mmMC_SEQ_MISC6 0x0A96
#define mmMC_SEQ_MISC7 0x0A99
#define mmMC_SEQ_MISC_TIMING 0x0A2A
#define mmMC_SEQ_MISC_TIMING2 0x0A2B
#define mmMC_SEQ_MISC_TIMING2_LP 0x0A9E
#define mmMC_SEQ_MISC_TIMING_LP 0x0A9D
#define mmMC_SEQ_PMG_CMD_EMRS_LP 0x0AA1
#define mmMC_SEQ_PMG_CMD_MRS1_LP 0x0AD2
#define mmMC_SEQ_PMG_CMD_MRS2_LP 0x0AD8
#define mmMC_SEQ_PMG_CMD_MRS_LP 0x0AA2
#define mmMC_SEQ_PMG_PG_HWCNTL 0x0AB9
#define mmMC_SEQ_PMG_TIMING 0x0A2C
#define mmMC_SEQ_PMG_TIMING_LP 0x0AD3
#define mmMC_SEQ_RAS_TIMING 0x0A28
#define mmMC_SEQ_RAS_TIMING_LP 0x0A9B
#define mmMC_SEQ_RD_CTL_D0 0x0A2D
#define mmMC_SEQ_RD_CTL_D0_LP 0x0AC7
#define mmMC_SEQ_RD_CTL_D1 0x0A2E
#define mmMC_SEQ_RD_CTL_D1_LP 0x0AC8
#define mmMC_SEQ_RESERVE_M 0x0A82
#define mmMC_SEQ_SUP_CNTL 0x0A32
#define mmMC_SEQ_SUP_PGM 0x0A33
#define mmMC_SEQ_TRAIN_WAKEUP_CNTL 0x0A3A
#define mmMC_SEQ_WR_CTL_2 0x0AD5
#define mmMC_SEQ_WR_CTL_2_LP 0x0AD6
#define mmMC_SEQ_WR_CTL_D0 0x0A2F
#define mmMC_SEQ_WR_CTL_D0_LP 0x0A9F
#define mmMC_SEQ_WR_CTL_D1 0x0A30
#define mmMC_SEQ_WR_CTL_D1_LP 0x0AA0
#define mmMC_SHARED_BLACKOUT_CNTL 0x082B
#define mmMC_SHARED_CHMAP 0x0801
#define mmMC_VM_AGP_BASE 0x080C
#define mmMC_VM_AGP_BOT 0x080B
#define mmMC_VM_AGP_TOP 0x080A
#define mmMC_VM_FB_LOCATION 0x0809
#define mmMC_VM_FB_OFFSET 0x081A
#define mmMC_VM_MX_L1_TLB_CNTL 0x0819
#define mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR 0x080F
#define mmMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x080E
#define mmMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x080D
#define mmMC_XPB_CLK_GAT 0x091E
#define mmMC_XPB_P2P_BAR_CFG 0x0903
#define mmMPLL_AD_FUNC_CNTL 0x0AF0
#define mmMPLL_CNTL_MODE 0x0AEC
#define mmMPLL_CONTROL 0x0AF5
#define mmMPLL_DQ_FUNC_CNTL 0x0AF1
#define mmMPLL_FUNC_CNTL 0x0AED
#define mmMPLL_FUNC_CNTL_1 0x0AEE
#define mmMPLL_FUNC_CNTL_2 0x0AEF
#define mmMPLL_SS1 0x0AF3
#define mmMPLL_SS2 0x0AF4
#define mmVM_CONTEXT0_CNTL 0x0504
#define mmVM_CONTEXT0_CNTL2 0x050C
#define mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR 0x054F
#define mmVM_CONTEXT0_PAGE_TABLE_END_ADDR 0x055F
#define mmVM_CONTEXT0_PAGE_TABLE_START_ADDR 0x0557
#define mmVM_CONTEXT0_PROTECTION_FAULT_DEFAULT_ADDR 0x0546
#define mmVM_CONTEXT1_CNTL 0x0505
#define mmVM_CONTEXT1_CNTL2 0x050D
#define mmVM_CONTEXT1_PAGE_TABLE_END_ADDR 0x0560
#define mmVM_CONTEXT1_PAGE_TABLE_START_ADDR 0x0558
#define mmVM_CONTEXT1_PROTECTION_FAULT_ADDR 0x053F
#define mmVM_CONTEXT1_PROTECTION_FAULT_DEFAULT_ADDR 0x0547
#define mmVM_CONTEXT1_PROTECTION_FAULT_STATUS 0x0537
#define mmVM_CONTEXT8_PAGE_TABLE_BASE_ADDR 0x050E
#define mmVM_INVALIDATE_REQUEST 0x051E
#define mmVM_INVALIDATE_RESPONSE 0x051F
#define mmVM_L2_CG 0x0570
#define mmVM_L2_CNTL 0x0500
#define mmVM_L2_CNTL2 0x0501
#define mmVM_L2_CNTL3 0x0502
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR 0x0576
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR 0x0575
#define mmVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET 0x0577
#define mmVM_PRT_APERTURE0_HIGH_ADDR 0x0530
#define mmVM_PRT_APERTURE0_LOW_ADDR 0x052C
#define mmVM_PRT_APERTURE1_HIGH_ADDR 0x0531
#define mmVM_PRT_APERTURE1_LOW_ADDR 0x052D
#define mmVM_PRT_APERTURE2_HIGH_ADDR 0x0532
#define mmVM_PRT_APERTURE2_LOW_ADDR 0x052E
#define mmVM_PRT_APERTURE3_HIGH_ADDR 0x0533
#define mmVM_PRT_APERTURE3_LOW_ADDR 0x052F
#define mmVM_PRT_CNTL 0x0534
#endif
