/*
 * UVD_3_1 Register documentation
 *
 * Copyright (C) 2020  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef UVD_3_1_SH_MASK_H
#define UVD_3_1_SH_MASK_H

#define UVD_CGC_GATE__SYS_MASK 0x1
#define UVD_CGC_GATE__SYS__SHIFT 0x0
#define UVD_CGC_GATE__UDEC_MASK 0x2
#define UVD_CGC_GATE__UDEC__SHIFT 0x1
#define UVD_CGC_GATE__MPEG2_MASK 0x4
#define UVD_CGC_GATE__MPEG2__SHIFT 0x2
#define UVD_CGC_GATE__REGS_MASK 0x8
#define UVD_CGC_GATE__REGS__SHIFT 0x3
#define UVD_CGC_GATE__RBC_MASK 0x10
#define UVD_CGC_GATE__RBC__SHIFT 0x4
#define UVD_CGC_GATE__LMI_MC_MASK 0x20
#define UVD_CGC_GATE__LMI_MC__SHIFT 0x5
#define UVD_CGC_GATE__LMI_UMC_MASK 0x40
#define UVD_CGC_GATE__LMI_UMC__SHIFT 0x6
#define UVD_CGC_GATE__IDCT_MASK 0x80
#define UVD_CGC_GATE__IDCT__SHIFT 0x7
#define UVD_CGC_GATE__MPRD_MASK 0x100
#define UVD_CGC_GATE__MPRD__SHIFT 0x8
#define UVD_CGC_GATE__MPC_MASK 0x200
#define UVD_CGC_GATE__MPC__SHIFT 0x9
#define UVD_CGC_GATE__LBSI_MASK 0x400
#define UVD_CGC_GATE__LBSI__SHIFT 0xa
#define UVD_CGC_GATE__LRBBM_MASK 0x800
#define UVD_CGC_GATE__LRBBM__SHIFT 0xb
#define UVD_CGC_GATE__UDEC_RE_MASK 0x1000
#define UVD_CGC_GATE__UDEC_RE__SHIFT 0xc
#define UVD_CGC_GATE__UDEC_CM_MASK 0x2000
#define UVD_CGC_GATE__UDEC_CM__SHIFT 0xd
#define UVD_CGC_GATE__UDEC_IT_MASK 0x4000
#define UVD_CGC_GATE__UDEC_IT__SHIFT 0xe
#define UVD_CGC_GATE__UDEC_DB_MASK 0x8000
#define UVD_CGC_GATE__UDEC_DB__SHIFT 0xf
#define UVD_CGC_GATE__UDEC_MP_MASK 0x10000
#define UVD_CGC_GATE__UDEC_MP__SHIFT 0x10
#define UVD_CGC_GATE__WCB_MASK 0x20000
#define UVD_CGC_GATE__WCB__SHIFT 0x11
#define UVD_CGC_GATE__VCPU_MASK 0x40000
#define UVD_CGC_GATE__VCPU__SHIFT 0x12
#define UVD_CGC_GATE__SCPU_MASK 0x80000
#define UVD_CGC_GATE__SCPU__SHIFT 0x13
#define UVD_CGC_CTRL__DYN_CLOCK_MODE_MASK 0x1
#define UVD_CGC_CTRL__DYN_CLOCK_MODE__SHIFT 0x0
#define UVD_CGC_CTRL__CLK_GATE_DLY_TIMER_MASK 0x3c
#define UVD_CGC_CTRL__CLK_GATE_DLY_TIMER__SHIFT 0x2
#define UVD_CGC_CTRL__CLK_OFF_DELAY_MASK 0x7c0
#define UVD_CGC_CTRL__CLK_OFF_DELAY__SHIFT 0x6
#define UVD_CGC_CTRL__UDEC_RE_MODE_MASK 0x800
#define UVD_CGC_CTRL__UDEC_RE_MODE__SHIFT 0xb
#define UVD_CGC_CTRL__UDEC_CM_MODE_MASK 0x1000
#define UVD_CGC_CTRL__UDEC_CM_MODE__SHIFT 0xc
#define UVD_CGC_CTRL__UDEC_IT_MODE_MASK 0x2000
#define UVD_CGC_CTRL__UDEC_IT_MODE__SHIFT 0xd
#define UVD_CGC_CTRL__UDEC_DB_MODE_MASK 0x4000
#define UVD_CGC_CTRL__UDEC_DB_MODE__SHIFT 0xe
#define UVD_CGC_CTRL__UDEC_MP_MODE_MASK 0x8000
#define UVD_CGC_CTRL__UDEC_MP_MODE__SHIFT 0xf
#define UVD_CGC_CTRL__SYS_MODE_MASK 0x10000
#define UVD_CGC_CTRL__SYS_MODE__SHIFT 0x10
#define UVD_CGC_CTRL__UDEC_MODE_MASK 0x20000
#define UVD_CGC_CTRL__UDEC_MODE__SHIFT 0x11
#define UVD_CGC_CTRL__MPEG2_MODE_MASK 0x40000
#define UVD_CGC_CTRL__MPEG2_MODE__SHIFT 0x12
#define UVD_CGC_CTRL__REGS_MODE_MASK 0x80000
#define UVD_CGC_CTRL__REGS_MODE__SHIFT 0x13
#define UVD_CGC_CTRL__RBC_MODE_MASK 0x100000
#define UVD_CGC_CTRL__RBC_MODE__SHIFT 0x14
#define UVD_CGC_CTRL__LMI_MC_MODE_MASK 0x200000
#define UVD_CGC_CTRL__LMI_MC_MODE__SHIFT 0x15
#define UVD_CGC_CTRL__LMI_UMC_MODE_MASK 0x400000
#define UVD_CGC_CTRL__LMI_UMC_MODE__SHIFT 0x16
#define UVD_CGC_CTRL__IDCT_MODE_MASK 0x800000
#define UVD_CGC_CTRL__IDCT_MODE__SHIFT 0x17
#define UVD_CGC_CTRL__MPRD_MODE_MASK 0x1000000
#define UVD_CGC_CTRL__MPRD_MODE__SHIFT 0x18
#define UVD_CGC_CTRL__MPC_MODE_MASK 0x2000000
#define UVD_CGC_CTRL__MPC_MODE__SHIFT 0x19
#define UVD_CGC_CTRL__LBSI_MODE_MASK 0x4000000
#define UVD_CGC_CTRL__LBSI_MODE__SHIFT 0x1a
#define UVD_CGC_CTRL__LRBBM_MODE_MASK 0x8000000
#define UVD_CGC_CTRL__LRBBM_MODE__SHIFT 0x1b
#define UVD_CGC_CTRL__WCB_MODE_MASK 0x10000000
#define UVD_CGC_CTRL__WCB_MODE__SHIFT 0x1c
#define UVD_CGC_CTRL__VCPU_MODE_MASK 0x20000000
#define UVD_CGC_CTRL__VCPU_MODE__SHIFT 0x1d
#define UVD_CGC_CTRL__SCPU_MODE_MASK 0x40000000
#define UVD_CGC_CTRL__SCPU_MODE__SHIFT 0x1e
#define UVD_LMI_CTRL2__STALL_ARB_UMC_MASK 0x100
#define UVD_LMI_CTRL2__STALL_ARB_UMC__SHIFT 0x8
#define UVD_MASTINT_EN__VCPU_EN_MASK 0x2
#define UVD_MASTINT_EN__VCPU_EN__SHIFT 0x1
#define UVD_MASTINT_EN__SYS_EN_MASK 0x4
#define UVD_MASTINT_EN__SYS_EN__SHIFT 0x2
#define UVD_LMI_CTRL__WRITE_CLEAN_TIMER_MASK 0xff
#define UVD_LMI_CTRL__WRITE_CLEAN_TIMER__SHIFT 0x0
#define UVD_LMI_CTRL__WRITE_CLEAN_TIMER_EN_MASK 0x100
#define UVD_LMI_CTRL__WRITE_CLEAN_TIMER_EN__SHIFT 0x8
#define UVD_LMI_CTRL__REQ_MODE_MASK 0x200
#define UVD_LMI_CTRL__REQ_MODE__SHIFT 0x9
#define UVD_LMI_CTRL__MASK_MC_URGENT_MASK 0x1000
#define UVD_LMI_CTRL__MASK_MC_URGENT__SHIFT 0xc
#define UVD_LMI_CTRL__DATA_COHERENCY_EN_MASK 0x2000
#define UVD_LMI_CTRL__DATA_COHERENCY_EN__SHIFT 0xd
#define UVD_LMI_CTRL__CRC_RESET_MASK 0x4000
#define UVD_LMI_CTRL__CRC_RESET__SHIFT 0xe
#define UVD_LMI_CTRL__DISABLE_ON_FWV_FAIL_MASK 0x100000
#define UVD_LMI_CTRL__DISABLE_ON_FWV_FAIL__SHIFT 0x14
#define UVD_LMI_CTRL__VCPU_DATA_COHERENCY_EN_MASK 0x200000
#define UVD_LMI_CTRL__VCPU_DATA_COHERENCY_EN__SHIFT 0x15
#define UVD_LMI_STATUS__READ_CLEAN_MASK 0x1
#define UVD_LMI_STATUS__READ_CLEAN__SHIFT 0x0
#define UVD_LMI_STATUS__WRITE_CLEAN_MASK 0x2
#define UVD_LMI_STATUS__WRITE_CLEAN__SHIFT 0x1
#define UVD_LMI_STATUS__WRITE_CLEAN_RAW_MASK 0x4
#define UVD_LMI_STATUS__WRITE_CLEAN_RAW__SHIFT 0x2
#define UVD_LMI_STATUS__VCPU_LMI_WRITE_CLEAN_MASK 0x8
#define UVD_LMI_STATUS__VCPU_LMI_WRITE_CLEAN__SHIFT 0x3
#define UVD_LMI_STATUS__UMC_WRITE_CLEAN_RAW_MASK 0x40
#define UVD_LMI_STATUS__UMC_WRITE_CLEAN_RAW__SHIFT 0x6
#define UVD_LMI_STATUS__UMC_READ_CLEAN_RAW_MASK 0x200
#define UVD_LMI_STATUS__UMC_READ_CLEAN_RAW__SHIFT 0x9
#define UVD_MPC_CNTL__REPLACEMENT_MODE_MASK 0x38
#define UVD_MPC_CNTL__REPLACEMENT_MODE__SHIFT 0x3
#define UVD_MPC_SET_MUXA0__VARA_1_MASK 0xfc0
#define UVD_MPC_SET_MUXA0__VARA_1__SHIFT 0x6
#define UVD_MPC_SET_MUXA0__VARA_2_MASK 0x3f000
#define UVD_MPC_SET_MUXA0__VARA_2__SHIFT 0xc
#define UVD_MPC_SET_MUXA0__VARA_3_MASK 0xfc0000
#define UVD_MPC_SET_MUXA0__VARA_3__SHIFT 0x12
#define UVD_MPC_SET_MUXA0__VARA_4_MASK 0x3f000000
#define UVD_MPC_SET_MUXA0__VARA_4__SHIFT 0x18
#define UVD_MPC_SET_MUXB0__VARB_1_MASK 0xfc0
#define UVD_MPC_SET_MUXB0__VARB_1__SHIFT 0x6
#define UVD_MPC_SET_MUXB0__VARB_2_MASK 0x3f000
#define UVD_MPC_SET_MUXB0__VARB_2__SHIFT 0xc
#define UVD_MPC_SET_MUXB0__VARB_3_MASK 0xfc0000
#define UVD_MPC_SET_MUXB0__VARB_3__SHIFT 0x12
#define UVD_MPC_SET_MUXB0__VARB_4_MASK 0x3f000000
#define UVD_MPC_SET_MUXB0__VARB_4__SHIFT 0x18
#define UVD_MPC_SET_MUX__SET_0_MASK 0x7
#define UVD_MPC_SET_MUX__SET_0__SHIFT 0x0
#define UVD_MPC_SET_MUX__SET_1_MASK 0x38
#define UVD_MPC_SET_MUX__SET_1__SHIFT 0x3
#define UVD_MPC_SET_MUX__SET_2_MASK 0x1c0
#define UVD_MPC_SET_MUX__SET_2__SHIFT 0x6
#define UVD_VCPU_CNTL__CLK_EN_MASK 0x200
#define UVD_VCPU_CNTL__CLK_EN__SHIFT 0x9
#define UVD_VCPU_CNTL__PRB_TIMEOUT_VAL_MASK 0xff00000
#define UVD_VCPU_CNTL__PRB_TIMEOUT_VAL__SHIFT 0x14
#define UVD_SOFT_RESET__RBC_SOFT_RESET_MASK 0x1
#define UVD_SOFT_RESET__RBC_SOFT_RESET__SHIFT 0x0
#define UVD_SOFT_RESET__LBSI_SOFT_RESET_MASK 0x2
#define UVD_SOFT_RESET__LBSI_SOFT_RESET__SHIFT 0x1
#define UVD_SOFT_RESET__LMI_SOFT_RESET_MASK 0x4
#define UVD_SOFT_RESET__LMI_SOFT_RESET__SHIFT 0x2
#define UVD_SOFT_RESET__VCPU_SOFT_RESET_MASK 0x8
#define UVD_SOFT_RESET__VCPU_SOFT_RESET__SHIFT 0x3
#define UVD_SOFT_RESET__CSM_SOFT_RESET_MASK 0x20
#define UVD_SOFT_RESET__CSM_SOFT_RESET__SHIFT 0x5
#define UVD_SOFT_RESET__CXW_SOFT_RESET_MASK 0x40
#define UVD_SOFT_RESET__CXW_SOFT_RESET__SHIFT 0x6
#define UVD_SOFT_RESET__TAP_SOFT_RESET_MASK 0x80
#define UVD_SOFT_RESET__TAP_SOFT_RESET__SHIFT 0x7
#define UVD_SOFT_RESET__LMI_UMC_SOFT_RESET_MASK 0x2000
#define UVD_SOFT_RESET__LMI_UMC_SOFT_RESET__SHIFT 0xd
#define UVD_RBC_RB_CNTL__RB_BUFSZ_MASK 0x1f
#define UVD_RBC_RB_CNTL__RB_BUFSZ__SHIFT 0x0
#define UVD_RBC_RB_CNTL__RB_BLKSZ_MASK 0x1f00
#define UVD_RBC_RB_CNTL__RB_BLKSZ__SHIFT 0x8
#define UVD_RBC_RB_CNTL__RB_NO_FETCH_MASK 0x10000
#define UVD_RBC_RB_CNTL__RB_NO_FETCH__SHIFT 0x10
#define UVD_RBC_RB_CNTL__RB_WPTR_POLL_EN_MASK 0x100000
#define UVD_RBC_RB_CNTL__RB_WPTR_POLL_EN__SHIFT 0x14
#define UVD_RBC_RB_CNTL__RB_NO_UPDATE_MASK 0x1000000
#define UVD_RBC_RB_CNTL__RB_NO_UPDATE__SHIFT 0x18
#define UVD_RBC_RB_CNTL__RB_RPTR_WR_EN_MASK 0x10000000
#define UVD_RBC_RB_CNTL__RB_RPTR_WR_EN__SHIFT 0x1c
#define UVD_STATUS__VCPU_REPORT_MASK 0xfe
#define UVD_STATUS__VCPU_REPORT__SHIFT 0x1
#define UVD_CGC_CTRL2__DYN_OCLK_RAMP_EN_MASK 0x1
#define UVD_CGC_CTRL2__DYN_OCLK_RAMP_EN__SHIFT 0x0
#define UVD_CGC_CTRL2__DYN_RCLK_RAMP_EN_MASK 0x2
#define UVD_CGC_CTRL2__DYN_RCLK_RAMP_EN__SHIFT 0x1
#define UVD_CGC_CTRL2__GATER_DIV_ID_MASK 0x1c
#define UVD_CGC_CTRL2__GATER_DIV_ID__SHIFT 0x2
#define UVD_PGFSM_CONFIG__UVD_PGFSM_FSM_ADDR_MASK 0xff
#define UVD_PGFSM_CONFIG__UVD_PGFSM_FSM_ADDR__SHIFT 0x0
#define UVD_PGFSM_CONFIG__UVD_PGFSM_POWER_DOWN_MASK 0x100
#define UVD_PGFSM_CONFIG__UVD_PGFSM_POWER_DOWN__SHIFT 0x8
#define UVD_PGFSM_CONFIG__UVD_PGFSM_POWER_UP_MASK 0x200
#define UVD_PGFSM_CONFIG__UVD_PGFSM_POWER_UP__SHIFT 0x9
#define UVD_PGFSM_CONFIG__UVD_PGFSM_P1_SELECT_MASK 0x400
#define UVD_PGFSM_CONFIG__UVD_PGFSM_P1_SELECT__SHIFT 0xa
#define UVD_POWER_STATUS__UVD_POWER_STATUS_MASK 0x1
#define UVD_POWER_STATUS__UVD_POWER_STATUS__SHIFT 0x0
// UVD_FW_STATUS
#define UVD_FW_STATUS__BUSY_MASK 0x00000001L
#define UVD_FW_STATUS__DONE_MASK 0x00000100L
#define UVD_FW_STATUS__PASS_MASK 0x00010000L
#endif /* UVD_3_1_SH_MASK_H */
