/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rnusers.h"
bool_t xdr_utmp(XDR *, struct ru_utmp *);
bool_t xdr_utmpptr(XDR *, struct ru_utmp **);
bool_t xdr_utmparr(XDR *, struct utmparr *);
bool_t xdr_utmpidle(XDR *, struct utmpidle *);
bool_t xdr_utmpidleptr(XDR *, struct utmpidle **);

bool_t
xdr_utmp(XDR *xdrs, struct ru_utmp *objp)
{
 int size;

 size = RNUSERS_MAXLINELEN;
 if (!xdr_bytes(xdrs, &objp->ut_line, &size, RNUSERS_MAXLINELEN))
 return (FALSE);
 size = RNUSERS_MAXUSERLEN;
 if (!xdr_bytes(xdrs, &objp->ut_name, &size, RNUSERS_MAXUSERLEN))
 return (FALSE);
 size = RNUSERS_MAXHOSTLEN;
 if (!xdr_bytes(xdrs, &objp->ut_host, &size, RNUSERS_MAXHOSTLEN))
 return (FALSE);
 if (!xdr_int(xdrs, &objp->ut_time))
 return (FALSE);
 return (TRUE);
}

bool_t
xdr_utmpptr(XDR *xdrs, struct ru_utmp **objpp)
{
 if (!xdr_reference(xdrs, (char **) objpp, sizeof (struct ru_utmp),
 xdr_utmp))
 return (FALSE);
 return (TRUE);
}

bool_t
xdr_utmparr(XDR *xdrs, struct utmparr *objp)
{
 if (!xdr_array(xdrs, (char **)&objp->uta_arr, (u_int *)&objp->uta_cnt,
 MAXUSERS, sizeof(struct ru_utmp *), xdr_utmpptr))
 return (FALSE);
 return (TRUE);
}

bool_t
xdr_utmpidle(XDR *xdrs, struct utmpidle *objp)
{
 if (!xdr_utmp(xdrs, &objp->ui_utmp))
 return (FALSE);
 if (!xdr_u_int(xdrs, &objp->ui_idle))
 return (FALSE);
 return (TRUE);
}

bool_t
xdr_utmpidleptr(XDR *xdrs, struct utmpidle **objpp)
{
 if (!xdr_reference(xdrs, (char **) objpp, sizeof (struct utmpidle),
 xdr_utmpidle))
 return (FALSE);
 return (TRUE);
}

bool_t
xdr_utmpidlearr(XDR *xdrs, struct utmpidlearr *objp)
{
 if (!xdr_array(xdrs, (char **)&objp->uia_arr, (u_int *)&objp->uia_cnt,
 MAXUSERS, sizeof(struct utmpidle *), xdr_utmpidleptr))
 return (FALSE);
 return (TRUE);
}
