/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RWALL_H_RPCGEN
#define _RWALL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define WALLPROG 100008
#define WALLVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define WALLPROC_WALL 2
extern  void * wallproc_wall_1(char **, CLIENT *);
extern  void * wallproc_wall_1_svc(char **, struct svc_req *);
extern int wallprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WALLPROC_WALL 2
extern  void * wallproc_wall_1();
extern  void * wallproc_wall_1_svc();
extern int wallprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RWALL_H_RPCGEN */
