/*
 * Copyright 2023 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _vpe_6_1_0_SH_MASK_HEADER
#define _vpe_6_1_0_SH_MASK_HEADER

//VPEC_F32_CNTL
#define VPEC_F32_CNTL__HALT__SHIFT 0x0
#define VPEC_F32_CNTL__TH1_RESET__SHIFT 0xd
#define VPEC_F32_CNTL__HALT_MASK 0x00000001L
#define VPEC_F32_CNTL__TH1_RESET_MASK 0x00002000L
//VPEC_CNTL
#define VPEC_CNTL__TRAP_ENABLE__SHIFT 0x0
#define VPEC_CNTL__UMSCH_INT_ENABLE__SHIFT 0xa
#define VPEC_CNTL__TRAP_ENABLE_MASK 0x00000001L
#define VPEC_CNTL__UMSCH_INT_ENABLE_MASK 0x00000400L
//VPEC_QUEUE_RESET_REQ
#define VPEC_QUEUE_RESET_REQ__QUEUE0_RESET__SHIFT 0x0
#define VPEC_QUEUE_RESET_REQ__QUEUE0_RESET_MASK 0x00000001L
//VPEC_QUEUE0_RB_CNTL
#define VPEC_QUEUE0_RB_CNTL__RB_ENABLE__SHIFT 0x0
#define VPEC_QUEUE0_RB_CNTL__RB_SIZE__SHIFT 0x1
#define VPEC_QUEUE0_RB_CNTL__RPTR_WRITEBACK_ENABLE__SHIFT 0xc
#define VPEC_QUEUE0_RB_CNTL__RB_PRIV__SHIFT 0x17
#define VPEC_QUEUE0_RB_CNTL__RB_VMID__SHIFT 0x18
#define VPEC_QUEUE0_RB_CNTL__RB_ENABLE_MASK 0x00000001L
#define VPEC_QUEUE0_RB_CNTL__RB_SIZE_MASK 0x0000003EL
#define VPEC_QUEUE0_RB_CNTL__RPTR_WRITEBACK_ENABLE_MASK 0x00001000L
#define VPEC_QUEUE0_RB_CNTL__RB_PRIV_MASK 0x00800000L
#define VPEC_QUEUE0_RB_CNTL__RB_VMID_MASK 0x0F000000L
//VPEC_QUEUE0_DOORBELL
#define VPEC_QUEUE0_DOORBELL__ENABLE__SHIFT 0x1c
#define VPEC_QUEUE0_DOORBELL__ENABLE_MASK 0x10000000L
//VPEC_QUEUE0_DOORBELL_OFFSET
#define VPEC_QUEUE0_DOORBELL_OFFSET__OFFSET__SHIFT 0x2
#define VPEC_QUEUE0_DOORBELL_OFFSET__OFFSET_MASK 0x0FFFFFFCL
//VPEC_QUEUE0_IB_CNTL
#define VPEC_QUEUE0_IB_CNTL__IB_ENABLE__SHIFT 0x0
#define VPEC_QUEUE0_IB_CNTL__IB_ENABLE_MASK 0x00000001L
#endif
