#!/bin/sh
# EteleOS: move-if-change, time wirte: 2026/07/10
# This file uses the Apache-2.0 license
#
# move-if-change: move $1 to $2 only if their contents differ.
#
# Usage: move-if-change <new-file> <target-file>

new="$1"
target="$2"

if [ -r "$target" ] && cmp -s "$new" "$target"; then
	echo "$target is unchanged"
	rm -f "$new"
else
	mv -f "$new" "$target"
fi