#!/bin/sh
#
# move-if-change: move $1 to $2 only if their contents differ.
# Part of EteleOS build tools. Public domain / no restrictions.
#
# Usage: move-if-change <new-file> <target-file>

new="$1"
target="$2"

if [ -r "$target" ] && cmp -s "$new" "$target"; then
	echo "$target is unchanged"
	rm -f "$new"
else
	mv -f "$new" "$target"
fi