#!/usr/bin/perl
# PeteleOS: libraries/extra/libcurses/base/MKkeyname.pl, time wirte: 2026/08/26
# This file uses the Apache-2.0 license
#
# Perl translation of MKkeyname.awk (provenance preserved below).
#
# $OpenBSD: MKkeyname.awk,v 1.6 2023/10/17 09:52:08 nicm Exp $
# $Id: MKkeyname.awk,v 1.6 2023/10/17 09:52:08 nicm Exp $
##############################################################################
# Copyright 2020 Thomas E. Dickey                                            #
# Copyright 1998-2016,2017 Free Software Foundation, Inc.                    #
#                                                                            #
# Permission is hereby granted, free of charge, to any person obtaining a    #
# copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation  #
# the rights to use, copy, modify, merge, publish, distribute, distribute    #
# with modifications, sublicense, and/or sell copies of the Software, and to #
# permit persons to whom the Software is furnished to do so, subject to the  #
# following conditions:                                                      #
#                                                                            #
# The above copyright notice and this permission notice shall be included in #
# all copies or substantial portions of the Software.                        #
#                                                                            #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR #
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   #
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    #
# THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    #
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER        #
# DEALINGS IN THE SOFTWARE.                                                  #
#                                                                            #
# Except as contained in this notice, the name(s) of the above copyright     #
# holders shall not be used in advertising or otherwise to promote the sale, #
# use or other dealings in this Software without prior written               #
# authorization.                                                             #
##############################################################################
use strict;
use warnings;

my %vars;
while (@ARGV && $ARGV[0] =~ /^(\w+)=(.*)$/) {
    $vars{$1} = $2;
    shift @ARGV;
}
my $bigstrings = defined $vars{bigstrings} ? $vars{bigstrings} : 0;

print "/* generated by MKkeyname.awk */\n";
print "\n";
print "#include <curses.priv.h>\n";
print "#include <tic.h>\n";
print "\n";

my $first = 1;
my $offset = 0;
my $names = '';

while (my $line = <>) {
    chomp $line;
    next unless $line =~ /^[^#]/;

    my @f = split(' ', $line);
    my $f1 = defined $f[0] ? $f[0] : '';

    if ($bigstrings) {
        if ($first) {
            print "struct kn { short offset; int code; };\n";
            print "static const struct kn _nc_key_names[] = {\n";
        }
        printf "\t{ %d, %s },\n", $offset, $f1;
        $offset += length($f1) + 1;
        $names = $names . "\n\t\"" . $f1 . "\\0\"";
    } else {
        if ($first) {
            print "struct kn { const char *name; int code; };\n";
            print "static const struct kn _nc_key_names[] = {\n";
        }
        printf "\t{ \"%s\", %s },\n", $f1, $f1;
    }
    $first = 0;
}

if ($bigstrings) {
    printf "\t{ -1, 0 }};\n";
    print "\n";
    print "static const char key_names[] = " . $names . ";\n";
} else {
    printf "\t{ 0, 0 }};\n";
}
print "\n";
print "#define SIZEOF_TABLE 256\n";
print "#define MyTable _nc_globals.keyname_table\n";
print "#define MyInit  _nc_globals.init_keyname\n";
print "\n";
print "NCURSES_EXPORT(NCURSES_CONST char *)\n";
print "safe_keyname (SCREEN *sp, int c)\n";
print "{\n";
print "\tchar name[20];\n";
print "\tNCURSES_CONST char *result = 0;\n";
print "\n";
print "\tif (c == -1) {\n";
print "\t\tresult = \"-1\";\n";
print "\t} else {\n";
print "\t\tint i;\n";
if ($bigstrings) {
    print "\t\tfor (i = 0; _nc_key_names[i].offset != -1; i++) {\n";
    print "\t\t\tif (_nc_key_names[i].code == c) {\n";
    print "\t\t\t\tresult = (NCURSES_CONST char *)key_names + _nc_key_names[i].offset;\n";
    print "\t\t\t\tbreak;\n";
    print "\t\t\t}\n";
    print "\t\t}\n";
} else {
    print "\t\tfor (i = 0; _nc_key_names[i].name != 0; i++) {\n";
    print "\t\t\tif (_nc_key_names[i].code == c) {\n";
    print "\t\t\t\tresult = (NCURSES_CONST char *)_nc_key_names[i].name;\n";
    print "\t\t\t\tbreak;\n";
    print "\t\t\t}\n";
    print "\t\t}\n";
}
print "\n";
print "\t\tif (result == 0 && (c >= 0 && c < SIZEOF_TABLE)) {\n";
print "\t\t\tif (MyTable == 0)\n";
print "\t\t\t\tMyTable = typeCalloc(char *, SIZEOF_TABLE);\n";
print "\n";
print "\t\t\tif (MyTable != 0) {\n";
print "\t\t\t\tint m_prefix = (sp == 0 || sp->_use_meta);\n";
print "\n";
print "\t\t\t\t/* if sense of meta() changed, discard cached data */\n";
print "\t\t\t\tif (MyInit != (m_prefix + 1)) {\n";
print "\t\t\t\t\tMyInit = m_prefix + 1;\n";
print "\t\t\t\t\tfor (i = 0; i < SIZEOF_TABLE; ++i) {\n";
print "\t\t\t\t\t\tif (MyTable[i]) {\n";
print "\t\t\t\t\t\t\tFreeAndNull(MyTable[i]);\n";
print "\t\t\t\t\t\t}\n";
print "\t\t\t\t\t}\n";
print "\t\t\t\t}\n";
print "\n";
print "\t\t\t\t/* create and cache result as needed */\n";
print "\t\t\t\tif (MyTable[c] == 0) {\n";
print "\t\t\t\t\tint cc = c;\n";
print "\t\t\t\t\tchar *p = name;\n";
print "#define P_LIMIT (sizeof(name) - (size_t) (p - name))\n";
print "\t\t\t\t\tif (cc >= 128 && m_prefix) {\n";
print "\t\t\t\t\t\t_nc_STRCPY(p, \"M-\", P_LIMIT);\n";
print "\t\t\t\t\t\tp += 2;\n";
print "\t\t\t\t\t\tcc -= 128;\n";
print "\t\t\t\t\t}\n";
print "\t\t\t\t\tif (cc < 32)\n";
print "\t\t\t\t\t\t_nc_SPRINTF(p, _nc_SLIMIT(P_LIMIT) \"^%c\", cc + '\@');\n";
print "\t\t\t\t\telse if (cc == 127)\n";
print "\t\t\t\t\t\t_nc_STRCPY(p, \"^?\", P_LIMIT);\n";
print "\t\t\t\t\telse\n";
print "\t\t\t\t\t\t_nc_SPRINTF(p, _nc_SLIMIT(P_LIMIT) \"%c\", cc);\n";
print "\t\t\t\t\tMyTable[c] = strdup(name);\n";
print "\t\t\t\t}\n";
print "\t\t\t\tresult = MyTable[c];\n";
print "\t\t\t}\n";
print "#if NCURSES_EXT_FUNCS && NCURSES_XNAMES\n";
print "\t\t} else if (result == 0 && HasTerminal(sp)) {\n";
print "\t\t\tint j, k;\n";
print "\t\t\tchar * bound;\n";
print "\t\t\tTERMTYPE2 *tp = &TerminalType(TerminalOf(sp));\n";
print "\t\t\tunsigned save_trace = _nc_tracing;\n";
print "\n";
print "\t\t\t_nc_tracing = 0;\t/* prevent recursion via keybound() */\n";
print "\t\t\tfor (j = 0; (bound = NCURSES_SP_NAME(keybound)(NCURSES_SP_ARGx c, j)) != 0; ++j) {\n";
print "\t\t\t\tfor(k = STRCOUNT; k < (int) NUM_STRINGS(tp);  k++) {\n";
print "\t\t\t\t\tif (tp->Strings[k] != 0 && !strcmp(bound, tp->Strings[k])) {\n";
print "\t\t\t\t\t\tresult = ExtStrname(tp, k, strnames);\n";
print "\t\t\t\t\t\tbreak;\n";
print "\t\t\t\t\t}\n";
print "\t\t\t\t}\n";
print "\t\t\t\tfree(bound);\n";
print "\t\t\t\tif (result != 0)\n";
print "\t\t\t\t\tbreak;\n";
print "\t\t\t}\n";
print "\t\t\t_nc_tracing = save_trace;\n";
print "#endif\n";
print "\t\t}\n";
print "\t}\n";
print "\treturn result;\n";
print "}\n";
print "\n";
print "NCURSES_EXPORT(NCURSES_CONST char *)\n";
print "keyname (int c)\n";
print "{\n";
print "\treturn safe_keyname (CURRENT_SCREEN, c);\n";
print "}\n";
print "\n";
print "#if NO_LEAKS\n";
print "void _nc_keyname_leaks(void)\n";
print "{\n";
print "\tif (MyTable != 0) {\n";
print "\t\tint j;\n";
print "\t\tfor (j = 0; j < SIZEOF_TABLE; ++j) {\n";
print "\t\t\tFreeIfNeeded(MyTable[j]);\n";
print "\t\t}\n";
print "\t\tFreeAndNull(MyTable);\n";
print "\t}\n";
print "}\n";
print "#endif /* NO_LEAKS */\n";
