/*
 * Copyright (C) 2018  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _mmhub_9_4_1_OFFSET_HEADER
#define _mmhub_9_4_1_OFFSET_HEADER

// addressBlock: mmhub_dagb_dagbdec0
// base address: 0x68000
#define mmDAGB0_RD_CGTT_CLK_CTRL 0x0015
#define mmDAGB0_RD_CGTT_CLK_CTRL_BASE_IDX 1
#define mmDAGB0_WR_CGTT_CLK_CTRL 0x0041
#define mmDAGB0_WR_CGTT_CLK_CTRL_BASE_IDX 1
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x005b
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 1
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x005c
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 1
#define mmDAGB0_CNTL_MISC2 0x0067
#define mmDAGB0_CNTL_MISC2_BASE_IDX 1
// addressBlock: mmhub_dagb_dagbdec1
// base address: 0x68200
#define mmDAGB1_WRCLI2 0x00ae
#define mmDAGB1_WRCLI2_BASE_IDX 1
#define mmDAGB1_WRCLI_GPU_SNOOP_OVERRIDE 0x00db
#define mmDAGB1_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 1
#define mmDAGB1_CNTL_MISC2 0x00e7
#define mmDAGB1_CNTL_MISC2_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec0
// base address: 0x68a00
#define mmMMEA0_EDC_CNT 0x0386
#define mmMMEA0_EDC_CNT_BASE_IDX 1
#define mmMMEA0_EDC_CNT2 0x0387
#define mmMMEA0_EDC_CNT2_BASE_IDX 1
#define mmMMEA0_ERR_STATUS 0x0391
#define mmMMEA0_ERR_STATUS_BASE_IDX 1
#define mmMMEA0_EDC_CNT3 0x0394
#define mmMMEA0_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec1
// base address: 0x68f00
#define mmMMEA1_DRAM_WR_CLI2GRP_MAP0 0x03c2
#define mmMMEA1_DRAM_WR_CLI2GRP_MAP0_BASE_IDX 1
#define mmMMEA1_EDC_CNT 0x04c6
#define mmMMEA1_EDC_CNT_BASE_IDX 1
#define mmMMEA1_EDC_CNT2 0x04c7
#define mmMMEA1_EDC_CNT2_BASE_IDX 1
#define mmMMEA1_ERR_STATUS 0x04d1
#define mmMMEA1_ERR_STATUS_BASE_IDX 1
#define mmMMEA1_EDC_CNT3 0x04d4
#define mmMMEA1_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec2
// base address: 0x69400
#define mmMMEA2_EDC_CNT 0x0606
#define mmMMEA2_EDC_CNT_BASE_IDX 1
#define mmMMEA2_EDC_CNT2 0x0607
#define mmMMEA2_EDC_CNT2_BASE_IDX 1
#define mmMMEA2_ERR_STATUS 0x0611
#define mmMMEA2_ERR_STATUS_BASE_IDX 1
#define mmMMEA2_EDC_CNT3 0x0614
#define mmMMEA2_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec3
// base address: 0x69900
#define mmMMEA3_EDC_CNT 0x0746
#define mmMMEA3_EDC_CNT_BASE_IDX 1
#define mmMMEA3_EDC_CNT2 0x0747
#define mmMMEA3_EDC_CNT2_BASE_IDX 1
#define mmMMEA3_ERR_STATUS 0x0751
#define mmMMEA3_ERR_STATUS_BASE_IDX 1
#define mmMMEA3_EDC_CNT3 0x0754
#define mmMMEA3_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec4
// base address: 0x69e00
#define mmMMEA4_EDC_CNT 0x0886
#define mmMMEA4_EDC_CNT_BASE_IDX 1
#define mmMMEA4_EDC_CNT2 0x0887
#define mmMMEA4_EDC_CNT2_BASE_IDX 1
#define mmMMEA4_ERR_STATUS 0x0891
#define mmMMEA4_ERR_STATUS_BASE_IDX 1
#define mmMMEA4_EDC_CNT3 0x0894
#define mmMMEA4_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_utcl2_atcl2dec
// base address: 0x6a600
#define mmATCL2_0_ATC_L2_MISC_CG 0x098b
#define mmATCL2_0_ATC_L2_MISC_CG_BASE_IDX 1
// addressBlock: mmhub_utcl2_vml2pfdec
// base address: 0x6a700
#define mmVML2PF0_VM_L2_CNTL 0x09c0
#define mmVML2PF0_VM_L2_CNTL_BASE_IDX 1
#define mmVML2PF0_VM_L2_CNTL2 0x09c1
#define mmVML2PF0_VM_L2_CNTL2_BASE_IDX 1
#define mmVML2PF0_VM_L2_CNTL3 0x09c2
#define mmVML2PF0_VM_L2_CNTL3_BASE_IDX 1
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_CNTL 0x09c7
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 1
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_CNTL2 0x09c8
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 1
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_STATUS 0x09cb
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 1
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x09ce
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 1
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x09cf
#define mmVML2PF0_VM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x09d1
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x09d2
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x09d3
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x09d4
#define mmVML2PF0_VM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x09d5
#define mmVML2PF0_VM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x09d6
#define mmVML2PF0_VM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 1
#define mmVML2PF0_VM_L2_CNTL4 0x09d7
#define mmVML2PF0_VM_L2_CNTL4_BASE_IDX 1
// addressBlock: mmhub_utcl2_vml2vcdec
// base address: 0x6a800
#define mmVML2VC0_VM_CONTEXT0_CNTL 0x0a00
#define mmVML2VC0_VM_CONTEXT0_CNTL_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT1_CNTL 0x0a01
#define mmVML2VC0_VM_CONTEXT1_CNTL_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG0_SEM 0x0a11
#define mmVML2VC0_VM_INVALIDATE_ENG0_SEM_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG0_REQ 0x0a23
#define mmVML2VC0_VM_INVALIDATE_ENG0_REQ_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG1_REQ 0x0a24
#define mmVML2VC0_VM_INVALIDATE_ENG1_REQ_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG0_ACK 0x0a35
#define mmVML2VC0_VM_INVALIDATE_ENG0_ACK_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0a47
#define mmVML2VC0_VM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0a48
#define mmVML2VC0_VM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 1
#define mmVML2VC0_VM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0a49
#define mmVML2VC0_VM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x0a6b
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x0a6c
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x0a6d
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x0a8b
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x0a8c
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x0a8d
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x0a8e
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x0aab
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x0aac
#define mmVML2VC0_VM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x0aad
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x0aae
#define mmVML2VC0_VM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
// addressBlock: mmhub_utcl2_vmsharedpfdec
// base address: 0x6ab90
#define mmVMSHAREDPF0_MC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x0aec
#define mmVMSHAREDPF0_MC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 1
#define mmVMSHAREDPF0_MC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x0aed
#define mmVMSHAREDPF0_MC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 1
#define mmMC_VM_XGMI_LFB_CNTL 0x0823
#define mmMC_VM_XGMI_LFB_CNTL_BASE_IDX 0
#define mmMC_VM_XGMI_LFB_SIZE 0x0824
#define mmMC_VM_XGMI_LFB_SIZE_BASE_IDX 0
// addressBlock: mmhub_utcl2_vmsharedvcdec
// base address: 0x6ac00
#define mmVMSHAREDVC0_MC_VM_FB_LOCATION_BASE 0x0b00
#define mmVMSHAREDVC0_MC_VM_FB_LOCATION_BASE_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_FB_LOCATION_TOP 0x0b01
#define mmVMSHAREDVC0_MC_VM_FB_LOCATION_TOP_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_AGP_TOP 0x0b02
#define mmVMSHAREDVC0_MC_VM_AGP_TOP_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_AGP_BOT 0x0b03
#define mmVMSHAREDVC0_MC_VM_AGP_BOT_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_AGP_BASE 0x0b04
#define mmVMSHAREDVC0_MC_VM_AGP_BASE_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_SYSTEM_APERTURE_LOW_ADDR 0x0b05
#define mmVMSHAREDVC0_MC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x0b06
#define mmVMSHAREDVC0_MC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 1
#define mmVMSHAREDVC0_MC_VM_MX_L1_TLB_CNTL 0x0b07
#define mmVMSHAREDVC0_MC_VM_MX_L1_TLB_CNTL_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec5
// base address: 0x74a00
#define mmMMEA5_EDC_CNT 0x3386
#define mmMMEA5_EDC_CNT_BASE_IDX 1
#define mmMMEA5_EDC_CNT2 0x3387
#define mmMMEA5_EDC_CNT2_BASE_IDX 1
#define mmMMEA5_ERR_STATUS 0x3391
#define mmMMEA5_ERR_STATUS_BASE_IDX 1
#define mmMMEA5_EDC_CNT3 0x3394
#define mmMMEA5_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec6
// base address: 0x74f00
#define mmMMEA6_EDC_CNT 0x34c6
#define mmMMEA6_EDC_CNT_BASE_IDX 1
#define mmMMEA6_EDC_CNT2 0x34c7
#define mmMMEA6_EDC_CNT2_BASE_IDX 1
#define mmMMEA6_ERR_STATUS 0x34d1
#define mmMMEA6_ERR_STATUS_BASE_IDX 1
#define mmMMEA6_EDC_CNT3 0x34d4
#define mmMMEA6_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_ea_mmeadec7
// base address: 0x75400
#define mmMMEA7_EDC_CNT 0x3606
#define mmMMEA7_EDC_CNT_BASE_IDX 1
#define mmMMEA7_EDC_CNT2 0x3607
#define mmMMEA7_EDC_CNT2_BASE_IDX 1
#define mmMMEA7_ERR_STATUS 0x3611
#define mmMMEA7_ERR_STATUS_BASE_IDX 1
#define mmMMEA7_EDC_CNT3 0x3614
#define mmMMEA7_EDC_CNT3_BASE_IDX 1
#endif
