/*
 * Copyright 2021 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _mmhub_3_0_0_OFFSET_HEADER
#define _mmhub_3_0_0_OFFSET_HEADER

// addressBlock: mmhub_dagbdec
// base address: 0x68000
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x007f
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x0080
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 0
#define regDAGB0_CNTL_MISC2 0x0085
#define regDAGB0_CNTL_MISC2_BASE_IDX 0
#define regDAGB1_CNTL_MISC2 0x00f5
#define regDAGB1_CNTL_MISC2_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmatcl2dec
// base address: 0x69b00
#define regMM_ATC_L2_MISC_CG 0x06cd
#define regMM_ATC_L2_MISC_CG_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvml2pfdec
// base address: 0x69c00
#define regMMVM_L2_CNTL 0x0700
#define regMMVM_L2_CNTL_BASE_IDX 0
#define regMMVM_L2_CNTL2 0x0701
#define regMMVM_L2_CNTL2_BASE_IDX 0
#define regMMVM_L2_CNTL3 0x0702
#define regMMVM_L2_CNTL3_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_CNTL 0x0708
#define regMMVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_CNTL2 0x0709
#define regMMVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_STATUS 0x070c
#define regMMVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x070f
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x0710
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0712
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0713
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0714
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0715
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 0
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0716
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 0
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0717
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 0
#define regMMVM_L2_CNTL4 0x0718
#define regMMVM_L2_CNTL4_BASE_IDX 0
#define regMMVM_L2_BANK_SELECT_RESERVED_CID2 0x071b
#define regMMVM_L2_BANK_SELECT_RESERVED_CID2_BASE_IDX 0
#define regMMVM_L2_CNTL5 0x071e
#define regMMVM_L2_CNTL5_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvml2vcdec
// base address: 0x69d00
#define regMMVM_CONTEXT0_CNTL 0x0740
#define regMMVM_CONTEXT0_CNTL_BASE_IDX 0
#define regMMVM_CONTEXT1_CNTL 0x0741
#define regMMVM_CONTEXT1_CNTL_BASE_IDX 0
#define regMMVM_CONTEXTS_DISABLE 0x0750
#define regMMVM_CONTEXTS_DISABLE_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_SEM 0x0751
#define regMMVM_INVALIDATE_ENG0_SEM_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_REQ 0x0763
#define regMMVM_INVALIDATE_ENG0_REQ_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG1_REQ 0x0764
#define regMMVM_INVALIDATE_ENG1_REQ_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_ACK 0x0775
#define regMMVM_INVALIDATE_ENG0_ACK_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0787
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0788
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0789
#define regMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x07ab
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x07ac
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x07ad
#define regMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x07cb
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x07cc
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x07cd
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x07ce
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x07eb
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x07ec
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x07ed
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x07ee
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvmsharedpfdec
// base address: 0x6a340
#define regMMMC_VM_FB_OFFSET 0x08d7
#define regMMMC_VM_FB_OFFSET_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x08d8
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x08d9
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 0
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_START 0x08df
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_START_BASE_IDX 0
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_END 0x08e0
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_END_BASE_IDX 0
#define regMMMC_VM_LOCAL_FB_ADDRESS_START 0x08e2
#define regMMMC_VM_LOCAL_FB_ADDRESS_START_BASE_IDX 0
#define regMMMC_VM_LOCAL_FB_ADDRESS_END 0x08e3
#define regMMMC_VM_LOCAL_FB_ADDRESS_END_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvmsharedvcdec
// base address: 0x6a3b0
#define regMMMC_VM_FB_LOCATION_BASE 0x08ec
#define regMMMC_VM_FB_LOCATION_BASE_BASE_IDX 0
#define regMMMC_VM_FB_LOCATION_TOP 0x08ed
#define regMMMC_VM_FB_LOCATION_TOP_BASE_IDX 0
#define regMMMC_VM_AGP_TOP 0x08ee
#define regMMMC_VM_AGP_TOP_BASE_IDX 0
#define regMMMC_VM_AGP_BOT 0x08ef
#define regMMMC_VM_AGP_BOT_BASE_IDX 0
#define regMMMC_VM_AGP_BASE 0x08f0
#define regMMMC_VM_AGP_BASE_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x08f1
#define regMMMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x08f2
#define regMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 0
#define regMMMC_VM_MX_L1_TLB_CNTL 0x08f3
#define regMMMC_VM_MX_L1_TLB_CNTL_BASE_IDX 0
#endif
