/*
 * Copyright 2020 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _mmhub_1_7_OFFSET_HEADER
#define _mmhub_1_7_OFFSET_HEADER

// addressBlock: mmhub_dagb_dagbdec0
// base address: 0x68000
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x005e
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x005f
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 0
#define regDAGB0_CNTL_MISC2 0x006a
#define regDAGB0_CNTL_MISC2_BASE_IDX 0
// addressBlock: mmhub_dagb_dagbdec1
// base address: 0x68200
#define regDAGB1_WRCLI_GPU_SNOOP_OVERRIDE 0x00de
#define regDAGB1_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define regDAGB1_CNTL_MISC2 0x00ea
#define regDAGB1_CNTL_MISC2_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec0
// base address: 0x68c00
#define regMMEA0_EDC_CNT 0x0406
#define regMMEA0_EDC_CNT_BASE_IDX 0
#define regMMEA0_EDC_CNT2 0x0407
#define regMMEA0_EDC_CNT2_BASE_IDX 0
#define regMMEA0_ERR_STATUS 0x0411
#define regMMEA0_ERR_STATUS_BASE_IDX 0
#define regMMEA0_EDC_CNT3 0x0414
#define regMMEA0_EDC_CNT3_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec1
// base address: 0x69100
#define regMMEA1_EDC_CNT 0x0546
#define regMMEA1_EDC_CNT_BASE_IDX 0
#define regMMEA1_EDC_CNT2 0x0547
#define regMMEA1_EDC_CNT2_BASE_IDX 0
#define regMMEA1_ERR_STATUS 0x0551
#define regMMEA1_ERR_STATUS_BASE_IDX 0
#define regMMEA1_EDC_CNT3 0x0554
#define regMMEA1_EDC_CNT3_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec2
// base address: 0x69600
#define regMMEA2_EDC_CNT 0x0686
#define regMMEA2_EDC_CNT_BASE_IDX 0
#define regMMEA2_EDC_CNT2 0x0687
#define regMMEA2_EDC_CNT2_BASE_IDX 0
#define regMMEA2_ERR_STATUS 0x0691
#define regMMEA2_ERR_STATUS_BASE_IDX 0
#define regMMEA2_EDC_CNT3 0x0694
#define regMMEA2_EDC_CNT3_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec3
// base address: 0x69b00
#define regMMEA3_EDC_CNT 0x07c6
#define regMMEA3_EDC_CNT_BASE_IDX 0
#define regMMEA3_EDC_CNT2 0x07c7
#define regMMEA3_EDC_CNT2_BASE_IDX 0
#define regMMEA3_ERR_STATUS 0x07d1
#define regMMEA3_ERR_STATUS_BASE_IDX 0
#define regMMEA3_EDC_CNT3 0x07d4
#define regMMEA3_EDC_CNT3_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec4
// base address: 0x6a000
#define regMMEA4_EDC_CNT 0x0906
#define regMMEA4_EDC_CNT_BASE_IDX 0
#define regMMEA4_EDC_CNT2 0x0907
#define regMMEA4_EDC_CNT2_BASE_IDX 0
#define regMMEA4_ERR_STATUS 0x0911
#define regMMEA4_ERR_STATUS_BASE_IDX 0
#define regMMEA4_EDC_CNT3 0x0914
#define regMMEA4_EDC_CNT3_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec5
// base address: 0x6a500
#define regMMEA5_EDC_CNT 0x0a46
#define regMMEA5_EDC_CNT_BASE_IDX 0
#define regMMEA5_EDC_CNT2 0x0a47
#define regMMEA5_EDC_CNT2_BASE_IDX 0
#define regMMEA5_ERR_STATUS 0x0a51
#define regMMEA5_ERR_STATUS_BASE_IDX 0
#define regMMEA5_EDC_CNT3 0x0a54
#define regMMEA5_EDC_CNT3_BASE_IDX 0
// addressBlock: mmhub_utcl2_atcl2dec
// base address: 0x6ad00
#define regATC_L2_MISC_CG 0x0b4b
#define regATC_L2_MISC_CG_BASE_IDX 0
#define regATC_L2_CACHE_4K_DSM_INDEX 0x0b4e
#define regATC_L2_CACHE_4K_DSM_INDEX_BASE_IDX 0
#define regATC_L2_CACHE_32K_DSM_INDEX 0x0b4f
#define regATC_L2_CACHE_32K_DSM_INDEX_BASE_IDX 0
#define regATC_L2_CACHE_2M_DSM_INDEX 0x0b50
#define regATC_L2_CACHE_2M_DSM_INDEX_BASE_IDX 0
#define regATC_L2_CACHE_4K_DSM_CNTL 0x0b51
#define regATC_L2_CACHE_4K_DSM_CNTL_BASE_IDX 0
#define regATC_L2_CACHE_32K_DSM_CNTL 0x0b52
#define regATC_L2_CACHE_32K_DSM_CNTL_BASE_IDX 0
#define regATC_L2_CACHE_2M_DSM_CNTL 0x0b53
#define regATC_L2_CACHE_2M_DSM_CNTL_BASE_IDX 0
// addressBlock: mmhub_utcl2_vml2pfdec
// base address: 0x6ae00
#define regVM_L2_CNTL 0x0b80
#define regVM_L2_CNTL_BASE_IDX 0
#define regVM_L2_CNTL2 0x0b81
#define regVM_L2_CNTL2_BASE_IDX 0
#define regVM_L2_CNTL3 0x0b82
#define regVM_L2_CNTL3_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_CNTL 0x0b87
#define regVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_CNTL2 0x0b88
#define regVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_STATUS 0x0b8b
#define regVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x0b8e
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x0b8f
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0b91
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0b92
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0b93
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0b94
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 0
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0b95
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 0
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0b96
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 0
#define regVM_L2_CNTL4 0x0b97
#define regVM_L2_CNTL4_BASE_IDX 0
#define regVML2_MEM_ECC_INDEX 0x0ba1
#define regVML2_MEM_ECC_INDEX_BASE_IDX 0
#define regVML2_WALKER_MEM_ECC_INDEX 0x0ba2
#define regVML2_WALKER_MEM_ECC_INDEX_BASE_IDX 0
#define regUTCL2_MEM_ECC_INDEX 0x0ba3
#define regUTCL2_MEM_ECC_INDEX_BASE_IDX 0
#define regVML2_MEM_ECC_CNTL 0x0ba4
#define regVML2_MEM_ECC_CNTL_BASE_IDX 0
#define regVML2_WALKER_MEM_ECC_CNTL 0x0ba5
#define regVML2_WALKER_MEM_ECC_CNTL_BASE_IDX 0
#define regUTCL2_MEM_ECC_CNTL 0x0ba6
#define regUTCL2_MEM_ECC_CNTL_BASE_IDX 0
#define regVML2_MEM_ECC_STATUS 0x0ba7
#define regVML2_MEM_ECC_STATUS_BASE_IDX 0
#define regVML2_WALKER_MEM_ECC_STATUS 0x0ba8
#define regVML2_WALKER_MEM_ECC_STATUS_BASE_IDX 0
#define regUTCL2_MEM_ECC_STATUS 0x0ba9
#define regUTCL2_MEM_ECC_STATUS_BASE_IDX 0
// addressBlock: mmhub_utcl2_vml2vcdec
// base address: 0x6af00
#define regVM_CONTEXT0_CNTL 0x0bc0
#define regVM_CONTEXT0_CNTL_BASE_IDX 0
#define regVM_CONTEXT1_CNTL 0x0bc1
#define regVM_CONTEXT1_CNTL_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_SEM 0x0bd1
#define regVM_INVALIDATE_ENG0_SEM_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_REQ 0x0be3
#define regVM_INVALIDATE_ENG0_REQ_BASE_IDX 0
#define regVM_INVALIDATE_ENG1_REQ 0x0be4
#define regVM_INVALIDATE_ENG1_REQ_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_ACK 0x0bf5
#define regVM_INVALIDATE_ENG0_ACK_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0c07
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0c08
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 0
#define regVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0c09
#define regVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x0c2b
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x0c2c
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x0c2d
#define regVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x0c4b
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x0c4c
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x0c4d
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x0c4e
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x0c6b
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x0c6c
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x0c6d
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x0c6e
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
// addressBlock: mmhub_utcl2_vmsharedpfdec
// base address: 0x6b290
#define regMC_VM_FB_OFFSET 0x0cab
#define regMC_VM_FB_OFFSET_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x0cac
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x0cad
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 0
#define regMC_VM_XGMI_LFB_CNTL 0x0cb8
#define regMC_VM_XGMI_LFB_CNTL_BASE_IDX 0
#define regMC_VM_XGMI_LFB_SIZE 0x0cb9
#define regMC_VM_XGMI_LFB_SIZE_BASE_IDX 0
// addressBlock: mmhub_utcl2_vmsharedvcdec
// base address: 0x6b300
#define regMC_VM_FB_LOCATION_BASE 0x0cc0
#define regMC_VM_FB_LOCATION_BASE_BASE_IDX 0
#define regMC_VM_FB_LOCATION_TOP 0x0cc1
#define regMC_VM_FB_LOCATION_TOP_BASE_IDX 0
#define regMC_VM_AGP_TOP 0x0cc2
#define regMC_VM_AGP_TOP_BASE_IDX 0
#define regMC_VM_AGP_BOT 0x0cc3
#define regMC_VM_AGP_BOT_BASE_IDX 0
#define regMC_VM_AGP_BASE 0x0cc4
#define regMC_VM_AGP_BASE_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x0cc5
#define regMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x0cc6
#define regMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 0
#define regMC_VM_MX_L1_TLB_CNTL 0x0cc7
#define regMC_VM_MX_L1_TLB_CNTL_BASE_IDX 0
#endif
