/*
 * Copyright (C) 2020  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _mmhub_2_3_0_OFFSET_HEADER
#define _mmhub_2_3_0_OFFSET_HEADER

// addressBlock: mmhub_dagbdec
// base address: 0x68000
#define mmDAGB0_RD_CGTT_CLK_CTRL 0x0024
#define mmDAGB0_RD_CGTT_CLK_CTRL_BASE_IDX 1
#define mmDAGB0_WR_CGTT_CLK_CTRL 0x0065
#define mmDAGB0_WR_CGTT_CLK_CTRL_BASE_IDX 1
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x0092
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 1
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x0093
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 1
#define mmDAGB0_CNTL_MISC2 0x0096
#define mmDAGB0_CNTL_MISC2_BASE_IDX 1
// addressBlock: mmhub_mmea_mmeadec0
// base address: 0x68400
#define mmMMEA0_EDC_CNT 0x020f
#define mmMMEA0_EDC_CNT_BASE_IDX 1
#define mmMMEA0_EDC_CNT2 0x0210
#define mmMMEA0_EDC_CNT2_BASE_IDX 1
#define mmMMEA0_ERR_STATUS 0x021a
#define mmMMEA0_ERR_STATUS_BASE_IDX 1
#define mmMMEA0_EDC_CNT3 0x021d
#define mmMMEA0_EDC_CNT3_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmatcl2dec
// base address: 0x69b00
#define mmMM_ATC_L2_MISC_CG 0x06cd
#define mmMM_ATC_L2_MISC_CG_BASE_IDX 1
#define mmMM_ATC_L2_CGTT_CLK_CTRL 0x06cf
#define mmMM_ATC_L2_CGTT_CLK_CTRL_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvml2pfdec
// base address: 0x69c00
#define mmMMVM_L2_CNTL 0x0700
#define mmMMVM_L2_CNTL_BASE_IDX 1
#define mmMMVM_L2_CNTL2 0x0701
#define mmMMVM_L2_CNTL2_BASE_IDX 1
#define mmMMVM_L2_CNTL3 0x0702
#define mmMMVM_L2_CNTL3_BASE_IDX 1
#define mmMMVM_L2_PROTECTION_FAULT_CNTL 0x0708
#define mmMMVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 1
#define mmMMVM_L2_PROTECTION_FAULT_CNTL2 0x0709
#define mmMMVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 1
#define mmMMVM_L2_PROTECTION_FAULT_STATUS 0x070c
#define mmMMVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 1
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x070f
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 1
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x0710
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 1
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0712
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 1
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0713
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 1
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0714
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 1
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0715
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 1
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0716
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 1
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0717
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 1
#define mmMMVM_L2_CNTL4 0x0718
#define mmMMVM_L2_CNTL4_BASE_IDX 1
#define mmMMVM_L2_CNTL5 0x0720
#define mmMMVM_L2_CNTL5_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvml2vcdec
// base address: 0x69d00
#define mmMMVM_CONTEXT0_CNTL 0x0740
#define mmMMVM_CONTEXT0_CNTL_BASE_IDX 1
#define mmMMVM_CONTEXT1_CNTL 0x0741
#define mmMMVM_CONTEXT1_CNTL_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvmsharedpfdec
// base address: 0x6a340
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x08d8
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 1
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x08d9
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvmsharedvcdec
// base address: 0x6a3b0
#define mmMMMC_VM_FB_LOCATION_BASE 0x08ec
#define mmMMMC_VM_FB_LOCATION_BASE_BASE_IDX 1
#define mmMMMC_VM_FB_LOCATION_TOP 0x08ed
#define mmMMMC_VM_FB_LOCATION_TOP_BASE_IDX 1
#define mmMMMC_VM_AGP_TOP 0x08ee
#define mmMMMC_VM_AGP_TOP_BASE_IDX 1
#define mmMMMC_VM_AGP_BOT 0x08ef
#define mmMMMC_VM_AGP_BOT_BASE_IDX 1
#define mmMMMC_VM_AGP_BASE 0x08f0
#define mmMMMC_VM_AGP_BASE_BASE_IDX 1
#define mmMMMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x08f1
#define mmMMMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 1
#define mmMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x08f2
#define mmMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 1
#define mmMMMC_VM_MX_L1_TLB_CNTL 0x08f3
#define mmMMMC_VM_MX_L1_TLB_CNTL_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvml2ptdec
// base address: 0x6a500
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x0940
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x0941
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 1
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x0942
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x0943
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x0944
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x0945
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
#define mmMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x0948
#define mmMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x094a
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x094b
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x094c
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x094d
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvml2indec
// base address: 0x6a800
#define mmMMVM_INVALIDATE_ENG0_SEM 0x0a00
#define mmMMVM_INVALIDATE_ENG0_SEM_BASE_IDX 1
#define mmMMVM_INVALIDATE_ENG0_REQ 0x0a01
#define mmMMVM_INVALIDATE_ENG0_REQ_BASE_IDX 1
#define mmMMVM_INVALIDATE_ENG0_ACK 0x0a02
#define mmMMVM_INVALIDATE_ENG0_ACK_BASE_IDX 1
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0a03
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 1
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0a04
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 1
#define mmMMVM_INVALIDATE_ENG1_REQ 0x0a09
#define mmMMVM_INVALIDATE_ENG1_REQ_BASE_IDX 1
#define mmMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0a0b
#define mmMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 1
#endif
