/*
 * Copyright 2022 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _mmhub_1_8_0_OFFSET_HEADER
#define _mmhub_1_8_0_OFFSET_HEADER

// addressBlock: aid_mmhub_dagb_dagbdec0
// base address: 0x60000
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x0060
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x0061
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 0
#define regDAGB0_CNTL_MISC2 0x006e
#define regDAGB0_CNTL_MISC2_BASE_IDX 0
// addressBlock: aid_mmhub_dagb_dagbdec1
// base address: 0x60200
#define regDAGB1_WRCLI_GPU_SNOOP_OVERRIDE 0x00e0
#define regDAGB1_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define regDAGB1_CNTL_MISC2 0x00ee
#define regDAGB1_CNTL_MISC2_BASE_IDX 0
// addressBlock: aid_mmhub_ea_mmeadec0
// base address: 0x60c00
#define regMMEA0_UE_ERR_STATUS_LO 0x0406
#define regMMEA0_UE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA0_UE_ERR_STATUS_HI 0x0407
#define regMMEA0_UE_ERR_STATUS_HI_BASE_IDX 0
#define regMMEA0_ERR_STATUS 0x0411
#define regMMEA0_ERR_STATUS_BASE_IDX 0
#define regMMEA0_CE_ERR_STATUS_LO 0x0414
#define regMMEA0_CE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA0_CE_ERR_STATUS_HI 0x0416
#define regMMEA0_CE_ERR_STATUS_HI_BASE_IDX 0
// addressBlock: aid_mmhub_ea_mmeadec1
// base address: 0x61100
#define regMMEA1_UE_ERR_STATUS_LO 0x0546
#define regMMEA1_UE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA1_UE_ERR_STATUS_HI 0x0547
#define regMMEA1_UE_ERR_STATUS_HI_BASE_IDX 0
#define regMMEA1_ERR_STATUS 0x0551
#define regMMEA1_ERR_STATUS_BASE_IDX 0
#define regMMEA1_CE_ERR_STATUS_LO 0x0554
#define regMMEA1_CE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA1_CE_ERR_STATUS_HI 0x0556
#define regMMEA1_CE_ERR_STATUS_HI_BASE_IDX 0
// addressBlock: aid_mmhub_ea_mmeadec2
// base address: 0x61600
#define regMMEA2_UE_ERR_STATUS_LO 0x0686
#define regMMEA2_UE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA2_UE_ERR_STATUS_HI 0x0687
#define regMMEA2_UE_ERR_STATUS_HI_BASE_IDX 0
#define regMMEA2_ERR_STATUS 0x0691
#define regMMEA2_ERR_STATUS_BASE_IDX 0
#define regMMEA2_CE_ERR_STATUS_LO 0x0694
#define regMMEA2_CE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA2_CE_ERR_STATUS_HI 0x0696
#define regMMEA2_CE_ERR_STATUS_HI_BASE_IDX 0
// addressBlock: aid_mmhub_ea_mmeadec3
// base address: 0x61b00
#define regMMEA3_UE_ERR_STATUS_LO 0x07c6
#define regMMEA3_UE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA3_UE_ERR_STATUS_HI 0x07c7
#define regMMEA3_UE_ERR_STATUS_HI_BASE_IDX 0
#define regMMEA3_ERR_STATUS 0x07d1
#define regMMEA3_ERR_STATUS_BASE_IDX 0
#define regMMEA3_CE_ERR_STATUS_LO 0x07d4
#define regMMEA3_CE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA3_CE_ERR_STATUS_HI 0x07d6
#define regMMEA3_CE_ERR_STATUS_HI_BASE_IDX 0
// addressBlock: aid_mmhub_ea_mmeadec4
// base address: 0x62000
#define regMMEA4_UE_ERR_STATUS_LO 0x0906
#define regMMEA4_UE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA4_UE_ERR_STATUS_HI 0x0907
#define regMMEA4_UE_ERR_STATUS_HI_BASE_IDX 0
#define regMMEA4_ERR_STATUS 0x0911
#define regMMEA4_ERR_STATUS_BASE_IDX 0
#define regMMEA4_CE_ERR_STATUS_LO 0x0914
#define regMMEA4_CE_ERR_STATUS_LO_BASE_IDX 0
#define regMMEA4_CE_ERR_STATUS_HI 0x0916
#define regMMEA4_CE_ERR_STATUS_HI_BASE_IDX 0
// addressBlock: aid_mmhub_utcl2_atcl2dec
// base address: 0x62d00
#define regATC_L2_MISC_CG 0x0b4b
#define regATC_L2_MISC_CG_BASE_IDX 0
#define regATC_L2_CACHE_4K_DSM_INDEX 0x0b4f
#define regATC_L2_CACHE_4K_DSM_INDEX_BASE_IDX 0
#define regATC_L2_CACHE_32K_DSM_INDEX 0x0b50
#define regATC_L2_CACHE_32K_DSM_INDEX_BASE_IDX 0
#define regATC_L2_CACHE_2M_DSM_INDEX 0x0b51
#define regATC_L2_CACHE_2M_DSM_INDEX_BASE_IDX 0
#define regATC_L2_CACHE_4K_DSM_CNTL 0x0b52
#define regATC_L2_CACHE_4K_DSM_CNTL_BASE_IDX 0
#define regATC_L2_CACHE_32K_DSM_CNTL 0x0b53
#define regATC_L2_CACHE_32K_DSM_CNTL_BASE_IDX 0
#define regATC_L2_CACHE_2M_DSM_CNTL 0x0b54
#define regATC_L2_CACHE_2M_DSM_CNTL_BASE_IDX 0
// addressBlock: aid_mmhub_utcl2_vml2pfdec
// base address: 0x62d80
#define regVM_L2_CNTL 0x0b60
#define regVM_L2_CNTL_BASE_IDX 0
#define regVM_L2_CNTL2 0x0b61
#define regVM_L2_CNTL2_BASE_IDX 0
#define regVM_L2_CNTL3 0x0b62
#define regVM_L2_CNTL3_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_CNTL 0x0b67
#define regVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_CNTL2 0x0b68
#define regVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_STATUS 0x0b6b
#define regVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x0b6e
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 0
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x0b6f
#define regVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0b71
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0b72
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0b73
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 0
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0b74
#define regVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 0
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0b75
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 0
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0b76
#define regVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 0
#define regVM_L2_CNTL4 0x0b77
#define regVM_L2_CNTL4_BASE_IDX 0
#define regVML2_MEM_ECC_INDEX 0x0b82
#define regVML2_MEM_ECC_INDEX_BASE_IDX 0
#define regVML2_WALKER_MEM_ECC_INDEX 0x0b83
#define regVML2_WALKER_MEM_ECC_INDEX_BASE_IDX 0
#define regUTCL2_MEM_ECC_INDEX 0x0b84
#define regUTCL2_MEM_ECC_INDEX_BASE_IDX 0
#define regVML2_MEM_ECC_CNTL 0x0b85
#define regVML2_MEM_ECC_CNTL_BASE_IDX 0
#define regVML2_WALKER_MEM_ECC_CNTL 0x0b86
#define regVML2_WALKER_MEM_ECC_CNTL_BASE_IDX 0
#define regUTCL2_MEM_ECC_CNTL 0x0b87
#define regUTCL2_MEM_ECC_CNTL_BASE_IDX 0
#define regVML2_MEM_ECC_STATUS 0x0b88
#define regVML2_MEM_ECC_STATUS_BASE_IDX 0
#define regVML2_WALKER_MEM_ECC_STATUS 0x0b89
#define regVML2_WALKER_MEM_ECC_STATUS_BASE_IDX 0
#define regUTCL2_MEM_ECC_STATUS 0x0b8a
#define regUTCL2_MEM_ECC_STATUS_BASE_IDX 0
// addressBlock: aid_mmhub_utcl2_vml2vcdec
// base address: 0x62e80
#define regVM_CONTEXT0_CNTL 0x0ba0
#define regVM_CONTEXT0_CNTL_BASE_IDX 0
#define regVM_CONTEXT1_CNTL 0x0ba1
#define regVM_CONTEXT1_CNTL_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_SEM 0x0bb1
#define regVM_INVALIDATE_ENG0_SEM_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_REQ 0x0bc3
#define regVM_INVALIDATE_ENG0_REQ_BASE_IDX 0
#define regVM_INVALIDATE_ENG1_REQ 0x0bc4
#define regVM_INVALIDATE_ENG1_REQ_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_ACK 0x0bd5
#define regVM_INVALIDATE_ENG0_ACK_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0be7
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 0
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0be8
#define regVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 0
#define regVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0be9
#define regVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x0c0b
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x0c0c
#define regVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x0c0d
#define regVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x0c2b
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x0c2c
#define regVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x0c2d
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x0c2e
#define regVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x0c4b
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x0c4c
#define regVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x0c4d
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x0c4e
#define regVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
// addressBlock: aid_mmhub_utcl2_vmsharedpfdec
// base address: 0x63200
#define regMC_VM_FB_OFFSET 0x0c87
#define regMC_VM_FB_OFFSET_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x0c88
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x0c89
#define regMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 0
#define regMC_VM_XGMI_LFB_CNTL 0x0c97
#define regMC_VM_XGMI_LFB_CNTL_BASE_IDX 0
#define regMC_VM_XGMI_LFB_SIZE 0x0c98
#define regMC_VM_XGMI_LFB_SIZE_BASE_IDX 0
// addressBlock: aid_mmhub_utcl2_vmsharedvcdec
// base address: 0x63270
#define regMC_VM_FB_LOCATION_BASE 0x0c9c
#define regMC_VM_FB_LOCATION_BASE_BASE_IDX 0
#define regMC_VM_FB_LOCATION_TOP 0x0c9d
#define regMC_VM_FB_LOCATION_TOP_BASE_IDX 0
#define regMC_VM_AGP_TOP 0x0c9e
#define regMC_VM_AGP_TOP_BASE_IDX 0
#define regMC_VM_AGP_BOT 0x0c9f
#define regMC_VM_AGP_BOT_BASE_IDX 0
#define regMC_VM_AGP_BASE 0x0ca0
#define regMC_VM_AGP_BASE_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x0ca1
#define regMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 0
#define regMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x0ca2
#define regMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 0
#define regMC_VM_MX_L1_TLB_CNTL 0x0ca3
#define regMC_VM_MX_L1_TLB_CNTL_BASE_IDX 0
// addressBlock: aid_mmhub_mm_cane_mmcanedec
// base address: 0x635f0
#define regMM_CANE_UE_ERR_STATUS_LO 0x0d8d
#define regMM_CANE_UE_ERR_STATUS_LO_BASE_IDX 0
#define regMM_CANE_UE_ERR_STATUS_HI 0x0d8e
#define regMM_CANE_UE_ERR_STATUS_HI_BASE_IDX 0
#define regMM_CANE_CE_ERR_STATUS_LO 0x0d8f
#define regMM_CANE_CE_ERR_STATUS_LO_BASE_IDX 0
#define regMM_CANE_CE_ERR_STATUS_HI 0x0d90
#define regMM_CANE_CE_ERR_STATUS_HI_BASE_IDX 0
#endif
