/*
 * Copyright 2023 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _mmhub_3_3_0_OFFSET_HEADER
#define _mmhub_3_3_0_OFFSET_HEADER

// addressBlock: mmhub_dagbdec
// base address: 0x68000
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x0091
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 1
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x0092
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 1
#define regDAGB0_CNTL_MISC2 0x0097
#define regDAGB0_CNTL_MISC2_BASE_IDX 1
// addressBlock: mmhub_l1tlb_mmvmtlspfdec
// base address: 0x696c0
#define regMMVM_L2_SAW_CNTL4 0x0707
#define regMMVM_L2_SAW_CNTL4_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_CNTL 0x0708
#define regMMVM_L2_SAW_CONTEXT0_CNTL_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x070a
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x070b
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x070c
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x070d
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x070e
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x070f
#define regMMVM_L2_SAW_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
#define regMMVM_L2_SAW_CONTEXTS_DISABLE 0x0710
#define regMMVM_L2_SAW_CONTEXTS_DISABLE_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmatcl2dec
// base address: 0x69f00
#define regMM_ATC_L2_MISC_CG 0x07cd
#define regMM_ATC_L2_MISC_CG_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvml2pfdec
// base address: 0x6a000
#define regMMVM_L2_CNTL 0x0800
#define regMMVM_L2_CNTL_BASE_IDX 1
#define regMMVM_L2_CNTL2 0x0801
#define regMMVM_L2_CNTL2_BASE_IDX 1
#define regMMVM_L2_CNTL3 0x0802
#define regMMVM_L2_CNTL3_BASE_IDX 1
#define regMMVM_L2_PROTECTION_FAULT_CNTL 0x0808
#define regMMVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 1
#define regMMVM_L2_PROTECTION_FAULT_CNTL2 0x0809
#define regMMVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 1
#define regMMVM_L2_PROTECTION_FAULT_STATUS 0x080c
#define regMMVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 1
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x080f
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 1
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x0810
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 1
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0812
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 1
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0813
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 1
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0814
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 1
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0815
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 1
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0816
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 1
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0817
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 1
#define regMMVM_L2_CNTL4 0x0818
#define regMMVM_L2_CNTL4_BASE_IDX 1
#define regMMVM_L2_BANK_SELECT_RESERVED_CID2 0x081b
#define regMMVM_L2_BANK_SELECT_RESERVED_CID2_BASE_IDX 1
#define regMMVM_L2_CNTL5 0x081e
#define regMMVM_L2_CNTL5_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvml2vcdec
// base address: 0x6a100
#define regMMVM_CONTEXT0_CNTL 0x0840
#define regMMVM_CONTEXT0_CNTL_BASE_IDX 1
#define regMMVM_CONTEXT1_CNTL 0x0841
#define regMMVM_CONTEXT1_CNTL_BASE_IDX 1
#define regMMVM_CONTEXTS_DISABLE 0x0850
#define regMMVM_CONTEXTS_DISABLE_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG0_SEM 0x0851
#define regMMVM_INVALIDATE_ENG0_SEM_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG0_REQ 0x0863
#define regMMVM_INVALIDATE_ENG0_REQ_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG1_REQ 0x0864
#define regMMVM_INVALIDATE_ENG1_REQ_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG0_ACK 0x0875
#define regMMVM_INVALIDATE_ENG0_ACK_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0887
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0888
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 1
#define regMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0889
#define regMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 1
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x08ab
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x08ac
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 1
#define regMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x08ad
#define regMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 1
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x08cb
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x08cc
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x08cd
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 1
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x08ce
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 1
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x08eb
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x08ec
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x08ed
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 1
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x08ee
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvmsharedpfdec
// base address: 0x6a740
#define regMMMC_VM_FB_OFFSET 0x09d7
#define regMMMC_VM_FB_OFFSET_BASE_IDX 1
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x09d8
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 1
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x09d9
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 1
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_START 0x09df
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_START_BASE_IDX 1
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_END 0x09e0
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_END_BASE_IDX 1
#define regMMMC_VM_LOCAL_FB_ADDRESS_START 0x09e2
#define regMMMC_VM_LOCAL_FB_ADDRESS_START_BASE_IDX 1
#define regMMMC_VM_LOCAL_FB_ADDRESS_END 0x09e3
#define regMMMC_VM_LOCAL_FB_ADDRESS_END_BASE_IDX 1
// addressBlock: mmhub_mmutcl2_mmvmsharedvcdec
// base address: 0x6a7b0
#define regMMMC_VM_FB_LOCATION_BASE 0x09ec
#define regMMMC_VM_FB_LOCATION_BASE_BASE_IDX 1
#define regMMMC_VM_FB_LOCATION_TOP 0x09ed
#define regMMMC_VM_FB_LOCATION_TOP_BASE_IDX 1
#define regMMMC_VM_AGP_TOP 0x09ee
#define regMMMC_VM_AGP_TOP_BASE_IDX 1
#define regMMMC_VM_AGP_BOT 0x09ef
#define regMMMC_VM_AGP_BOT_BASE_IDX 1
#define regMMMC_VM_AGP_BASE 0x09f0
#define regMMMC_VM_AGP_BASE_BASE_IDX 1
#define regMMMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x09f1
#define regMMMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 1
#define regMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x09f2
#define regMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 1
#define regMMMC_VM_MX_L1_TLB_CNTL 0x09f3
#define regMMMC_VM_MX_L1_TLB_CNTL_BASE_IDX 1
#endif
