/*
 * Copyright (C) 2017  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _mmhub_9_3_0_OFFSET_HEADER
#define _mmhub_9_3_0_OFFSET_HEADER

// addressBlock: mmhub_dagbdec
// base address: 0x68000
#define mmDAGB0_RD_CGTT_CLK_CTRL 0x0015
#define mmDAGB0_RD_CGTT_CLK_CTRL_BASE_IDX 0
#define mmDAGB0_WR_CGTT_CLK_CTRL 0x0041
#define mmDAGB0_WR_CGTT_CLK_CTRL_BASE_IDX 0
#define mmDAGB0_CNTL_MISC2 0x0063
#define mmDAGB0_CNTL_MISC2_BASE_IDX 0
#define mmDAGB1_WRCLI2 0x00ae
#define mmDAGB1_WRCLI2_BASE_IDX 0
#define mmDAGB1_CNTL_MISC2 0x00e3
#define mmDAGB1_CNTL_MISC2_BASE_IDX 0
// addressBlock: mmhub_ea_mmeadec
// base address: 0x68400
#define mmMMEA0_EDC_CNT 0x0206
#define mmMMEA0_EDC_CNT_BASE_IDX 0
#define mmMMEA0_EDC_CNT2 0x0207
#define mmMMEA0_EDC_CNT2_BASE_IDX 0
#define mmMMEA0_ERR_STATUS 0x0211
#define mmMMEA0_ERR_STATUS_BASE_IDX 0
#define mmMMEA1_DRAM_WR_CLI2GRP_MAP0 0x0242
#define mmMMEA1_DRAM_WR_CLI2GRP_MAP0_BASE_IDX 0
#define mmMMEA1_EDC_CNT 0x0346
#define mmMMEA1_EDC_CNT_BASE_IDX 0
#define mmMMEA1_EDC_CNT2 0x0347
#define mmMMEA1_EDC_CNT2_BASE_IDX 0
#define mmMMEA1_ERR_STATUS 0x0351
#define mmMMEA1_ERR_STATUS_BASE_IDX 0
// addressBlock: mmhub_utcl2_atcl2dec
// base address: 0x69900
#define mmATC_L2_MISC_CG 0x064a
#define mmATC_L2_MISC_CG_BASE_IDX 0
// addressBlock: mmhub_utcl2_vml2pfdec
// base address: 0x69a00
#define mmVM_L2_CNTL 0x0680
#define mmVM_L2_CNTL_BASE_IDX 0
#define mmVM_L2_CNTL2 0x0681
#define mmVM_L2_CNTL2_BASE_IDX 0
#define mmVM_L2_CNTL3 0x0682
#define mmVM_L2_CNTL3_BASE_IDX 0
#define mmVM_L2_PROTECTION_FAULT_CNTL 0x0687
#define mmVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 0
#define mmVM_L2_PROTECTION_FAULT_CNTL2 0x0688
#define mmVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 0
#define mmVM_L2_PROTECTION_FAULT_STATUS 0x068b
#define mmVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 0
#define mmVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x068e
#define mmVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 0
#define mmVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x068f
#define mmVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 0
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0691
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 0
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0692
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 0
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0693
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 0
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0694
#define mmVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 0
#define mmVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0695
#define mmVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 0
#define mmVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0696
#define mmVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 0
#define mmVM_L2_CNTL4 0x0697
#define mmVM_L2_CNTL4_BASE_IDX 0
// addressBlock: mmhub_utcl2_vml2vcdec
// base address: 0x69b00
#define mmVM_CONTEXT0_CNTL 0x06c0
#define mmVM_CONTEXT0_CNTL_BASE_IDX 0
#define mmVM_CONTEXT1_CNTL 0x06c1
#define mmVM_CONTEXT1_CNTL_BASE_IDX 0
#define mmVM_INVALIDATE_ENG0_SEM 0x06d1
#define mmVM_INVALIDATE_ENG0_SEM_BASE_IDX 0
#define mmVM_INVALIDATE_ENG0_REQ 0x06e3
#define mmVM_INVALIDATE_ENG0_REQ_BASE_IDX 0
#define mmVM_INVALIDATE_ENG1_REQ 0x06e4
#define mmVM_INVALIDATE_ENG1_REQ_BASE_IDX 0
#define mmVM_INVALIDATE_ENG0_ACK 0x06f5
#define mmVM_INVALIDATE_ENG0_ACK_BASE_IDX 0
#define mmVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0707
#define mmVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 0
#define mmVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0708
#define mmVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 0
#define mmVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0709
#define mmVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 0
#define mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x072b
#define mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x072c
#define mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 0
#define mmVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x072d
#define mmVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define mmVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x074b
#define mmVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define mmVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x074c
#define mmVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define mmVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x074d
#define mmVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define mmVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x074e
#define mmVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define mmVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x076b
#define mmVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define mmVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x076c
#define mmVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#define mmVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x076d
#define mmVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define mmVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x076e
#define mmVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
// addressBlock: mmhub_utcl2_vmsharedpfdec
// base address: 0x6a040
#define mmMC_VM_FB_OFFSET 0x0817
#define mmMC_VM_FB_OFFSET_BASE_IDX 0
#define mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x0818
#define mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 0
#define mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x0819
#define mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 0
#define mmMC_MEM_POWER_LS 0x081c
#define mmMC_MEM_POWER_LS_BASE_IDX 0
#define mmMC_VM_XGMI_LFB_CNTL 0x0823
#define mmMC_VM_XGMI_LFB_CNTL_BASE_IDX 0
#define mmMC_VM_XGMI_LFB_SIZE 0x0824
#define mmMC_VM_XGMI_LFB_SIZE_BASE_IDX 0
// addressBlock: mmhub_utcl2_vmsharedvcdec
// base address: 0x6a0b0
#define mmMC_VM_FB_LOCATION_BASE 0x082c
#define mmMC_VM_FB_LOCATION_BASE_BASE_IDX 0
#define mmMC_VM_FB_LOCATION_TOP 0x082d
#define mmMC_VM_FB_LOCATION_TOP_BASE_IDX 0
#define mmMC_VM_AGP_TOP 0x082e
#define mmMC_VM_AGP_TOP_BASE_IDX 0
#define mmMC_VM_AGP_BOT 0x082f
#define mmMC_VM_AGP_BOT_BASE_IDX 0
#define mmMC_VM_AGP_BASE 0x0830
#define mmMC_VM_AGP_BASE_BASE_IDX 0
#define mmMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x0831
#define mmMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 0
#define mmMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x0832
#define mmMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 0
#define mmMC_VM_MX_L1_TLB_CNTL 0x0833
#define mmMC_VM_MX_L1_TLB_CNTL_BASE_IDX 0
#endif
