/*
 * Copyright 2023 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 */
#ifndef _mmhub_4_1_0_OFFSET_HEADER
#define _mmhub_4_1_0_OFFSET_HEADER

// addressBlock: mmhub_dagb_dagbdec
// base address: 0x68000
#define regDAGB0_CNTL_MISC2 0x00a1
#define regDAGB0_CNTL_MISC2_BASE_IDX 0
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x00d4
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x00d9
#define regDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 0
#define regDAGB1_CNTL_MISC2 0x023e
#define regDAGB1_CNTL_MISC2_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvmsharedpfdec
// base address: 0x69300
#define regMMMC_VM_FB_OFFSET 0x04c7
#define regMMMC_VM_FB_OFFSET_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x04c8
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x04c9
#define regMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 0
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_START 0x04ce
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_START_BASE_IDX 0
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_END 0x04cf
#define regMMMC_VM_LOCAL_SYSMEM_ADDRESS_END_BASE_IDX 0
#define regMMMC_VM_LOCAL_FB_ADDRESS_START 0x04d1
#define regMMMC_VM_LOCAL_FB_ADDRESS_START_BASE_IDX 0
#define regMMMC_VM_LOCAL_FB_ADDRESS_END 0x04d2
#define regMMMC_VM_LOCAL_FB_ADDRESS_END_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvml2pfdec
// base address: 0x69390
#define regMMVM_L2_CNTL 0x04e4
#define regMMVM_L2_CNTL_BASE_IDX 0
#define regMMVM_L2_CNTL2 0x04e5
#define regMMVM_L2_CNTL2_BASE_IDX 0
#define regMMVM_L2_CNTL3 0x04e6
#define regMMVM_L2_CNTL3_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_CNTL 0x04ec
#define regMMVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_CNTL2 0x04ed
#define regMMVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_STATUS_LO32 0x04f0
#define regMMVM_L2_PROTECTION_FAULT_STATUS_LO32_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x04f4
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 0
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x04f5
#define regMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x04f7
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x04f8
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x04f9
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 0
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x04fa
#define regMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 0
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x04fb
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 0
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x04fc
#define regMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 0
#define regMMVM_L2_CNTL4 0x04fd
#define regMMVM_L2_CNTL4_BASE_IDX 0
#define regMMVM_L2_BANK_SELECT_RESERVED_CID2 0x0500
#define regMMVM_L2_BANK_SELECT_RESERVED_CID2_BASE_IDX 0
#define regMMVM_L2_CNTL5 0x0503
#define regMMVM_L2_CNTL5_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvmsharedvcdec
// base address: 0x69550
#define regMMMC_VM_FB_LOCATION_BASE 0x0554
#define regMMMC_VM_FB_LOCATION_BASE_BASE_IDX 0
#define regMMMC_VM_FB_LOCATION_TOP 0x0555
#define regMMMC_VM_FB_LOCATION_TOP_BASE_IDX 0
#define regMMMC_VM_AGP_TOP 0x0556
#define regMMMC_VM_AGP_TOP_BASE_IDX 0
#define regMMMC_VM_AGP_BOT 0x0557
#define regMMMC_VM_AGP_BOT_BASE_IDX 0
#define regMMMC_VM_AGP_BASE 0x0558
#define regMMMC_VM_AGP_BASE_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x0559
#define regMMMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 0
#define regMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x055a
#define regMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 0
#define regMMMC_VM_MX_L1_TLB_CNTL 0x055b
#define regMMMC_VM_MX_L1_TLB_CNTL_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvml2vcdec
// base address: 0x69590
#define regMMVM_CONTEXT0_CNTL 0x0564
#define regMMVM_CONTEXT0_CNTL_BASE_IDX 0
#define regMMVM_CONTEXT1_CNTL 0x0565
#define regMMVM_CONTEXT1_CNTL_BASE_IDX 0
#define regMMVM_CONTEXTS_DISABLE 0x0574
#define regMMVM_CONTEXTS_DISABLE_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_SEM 0x0575
#define regMMVM_INVALIDATE_ENG0_SEM_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_REQ 0x0587
#define regMMVM_INVALIDATE_ENG0_REQ_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG1_REQ 0x0588
#define regMMVM_INVALIDATE_ENG1_REQ_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_ACK 0x0599
#define regMMVM_INVALIDATE_ENG0_ACK_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x05ab
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x05ac
#define regMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 0
#define regMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x05ad
#define regMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x05cf
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x05d0
#define regMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x05d1
#define regMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x05ef
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x05f0
#define regMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x05f1
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x05f2
#define regMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x060f
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x0610
#define regMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x0611
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x0612
#define regMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#endif
