/*
 * Copyright (C) 2019  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _mmhub_2_0_0_OFFSET_HEADER
#define _mmhub_2_0_0_OFFSET_HEADER

// addressBlock: mmhub_dagbdec
// base address: 0x68000
#define mmDAGB0_RD_CGTT_CLK_CTRL 0x0018
#define mmDAGB0_RD_CGTT_CLK_CTRL_BASE_IDX 0
#define mmDAGB0_WR_CGTT_CLK_CTRL 0x0049
#define mmDAGB0_WR_CGTT_CLK_CTRL_BASE_IDX 0
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE 0x006d
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_BASE_IDX 0
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE 0x006e
#define mmDAGB0_WRCLI_GPU_SNOOP_OVERRIDE_VALUE_BASE_IDX 0
#define mmDAGB0_CNTL_MISC2 0x0071
#define mmDAGB0_CNTL_MISC2_BASE_IDX 0
// addressBlock: mmhub_mmea_mmeadec
// base address: 0x68400
#define mmMMEA0_EDC_CNT 0x020f
#define mmMMEA0_EDC_CNT_BASE_IDX 0
#define mmMMEA0_EDC_CNT2 0x0210
#define mmMMEA0_EDC_CNT2_BASE_IDX 0
#define mmMMEA0_ERR_STATUS 0x021a
#define mmMMEA0_ERR_STATUS_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmatcl2dec
// base address: 0x69900
#define mmMM_ATC_L2_MISC_CG 0x064a
#define mmMM_ATC_L2_MISC_CG_BASE_IDX 0
#define mmMM_ATC_L2_CGTT_CLK_CTRL 0x064c
#define mmMM_ATC_L2_CGTT_CLK_CTRL_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvml2pfdec
// base address: 0x69a00
#define mmMMVM_L2_CNTL 0x0680
#define mmMMVM_L2_CNTL_BASE_IDX 0
#define mmMMVM_L2_CNTL2 0x0681
#define mmMMVM_L2_CNTL2_BASE_IDX 0
#define mmMMVM_L2_CNTL3 0x0682
#define mmMMVM_L2_CNTL3_BASE_IDX 0
#define mmMMVM_L2_PROTECTION_FAULT_CNTL 0x0688
#define mmMMVM_L2_PROTECTION_FAULT_CNTL_BASE_IDX 0
#define mmMMVM_L2_PROTECTION_FAULT_CNTL2 0x0689
#define mmMMVM_L2_PROTECTION_FAULT_CNTL2_BASE_IDX 0
#define mmMMVM_L2_PROTECTION_FAULT_STATUS 0x068c
#define mmMMVM_L2_PROTECTION_FAULT_STATUS_BASE_IDX 0
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32 0x068f
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_LO32_BASE_IDX 0
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32 0x0690
#define mmMMVM_L2_PROTECTION_FAULT_DEFAULT_ADDR_HI32_BASE_IDX 0
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32 0x0692
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_LO32_BASE_IDX 0
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32 0x0693
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR_HI32_BASE_IDX 0
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32 0x0694
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_LO32_BASE_IDX 0
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32 0x0695
#define mmMMVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR_HI32_BASE_IDX 0
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32 0x0696
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_LO32_BASE_IDX 0
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32 0x0697
#define mmMMVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET_HI32_BASE_IDX 0
#define mmMMVM_L2_CNTL4 0x0698
#define mmMMVM_L2_CNTL4_BASE_IDX 0
#define mmMMVM_L2_CNTL5 0x06a1
#define mmMMVM_L2_CNTL5_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvml2vcdec
// base address: 0x69b00
#define mmMMVM_CONTEXT0_CNTL 0x06c0
#define mmMMVM_CONTEXT0_CNTL_BASE_IDX 0
#define mmMMVM_CONTEXT1_CNTL 0x06c1
#define mmMMVM_CONTEXT1_CNTL_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG0_SEM 0x06d1
#define mmMMVM_INVALIDATE_ENG0_SEM_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG0_REQ 0x06e3
#define mmMMVM_INVALIDATE_ENG0_REQ_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG1_REQ 0x06e4
#define mmMMVM_INVALIDATE_ENG1_REQ_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG0_ACK 0x06f5
#define mmMMVM_INVALIDATE_ENG0_ACK_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32 0x0707
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_LO32_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32 0x0708
#define mmMMVM_INVALIDATE_ENG0_ADDR_RANGE_HI32_BASE_IDX 0
#define mmMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32 0x0709
#define mmMMVM_INVALIDATE_ENG1_ADDR_RANGE_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32 0x072b
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32 0x072c
#define mmMMVM_CONTEXT0_PAGE_TABLE_BASE_ADDR_HI32_BASE_IDX 0
#define mmMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32 0x072d
#define mmMMVM_CONTEXT1_PAGE_TABLE_BASE_ADDR_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32 0x074b
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32 0x074c
#define mmMMVM_CONTEXT0_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32 0x074d
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32 0x074e
#define mmMMVM_CONTEXT1_PAGE_TABLE_START_ADDR_HI32_BASE_IDX 0
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32 0x076b
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32 0x076c
#define mmMMVM_CONTEXT0_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32 0x076d
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_LO32_BASE_IDX 0
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32 0x076e
#define mmMMVM_CONTEXT1_PAGE_TABLE_END_ADDR_HI32_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvmsharedpfdec
// base address: 0x6a140
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB 0x0858
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_LSB_BASE_IDX 0
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB 0x0859
#define mmMMMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR_MSB_BASE_IDX 0
// addressBlock: mmhub_mmutcl2_mmvmsharedvcdec
// base address: 0x6a1b0
#define mmMMMC_VM_FB_LOCATION_BASE 0x086c
#define mmMMMC_VM_FB_LOCATION_BASE_BASE_IDX 0
#define mmMMMC_VM_FB_LOCATION_TOP 0x086d
#define mmMMMC_VM_FB_LOCATION_TOP_BASE_IDX 0
#define mmMMMC_VM_AGP_TOP 0x086e
#define mmMMMC_VM_AGP_TOP_BASE_IDX 0
#define mmMMMC_VM_AGP_BOT 0x086f
#define mmMMMC_VM_AGP_BOT_BASE_IDX 0
#define mmMMMC_VM_AGP_BASE 0x0870
#define mmMMMC_VM_AGP_BASE_BASE_IDX 0
#define mmMMMC_VM_SYSTEM_APERTURE_LOW_ADDR 0x0871
#define mmMMMC_VM_SYSTEM_APERTURE_LOW_ADDR_BASE_IDX 0
#define mmMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR 0x0872
#define mmMMMC_VM_SYSTEM_APERTURE_HIGH_ADDR_BASE_IDX 0
#define mmMMMC_VM_MX_L1_TLB_CNTL 0x0873
#define mmMMMC_VM_MX_L1_TLB_CNTL_BASE_IDX 0
#endif
