/*
 * Copyright (C) 2017  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#ifndef _nbif_6_1_SH_MASK_HEADER
#define _nbif_6_1_SH_MASK_HEADER

//BIF_SDMA0_DOORBELL_RANGE
#define BIF_SDMA0_DOORBELL_RANGE__OFFSET__SHIFT 0x2
#define BIF_SDMA0_DOORBELL_RANGE__SIZE__SHIFT 0x10
//BIF_IH_DOORBELL_RANGE
#define BIF_IH_DOORBELL_RANGE__OFFSET__SHIFT 0x2
#define BIF_IH_DOORBELL_RANGE__SIZE__SHIFT 0x10
//BIF_MMSCH0_DOORBELL_RANGE
#define BIF_MMSCH0_DOORBELL_RANGE__OFFSET__SHIFT 0x2
#define BIF_MMSCH0_DOORBELL_RANGE__SIZE__SHIFT 0x10
//EP_PCIE_TX_LTR_CNTL
#define EP_PCIE_TX_LTR_CNTL__LTR_PRIV_MSG_DIS_IN_PM_NON_D0__SHIFT 0xe
#define EP_PCIE_TX_LTR_CNTL__LTR_PRIV_RST_LTR_IN_DL_DOWN__SHIFT 0xf
//INTERRUPT_CNTL
#define INTERRUPT_CNTL__IH_DUMMY_RD_OVERRIDE__SHIFT 0x0
#define INTERRUPT_CNTL__IH_REQ_NONSNOOP_EN__SHIFT 0x3
//BIF_CLK_CTRL
#define BIF_CLK_CTRL__BIF_XSTCLK_READY__SHIFT 0x0
//BIF_DOORBELL_CNTL
#define BIF_DOORBELL_CNTL__DOORBELL_MONITOR_EN__SHIFT 0x4
//BIF_DOORBELL_INT_CNTL
#define BIF_DOORBELL_INT_CNTL__DOORBELL_INTERRUPT_STATUS__SHIFT 0x0
#define BIF_DOORBELL_INT_CNTL__DOORBELL_INTERRUPT_CLEAR__SHIFT 0x10
//BIF_FB_EN
#define BIF_FB_EN__FB_READ_EN__SHIFT 0x0
#define BIF_FB_EN__FB_WRITE_EN__SHIFT 0x1
//BACO_CNTL
#define BACO_CNTL__BACO_EN__SHIFT 0x0
#define BACO_CNTL__BACO_BIF_LCLK_SWITCH__SHIFT 0x1
#define BACO_CNTL__BACO_DUMMY_EN__SHIFT 0x2
#define BACO_CNTL__BACO_POWER_OFF__SHIFT 0x3
#define BACO_CNTL__BACO_DSTATE_BYPASS__SHIFT 0x5
#define BACO_CNTL__BACO_RST_INTR_MASK__SHIFT 0x6
#define BACO_CNTL__BACO_MODE__SHIFT 0x8
#define BACO_CNTL__RCU_BIF_CONFIG_DONE__SHIFT 0x9
//BIF_RB_CNTL
#define BIF_RB_CNTL__RB_ENABLE__SHIFT 0x0
//RCC_DEV0_EPF0_STRAP0
#define RCC_DEV0_EPF0_STRAP0__STRAP_ATI_REV_ID_DEV0_F0__SHIFT 0x18
//DOORBELL_SELFRING_GPA_APER_CNTL
#define DOORBELL_SELFRING_GPA_APER_CNTL__DOORBELL_SELFRING_GPA_APER_EN__SHIFT 0x0
#define DOORBELL_SELFRING_GPA_APER_CNTL__DOORBELL_SELFRING_GPA_APER_SIZE__SHIFT 0x8
//GPU_HDP_FLUSH_DONE
#define GPU_HDP_FLUSH_DONE__CP0__SHIFT 0x0
#define GPU_HDP_FLUSH_DONE__CP1__SHIFT 0x1
#define GPU_HDP_FLUSH_DONE__CP2__SHIFT 0x2
#define GPU_HDP_FLUSH_DONE__CP3__SHIFT 0x3
#define GPU_HDP_FLUSH_DONE__CP4__SHIFT 0x4
#define GPU_HDP_FLUSH_DONE__CP5__SHIFT 0x5
#define GPU_HDP_FLUSH_DONE__CP6__SHIFT 0x6
#define GPU_HDP_FLUSH_DONE__CP7__SHIFT 0x7
#define GPU_HDP_FLUSH_DONE__CP8__SHIFT 0x8
#define GPU_HDP_FLUSH_DONE__CP9__SHIFT 0x9
#define GPU_HDP_FLUSH_DONE__SDMA0__SHIFT 0xa
#define GPU_HDP_FLUSH_DONE__SDMA1__SHIFT 0xb
//MAILBOX_MSGBUF_TRN_DW0
#define MAILBOX_MSGBUF_TRN_DW0__MSGBUF_DATA__SHIFT 0x0
//MAILBOX_CONTROL
#define MAILBOX_CONTROL__TRN_MSG_VALID__SHIFT 0x0
#define MAILBOX_CONTROL__RCV_MSG_ACK__SHIFT 0x9
//MAILBOX_INT_CNTL
#define MAILBOX_INT_CNTL__VALID_INT_EN__SHIFT 0x0
#define MAILBOX_INT_CNTL__ACK_INT_EN__SHIFT 0x1
// addressBlock: rcc_pf_0_BIFPFVFDEC1
//RCC_DOORBELL_APER_EN
#define RCC_DOORBELL_APER_EN__BIF_DOORBELL_APER_EN__SHIFT 0x0
//RCC_DEV0_EPF2_STRAP2
#define RCC_DEV0_EPF2_STRAP2__STRAP_NO_SOFT_RESET_DEV0_F2__SHIFT 0x7
//BIF_SDMA0_DOORBELL_RANGE
#define BIF_SDMA0_DOORBELL_RANGE__OFFSET__MASK 0x00000FFCL
#define BIF_SDMA0_DOORBELL_RANGE__SIZE__MASK 0x001F0000L
//BIF_IH_DOORBELL_RANGE
#define BIF_IH_DOORBELL_RANGE__OFFSET__MASK 0x00000FFCL
#define BIF_IH_DOORBELL_RANGE__SIZE__MASK 0x001F0000L
//BIF_MMSCH0_DOORBELL_RANGE
#define BIF_MMSCH0_DOORBELL_RANGE__OFFSET__MASK 0x00000FFCL
#define BIF_MMSCH0_DOORBELL_RANGE__SIZE__MASK 0x001F0000L
//INTERRUPT_CNTL
#define INTERRUPT_CNTL__IH_DUMMY_RD_OVERRIDE__MASK 0x00000001L
#define INTERRUPT_CNTL__IH_REQ_NONSNOOP_EN__MASK 0x00000008L
//BIF_DOORBELL_CNTL
#define BIF_DOORBELL_CNTL__DOORBELL_MONITOR_EN__MASK 0x00000010L
//BIF_DOORBELL_INT_CNTL
#define BIF_DOORBELL_INT_CNTL__DOORBELL_INTERRUPT_CLEAR__MASK 0x00010000L
//BIF_FB_EN
#define BIF_FB_EN__FB_READ_EN__MASK 0x00000001L
#define BIF_FB_EN__FB_WRITE_EN__MASK 0x00000002L
//BACO_CNTL
#define BACO_CNTL__BACO_EN__MASK 0x00000001L
#define BACO_CNTL__BACO_BIF_LCLK_SWITCH__MASK 0x00000002L
#define BACO_CNTL__BACO_DUMMY_EN__MASK 0x00000004L
#define BACO_CNTL__BACO_POWER_OFF__MASK 0x00000008L
#define BACO_CNTL__BACO_DSTATE_BYPASS__MASK 0x00000020L
#define BACO_CNTL__BACO_RST_INTR_MASK__MASK 0x00000040L
#define BACO_CNTL__BACO_MODE__MASK 0x00000100L
//RCC_DEV0_EPF0_STRAP0
#define RCC_DEV0_EPF0_STRAP0__STRAP_ATI_REV_ID_DEV0_F0__MASK 0x0F000000L
//DOORBELL_SELFRING_GPA_APER_CNTL
#define DOORBELL_SELFRING_GPA_APER_CNTL__DOORBELL_SELFRING_GPA_APER_EN__MASK 0x00000001L
#define DOORBELL_SELFRING_GPA_APER_CNTL__DOORBELL_SELFRING_GPA_APER_SIZE__MASK 0x0000FF00L
//GPU_HDP_FLUSH_DONE
#define GPU_HDP_FLUSH_DONE__SDMA0__MASK 0x00000400L
#define GPU_HDP_FLUSH_DONE__SDMA1__MASK 0x00000800L
//MAILBOX_MSGBUF_TRN_DW0
#define MAILBOX_MSGBUF_TRN_DW0__MSGBUF_DATA__MASK 0xFFFFFFFFL
//MAILBOX_CONTROL
#define MAILBOX_CONTROL__TRN_MSG_VALID__MASK 0x00000001L
#define MAILBOX_CONTROL__RCV_MSG_ACK__MASK 0x00000200L
//MAILBOX_INT_CNTL
#define MAILBOX_INT_CNTL__VALID_INT_EN__MASK 0x00000001L
#define MAILBOX_INT_CNTL__ACK_INT_EN__MASK 0x00000002L
// addressBlock: rcc_pf_0_BIFPFVFDEC1
//RCC_DOORBELL_APER_EN
#define RCC_DOORBELL_APER_EN__BIF_DOORBELL_APER_EN__MASK 0x00000001L
#endif
